### ISSUE TITLE
Is it possible to execute command when creating the terminal?

### ISSUE THREAD

**Issue by lonelywolf4git** [sourcelair/xterm.js#1006]
I want to execute one command like 'ls' when creating the terminal, is it possible to do this?I also see there is on issue to discuss this.

https://github.com/sourcelair/xterm.js/issues/605

I see you give him some hint, I will appreciate that if you give me example code. thanks!

**Comment by Tyriar** [comment]
If you want to run a command when you launch you should either send the command directly to the pty. If you're using node-pty try `pty.write('ls')`. You can also do this by telling the shell to run the command, so launch `bash -c 'ls'` instead of just `bash`.
