### ISSUE TITLE
Links are sometimes not applied

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#1025]
VS Code issue https://github.com/Microsoft/vscode/issues/35552

**Comment by johnbendi** [comment]
I still get this issue at times. Even in the same terminal some links are clickable while some others are not. I don't even know where to start troubleshooting!

**Comment by Tyriar** [comment]
@johnbendi I've also seen it happen at least once, it seems like a different breakage and happens very rarely.
