### ISSUE TITLE
Resizing horizontally breaks the prompt

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#103]
Open demo:

![image](https://cloud.githubusercontent.com/assets/2193314/15917381/0c144f7e-2db1-11e6-8aec-f62012bcf5e5.png)

Run `term.resize(term.cols - 2, term.rows)` several times

![image](https://cloud.githubusercontent.com/assets/2193314/15917392/1f73cb44-2db1-11e6-9de3-057d250ff5fc.png)

The cursor will not go to the end of the line, the characters to the right are seemingly deleted. Pressing <kbd>enter</kbd> shows that they were just invisible on the UI:

![image](https://cloud.githubusercontent.com/assets/2193314/15917404/3b33b894-2db1-11e6-931e-806b130b0a8f.png)

When the horizontal size is changed, the terminal should wrap the prompt (ideally lines above the prompt too), just like when entering text into a narrow terminal:

![image](https://cloud.githubusercontent.com/assets/2193314/15917417/66803112-2db1-11e6-8e50-76a8ab9ac683.png)

**Comment by parisk** [comment]
@Tyriar does this still happen, after we merged #101?

**Comment by Tyriar** [comment]
@parisk yes, #101 only fixed resizing rows, this is resizing columns. Also I'll probably take a crack at fixing this one too if you want to assign to me.

**Comment by parisk** [comment]
It seems that GitHub won't let me assign this to you, but feel free to take this over. It would be amazing to have a PR for this.

**Comment by Tyriar** [comment]
Another note on this, the `&nbsp;` characters at the end seem to get cut and never refreshed, meaning that scroll events on the rows that are cut short don't make it to the terminal.

**Comment by parisk** [comment]
Would stripping all trailing `&nbsp;`s help?

**Comment by Tyriar** [comment]
@parisk the `&nbsp;` are good I think, provided the character width problems are handled. The `&nbsp;` and other characters if possible need to be restored.

**Comment by waywaaard** [comment]
This is still broken, right?

**Comment by Tyriar** [comment]
@waywaaard yes, the terminal should still work after resizing fine, it just truncates a chunk of the output.

**Comment by waywaaard** [comment]
Yeah, I mean the truncating. Is there a (*hacky*) way of fixing this for now?

**Comment by Tyriar** [comment]
No workaround, the characters are discarded on resize. The fix for this is to enable wrapping or to hang on to the lines and not display them.

**Comment by Tyriar** [comment]
I believe this is fixed after https://github.com/sourcelair/xterm.js/pull/616
