### ISSUE TITLE
Emulation: bold off broken and dim not implemented?

### ISSUE THREAD

**Issue by theflyingape** [sourcelair/xterm.js#1042]
Shutting off (20 + attribute) **bold** is not working, although others implemented (uline and reverse) do, i.e.,
```
echo -e '\x1B[33m yellow \x1B[1m bold \x1B[21m normal \x1B[m off'
echo -e '\x1B[33m yellow \x1B[4m uline \x1B[24m normal \x1B[m off'
echo -e '\x1B[33m yellow \x1B[7m reverse \x1B[27m normal \x1B[m off'
````

Oddly enough, changing **21** (bold off) to **22** (dim off) works:
`echo -e '\x1B[33m yellow \x1B[1m bold \x1B[22m normal \x1B[m off'`

... but bold -> dim _enable_ keeps bold _on_ -- I thought bold/dim are implemented as mutually exclusive, unlike underline, blink, and reverse that can be added or taken away with either bold or dim?  At the very least if dim is not implemented, it should shutoff bold, but it does not:
`echo -e '\x1B[33m yellow \x1B[1m bold \x1B[2m dim \x1B[m off'`

Two related questions:
1. I get **blink** (at least for now ;) not implemented, but how about **dim** and _italic_?
2. Can a custom color palette be constructed?  The one in v3 branch (below) is more palatable to me.

## Details
- Browser and browser version: Firefox 56 (64-bit)
- OS version: Fedora 26 (linux)
- xterm.js version: 2.9.2 and latest v3 branch

### Steps to reproduce
```
$ cat bin/ansi-test.sh
#!/bin/sh

alias print='echo -en'
alias println='echo -e'
csi="\\x1B["
color=( black red green yellow blue magenta cyan white )
attr=( reset bright dim italic uline blink 6 reverse )

for bg in `seq 0 7`; do
        print "(${csi}m${bg}) BG ${csi}0;1;$((30+${bg}))m ${color[${bg}]}${csi}m"
        for fg in `seq 0 7`; do
                print "\n    FG ${csi}0;1;$((30+${fg}))m ${color[${fg}]}${csi}m\t"
                print "${csi}$((40+${bg}))m"
                print "${csi}$((30+${fg}))m"
                for ca in `seq 1 7`; do
                        print "${csi}${ca}m  ${attr[${ca}]}  ${csi}$((20+${ca}))m"
                done
                print "${csi}m"
        done
        println "${csi}m"
done
```
**Showing Terminology - xterm.js - v3 branch:**
![terminology xterm v3](https://user-images.githubusercontent.com/19166945/31338262-7793b2d0-accc-11e7-919f-181db466cc3e.png)

**Comment by mofux** [comment]
@theflyingape I don't think bold/dim are mutually exclusive, at least not in `Terminal.app`:

<img width="770" alt="screen shot 2017-10-09 at 15 58 51" src="https://user-images.githubusercontent.com/2785983/31341754-cafd0a46-ad0a-11e7-8af2-c1cb086f5d93.png">

**Comment by mofux** [comment]
I can confirm dim support is not available, and looking into master, probably never has been?

**Comment by theflyingape** [comment]
Thanks, I do not understand your reference to `Terminal.app`, I was running the `demo/app` as pictured.
Does bold have to change font style, or can it be configured to only alter palette?
What you show here is closer to what is needed: I see your dim changed the color to a darker yellow -- yay, although I cannot reproduce that in demo/app.  However, it kept the font-style as **bold** whereas I'd expect it to back to normal -- or a lighter weight to be consistent with bold?

**Comment by mofux** [comment]
I am referring to the behaviour of clearing the bold style when setting dim. Terminal.app does not clear the bold style on dim. xterm (v3 branch) behaves exactly the same, but it does not support dim yet, which is why the text is not dimmed:

xterm.js (v3)
<img width="763" alt="screen shot 2017-10-09 at 16 17 55" src="https://user-images.githubusercontent.com/2785983/31342558-741b91ea-ad0d-11e7-8919-9efdfb622444.png">

**Comment by theflyingape** [comment]
I see your point clearly now.  And I now see `InputHandler.ts` has a p === 22 listed as "not bold".
Until dim is supported, can that be changed to (p === 21 || p === 22) to allow for the correct 21 code to be consumed while maintaining backward compatibility?

**Comment by mofux** [comment]
I'll try to create a PR to enable dim support.

**Comment by Tyriar** [comment]
Related: https://github.com/sourcelair/xterm.js/issues/580
