### ISSUE TITLE
Characters are condensed

### ISSUE THREAD

**Issue by mofux** [sourcelair/xterm.js#1046]
Since #1038 I am noticing that characters aren't as sharp as before. They also look not wide enough. Here is a direct comparision:

(expected) before #1038 
<img width="796" alt="screen shot 2017-10-10 at 20 47 43" src="https://user-images.githubusercontent.com/2785983/31404682-0c8f8d2e-adfd-11e7-898c-2c91cea7d2b2.png">

(current) since #1038 
<img width="796" alt="screen shot 2017-10-10 at 20 49 17" src="https://user-images.githubusercontent.com/2785983/31404698-1592a852-adfd-11e7-8704-eb066c2671a4.png">

I think only cached characters have this problem.

**Comment by Tyriar** [comment]
Something doesn't look right here, this is at 100% zoom level in the image above for before:

<img width="584" alt="screen shot 2017-10-10 at 12 42 59 pm" src="https://user-images.githubusercontent.com/2193314/31407152-ad8b1cc4-adb8-11e7-9358-f690cee930d8.png">

Something like this is I expect to see:

<img width="414" alt="screen shot 2017-10-10 at 12 45 43 pm" src="https://user-images.githubusercontent.com/2193314/31407209-f171444a-adb8-11e7-9a4e-b8098bd9e3ca.png">

Did you zoom into the screenshots or something?

Also the only remaining issue AFAIK is that the character don't use standard spacing which is only tracked in https://github.com/Microsoft/vscode/issues/35695 atm

**Comment by mofux** [comment]
Hmmm.... can't reproduce this blurriness when comparing both pictures:

<img width="795" alt="screen shot 2017-10-10 at 21 59 39" src="https://user-images.githubusercontent.com/2785983/31407795-7619e5ba-ae06-11e7-8d2a-49591e96f2b6.png">

But look at the space between the `af` in the `staff`. Before there was 1px space, now there is 2px space between the right line of the `a` and the left arm of the `f`. The same is also visible when checking the gap between the `s` and the `t`.

**Comment by Tyriar** [comment]
So I can tell "right.png" is an older version because the top-right of the `f` is cut off. What commit and font is that? I see a different font as the default on macOS.

**Comment by mofux** [comment]
"right" is on commit 22af08d. You can replicate the settings on Mac by pasting this into your dev console of the demo:

```javascript
term.setOption('fontFamily', 'monaco');
term.setOption('fontSize', 13);
```

If you look on the `t` or `f` strokes, you can clearly see that they are 1px smaller on the `wrong.png`

**Comment by Tyriar** [comment]
This might be the same as https://github.com/sourcelair/xterm.js/issues/1050

**Comment by mofux** [comment]
It is, your patch from https://github.com/Tyriar/xterm.js/commit/09c9cb4508bc13a8b5960e06b5eb34f2c93e66f3 solves this issue!
