### ISSUE TITLE
term.refresh problems

### ISSUE THREAD

**Issue by ricktbaker** [sourcelair/xterm.js#1054]
Executing a term.refresh doesn't seem to be actually refreshing.    I've had to modify the resize method with a custom method for a few reasons, and that's working well.   But after a resize I'm calling:

        term.refresh(0, term.rows - 1);

And I would expect it to redraw the existing contents to fit the resized screen.   But it doesn't appear to be happening at all.   If the screen is set to smaller, the text is just cut off.   If it's set wider, there is just a bunch of dead space.    Any new lines added fill the space properly.   I've been trying to add some breakpoints in to figure out if it's being called, but no success thus far.

EDIT: Even inspecting the this._terminal.rowContainer() element before its' being appended on the refresh shows each line being cut off instead of being put on to the next line.   Further researching this shows that as it's working through the number of lines, when it calculates the width of the terminal, it is just cutting off the content at that width and it's just disappearing from the dom instead of being put onto the next terminal line.

## Details
- Browser and browser version: electron 1.7.8
- OS version: mac os 10.12.6
- xterm.js version: 2.9.2

**Comment by Tyriar** [comment]
I think you're after this feature which we don't support yet: https://github.com/sourcelair/xterm.js/issues/622
