### ISSUE TITLE
Migration to v3 and the module.exports

### ISSUE THREAD

**Issue by exsilium** [sourcelair/xterm.js#1066]
Hi! So I'm trying to move to the v3 branch and I'm seeing that many of the previously existing interfaces are dropped:

v2:
```
Terminal.EventEmitter = EventEmitter_1.EventEmitter;
Terminal.inherits = inherits;
Terminal.on = on;
Terminal.off = off;
Terminal.cancel = cancel;
```
vs.

v3: 
```
var Terminal_1 = require("./Terminal");
module.exports = Terminal_1.Terminal;
```

Apart from inherits being dropped, what's the guidance here. How do I tap into the EventEmitter and the helper on/off/cancel directly? Why the change?

**Comment by Tyriar** [comment]
You were never meant to use `on`/`off`/`cancel` on `Terminal`. You can access `on` and `off` on each individual `Terminal` object:

```js
var t = new Terminal();
t.on(''scroll', () => {});
```

https://xtermjs.org/docs/api/terminal/#onevent-callback

If this is not sufficient, please elaborate what the use case is 😃

**Comment by exsilium** [comment]
Yes, digesting this a bit, I guess I was (ab)using the EventEmitter for the wrong purposes and the other interface changes looks good. So I'm good - closing and Thanks! :bowtie:
