### ISSUE TITLE
Right-click menu is not correct when terminal is in a bootstrap modal window

### ISSUE THREAD

**Issue by daemonic13** [sourcelair/xterm.js#1077]
With xterm inside a bootstrap modal window, the right click menu shows:
![image](https://user-images.githubusercontent.com/753286/31897130-7b03395a-b7e3-11e7-8fdd-8467efe6c054.png)

Which doesn't allow for copy, paste, etc...

## Details
- Browser and browser version:  Chrome v61.0.3163.100
- OS version:  Win 10
- xterm.js version: 2.9.1

### Steps to reproduce

1.  Run demo using attached index.html.txt (replace the demo index.html with it)
2.  Right click on terminal window, incorrect context menu appears

[index.html.txt](https://github.com/sourcelair/xterm.js/files/1407715/index.html.txt)

**Comment by Tyriar** [comment]
This is probably more of a problem with bootstrap using conflicting `z-index`'s or something, you will need to work around the issue in your codebase.
