### ISSUE TITLE
Could I set a backgroud-image in the new version.

### ISSUE THREAD

**Issue by songlijun** [sourcelair/xterm.js#1082]
before i pull the newest v3 version, I can set a backgroud image  and it's opacity like this:
// backgroud
        $(".terminal .xterm-viewport").css('background-image', 'url(' + url + ')');
        $(".terminal .xterm-viewport").css('-moz-opacity', opacity);
        $(".terminal .xterm-viewport").css('filter', 'alpha(opacity=' + (opacity * 100).toString() + ')');
        $(".terminal .xterm-viewport").css("opacity", opacity);

but now , i can't set backgroup image any more, could i have some interface to set a image^_^

**Comment by Tyriar** [comment]
You can no longer do this, you should be able to when transparent backgrounds are supported so closing in favor of https://github.com/sourcelair/xterm.js/issues/1004
