### ISSUE TITLE
Width of text rendering of canvas is smaller and unable to change it manually.

### ISSUE THREAD

**Issue by ganeshkbhat** [sourcelair/xterm.js#1086]
Issue: Width of text rendering of canvas is smaller and unable to change it manually.

##Details:
Rendering issues of width. I am trying to apply 100% width to terminal writes and I get line wrapped for half the terminal. I tried working with CompositionHelper.prototype.updateCompositionElements function by changing the textarea style and composition view style. But it did not help. Please check the image. Which is the correct renderer which creates the wrap width when the terminal is being created. 

## Details
- Browser and browser version: Chrome 62.0.x
- OS version: Windows/Linux
- xterm.js version: 2.9.2

that.xterm = new Terminal();
that.xterm.open('#elementReference');
that.xterm.write( `\r\n` + JSON.stringify(data));

![logwidth](https://user-images.githubusercontent.com/3424344/32051517-8f9752de-ba72-11e7-8fff-b505bf8304bd.png)

**Comment by mofux** [comment]
Do you use the `fit` addon to have the terminal automatically calculate the rows / cols to fit into the surrounding dom container? If not, you are probably seeing this issue because xterm operates on a fixed amount of rows / cols, that don't match the width of your document.

**Comment by ganeshkbhat** [comment]
Thank you for your precious time. Closing the issue.
