### ISSUE TITLE
Terminal display refresh after resize issue

### ISSUE THREAD

**Issue by bahinapster** [sourcelair/xterm.js#1087]
Hello i am trying to use the xterm.js lib on the web but i am facing an issue while resizing the terminal on fly where the content doesn't refresh.

## Details
- Chrome
- Mac os: 
- xterm.js version: 2.9.2

### Steps to reproduce

1. term.write( long text upper that 60 cols for example)
2. term.resize(50,40)

=> here the entered text will be cutted and the last 10 cols will not be displayed.

PS : i have tried refresh, the only way to hack this is by clearing the terminal and rewriting the text.

**Comment by mofux** [comment]
This behaviour is expected unfortunately. xterm.js does not automatically re-flow text if the terminal is resized. There have been some efforts to get this working, but unfortunately none of them have made it to production grade yet. It's still on our todo list though (see #622 for details).

**Comment by Tyriar** [comment]
Duplicate https://github.com/sourcelair/xterm.js/issues/622
