### ISSUE TITLE
setOption throws DOMException when setting theme

### ISSUE THREAD

**Issue by martin31821** [sourcelair/xterm.js#1089]
I'm using the following code to initialize xterm.js:
```
let term = new Terminal();
term.open(document.getElementById('xterm-system'));
term.setOption('fontFamily', 'Roboto Mono');
term.setOption('theme', LIGHT_THEME);
```

It throws the following exception when being run:
```
DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at xterm/lib/renderer/CharAtlas.js.CharAtlasGenerator.generate
    at Object.acquireCharAtlas
    at xterm/lib/renderer/BaseRenderLayer.js.BaseRenderLayer._refreshCharAtlas 
    at xterm/lib/renderer/BaseRenderLayer.js.BaseRenderLayer.onThemeChanged 
    at Array.forEach (<anonymous>)
    at xterm/lib/renderer/Renderer.js.Renderer.setTheme
    at xterm/lib/Terminal.js.Terminal._setTheme
    at xterm/lib/Terminal.js.Terminal.setOption
```

I picked the relevant line from `CharAtlasGenerator.generate`:
https://github.com/sourcelair/xterm.js/blob/v3/src/renderer/CharAtlas.ts#L199
```
 var charAtlasImageData = this._ctx.getImageData(0, 0, this._canvas.width, this._canvas.height);
```
where `this.canvas.width` and `this._canvas.height` are zero.

This is because `scaledCharWidth` and `scaledCharHeight` have the value `undefined` (see https://github.com/sourcelair/xterm.js/blob/v3/src/renderer/CharAtlas.ts#L130)

Chrome 62, Linux
XTerm.js v3 branch, commit `1d76cc921a53f16a0131b99a7a4dd407e343bfbc`

**Comment by Tyriar** [comment]
@martin31821 is `#xterm-system` hidden at the time you call `Terminal.open`?

**Comment by martin31821** [comment]
@Tyriar `#xterm-system` is not hidden, but the container `#xterm-system` is in is hidden.
Additionally I figured out that calling `Terminal.open` won't work if the container or `#xterm-system` is hidden, because `scaledCharWidth` and `scaledCharHeight` are both `undefined`...

**Comment by Tyriar** [comment]
I made a note in the API documentation and type declarations that the parent needs to be visible when calling open https://github.com/xtermjs/xtermjs.org/pull/33 https://github.com/sourcelair/xterm.js/pull/1094

**Comment by martin31821** [comment]
I think that triggering this exception shouldn't be possible, I tracked it down to https://github.com/sourcelair/xterm.js/blob/v3/src/renderer/BaseRenderLayer.ts#L18.
The variables are only declared and never initialized, causing the check in https://github.com/sourcelair/xterm.js/blob/v3/src/renderer/BaseRenderLayer.ts#L63 to pass 
and try to create a canvas of zero size. 

Initializing the values I mentioned to zero should fix the exception, although not the problem itself.

**Comment by Tyriar** [comment]
Good catch, I'll add the initialization to prevent the hard fail :+1:
