### ISSUE TITLE
Option to copy on selection

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#1092]
It's common on macOS for terminal emulators to provide an option to copy the text whenever a selection is made.

**Comment by Tyriar** [comment]
Closing this in favor of https://github.com/sourcelair/xterm.js/issues/1093, this cannot be implemented reliably in the browser so it shouldn't be supported by xterm.js.

**Comment by jayarjo** [comment]
Is it still the case? @Tyriar any elaboration on why this cannot be implemented reliably?
