### ISSUE TITLE
can i connect a server remotely

### ISSUE THREAD

**Issue by smalltimoo** [sourcelair/xterm.js#1098]
Can i install it on a server and connect from this server to another server "remote"? When the interface is automatically log on, the user name, password and ip are provided in the code
## Details
- Browser and browser version:  latest
- OS version:  windows
- xterm.js version: latest

### Steps to reproduce

1. 
2.

**Comment by Tyriar** [comment]
The demo gives an example of how to do this, app.js is a server https://github.com/sourcelair/xterm.js/tree/v3/demo
