### ISSUE TITLE
Support custom keybindings

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#118]
Raised from a discussion in https://github.com/sourcelair/xterm.js/pull/107, I would like to eventually let vscode users to be able to configure keybindings for:

- Copy and paste (https://github.com/Microsoft/vscode/issues/6451, this one's particularly urgent)
- Clear terminal (⌘K on OS X https://github.com/Microsoft/vscode/issues/7240, general command request https://github.com/Microsoft/vscode/issues/6603)

What I'm thinking is allowing consumers of xterm.js to be able to plug key -> escape sequence mappings into `evaluateKeyEscapeSequence`. This could return the same result interface if there is a match otherwise `undefined`.

**Comment by parisk** [comment]
I was thinking that an interesting solution would be offloading the copy/paste functionality to an addon, so as to be able to apply any functionality programmatically on top of the core terminal.

**Comment by Tyriar** [comment]
@parisk exposing some API like `Terminal.prototype.registerKeyMappings(event)` would be good, then that can be used by both addons for common customizations like copy and paste and also lets consumers do whatever they want with it.
