### ISSUE TITLE
Blur and focus behavior is messy and inconsistent

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#120]
There are some issues that need investigating:

- `Terminal.prototype.blur` isn't being run anymore
  - This means that when `this.sendFocus` is `true`, it will send `'\x1b[I'` on focus, but not `'\x1b[O'` on blur
- `Terminal.focus` is always `null` and not maintained, so even if `Terminal.prototype.blur` were hit, it would do nothing

Related: https://github.com/sourcelair/xterm.js/commit/6bc1881727ea3b44436495f05c9033528057aa76 & https://github.com/sourcelair/xterm.js/issues/119

**Comment by parisk** [comment]
Working on this right now. Implementation is more cumbersome than initially thought.

**Comment by parisk** [comment]
Posting an update here on what is most probably going wrong and why this is not trivial to implement. It seems that when the terminal refreshes, there are chances that it removes the whole thing and redraws everything. This leads to a huge load of native `focus` and `blur` events, which make it difficult to tackle.

My first attempt to fix this is attached to https://github.com/sourcelair/xterm.js/commit/2e8f43311fd0440c5f93f57aa2caf54aeffba92d, but still needs a lot of work.

## References
- DOM element removal: https://github.com/sourcelair/xterm.js/commit/2e8f43311fd0440c5f93f57aa2caf54aeffba92d#diff-d4f745d6f29faa0617f2e02bb95f0c44R1220
- DOM element re-focus: https://github.com/sourcelair/xterm.js/commit/2e8f43311fd0440c5f93f57aa2caf54aeffba92d#diff-d4f745d6f29faa0617f2e02bb95f0c44R1371

**Comment by Tyriar** [comment]
@parisk the pass of focus/blur are due to #132 right?
