### ISSUE TITLE
Terminal doesn't accept input via IME

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#124]
Using Ubuntu 16.04 native Korean IME the terminal just enters the English characters.

**Comment by Tyriar** [comment]
I think this is the case because of the removal of the textarea. This might be useful https://developer.mozilla.org/en-US/docs/Mozilla/IME_handling_guide

**Comment by Tyriar** [comment]
@parisk please comment when you get a chance, I'm not sure IMEs will work without the `<textarea>`.

**Comment by parisk** [comment]
Is there any way to detect *when* the Korean IME gets enabled? We could lease the contentEditable attribute.

**Comment by Tyriar** [comment]
@parisk it would probably work with contenteditable, however it would probably need to be on constantly. Note that this will probably happen with all IMEs, so many languages won't be able to be input by conventional means right now.

**Comment by Tyriar** [comment]
Another option if we really don't want to go back to the textarea is to provide some command that would popup and allow input into a regular `<input>` for IMEs. Not ideal though.
