### ISSUE TITLE
Installing and using addons through NPM?

### ISSUE THREAD

**Issue by themrwilliams** [sourcelair/xterm.js#135]
I've been toying with various uses of import/require (e.g., in a React app) for a while now and can't seem to get Xterm's addons to properly register when using Xterm via NPM.  Is this possible without making modifications to the source code and/or adding package files for each addon?

One example:

``` javascript
import Xterm from 'xterm';

// Either require('xterm/addons/attach/attach.js') or import {attach, detach} from 'xterm/addons/attach/attach';

var term = new Xterm();
// ...
term.attach(foo);

// Results in: Cannot read property 'prototype' of undefined from Xterm.prototype.attach()
```

I'd like to avoid using script tags to import everything if possible.  Apologies in advance if I'm overlooking the obvious.

**Comment by parisk** [comment]
Hi @themrwilliams, could you please try running the following and let me know if it worked for you?

```javascript
import Xterm from 'xterm';

var term = new Xterm();
// Create socket as well

term.loadAddon('attach');

term.attach(socket);
```

[documentation](https://github.com/sourcelair/xterm.js/blob/master/src/xterm.js#L782)

**Comment by themrwilliams** [comment]
@parisk 

```javascript
import Xterm from 'xterm';

export class SomeComponent extends Component {
    someFunction(container) {
        var term = new Xterm();
        term.loadAddon('attach');
    }
}
```

Results in:
browserified_file.js:1946 Uncaught (in promise) TypeError: term.loadAddon is not a function(…)

I verified that the version (09d67a6) of Xterm.js I'm using has the loadAddon function.

In the mean time, the following works, but it's pretty hacky:
```javascript
const Xterm = require('xterm/src/xterm.js');
window.Xterm = Xterm;
require('xterm/addons/attach/attach.js');
```

**Comment by Tyriar** [comment]
A new version will need to be published before `loadAddon` is available.
