### ISSUE TITLE
Lines containing unicode characters differ in height

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#149]
Using the demo, lines with CJK characters at 24px, regular lines are 18px, and my prompt character is 20px.

![image](https://cloud.githubusercontent.com/assets/2193314/16393767/e56a18d0-3c66-11e6-8fd0-d9f994726392.png)

This is the reason that on my computer the size of the terminal increases every time I press enter; because the `❯` character is being added, pushing out the height of the line.

**Comment by parisk** [comment]
@Tyriar are you aware of any way we can fix this? Could we somehow (based on font-size I guess) know what is the appropriate line height to set, in order not to have lines with variant line heights?

**Comment by Tyriar** [comment]
The way I'm probably going to approach a fit for vscode at least which allows a configurable `font-size` and `line-height`, is to make the default `line-height` a fixed pixel size and set it as the `height` as well. Setting `height` and `line-height` forces all chars to be aligned the same and all lines to be the same height.
