### ISSUE TITLE
Allow consumers to specify a set of key sequences to not be handled by the terminal and bubble up instead

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#152]
See https://github.com/Microsoft/vscode/issues/7269 for context.

Some users want <kbd>F1</kbd> to not be consumed by the temrinal and instead be bubbled up to be handled by the application (to toggle the command palette). I can see this being useful for other keys as well depending on specific the use case.

**Comment by parisk** [comment]
Sounds like a sane proposal. We could create a more declarative key binding API and export all current key handling to add-on like objects.

**Comment by parisk** [comment]
This way you will be able to choose which of them to include in your "xterm bundle".

**Comment by TDaglis** [comment]
As an alternative (or as a temporary) solution, the application could catch the key sequences on capturing instead of bubbling.

**Comment by protasenko** [comment]
This is already pretty easy to achieve with very small modifications. The existing "keydown" event should be emitted with additional parameter "result". And it's emit call should be moved up before `if (result.cancel)` and `if (!result.key)` blocks. Then the "keydown" handler could inspect `event.keyCode` and `result.key` and e.g. set `result.key = ""` to ignore key and let it bubble, or also set `result.cancel = true` to prevent bubble as well. It could even override `result.key` with a different escape sequence if required. The websocket sending code would still reside in the catch-all "data" handler...

**Comment by Tyriar** [comment]
This duplicates https://github.com/sourcelair/xterm.js/issues/118
