### ISSUE TITLE
reverse-i-search incorrectly overwrites characters

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#162]
Steps to reproduce:

1. Type `npm install` and interrupt the process using <kbd>ctrl</kbd>+<kbd>c</kbd> to add it to history
2. <kbd>ctrl</kbd>+<kbd>r</kbd>
3. Type `npm inst`

gnome-terminal:

![image](https://cloud.githubusercontent.com/assets/2193314/16595745/9ba1e314-42a5-11e6-98a3-550e5acec1ab.png)

xterm.js:

![image](https://cloud.githubusercontent.com/assets/2193314/16595769/b19a9508-42a5-11e6-84c9-c67cd7f96aed.png)

Note that the cursor seems to be in the correct position but the characters aren't.

**Comment by jerch** [comment]
This got also fixed by #163.

**Comment by Tyriar** [comment]
@jerch nice :smiley:
