### ISSUE TITLE
Problems in search & highlight

### ISSUE THREAD

**Issue by jerch** [sourcelair/xterm.js#1680]
Entering this line with lots of spaces in the demo:

```
echo -e '                                          http://example.com      http://example.com'
```

pressing <kbd>enter</kbd> and searching for `http` shows two bugs:

1. the first result gets highlighted in the line above - imho related to some trimming of white spaces from right (maybe the empty vs. space cell problem? see https://github.com/xtermjs/xterm.js/issues/791#issuecomment-403284022)
2. the second possible match in every line gets never highlighted

Problem one is new in master, problem two is also in 3.7. Have not tested older releases.

**Comment by Tyriar** [comment]
Problem 2 is captured in https://github.com/xtermjs/xterm.js/issues/1654

**Comment by Tyriar** [comment]
@jerch great find btw 😄

**Comment by Tyriar** [comment]
@alexr00 can pick this one up 🙂
