### ISSUE TITLE
Cannot enter # on Mac UK keyboard

### ISSUE THREAD

**Issue by BenHall** [sourcelair/xterm.js#169]
I had to patch term.js previously to get # working on a Mac UK keyboard (shift + 3).

https://github.com/BenHall/term.js/commit/edf03f4656bd7eb5df1151dcfb1ba1a1d19287b0

I tried to do the same patch xterm but it didn't work. I added the following code at line 2568

https://github.com/sourcelair/xterm.js/blob/39edbfb6558343dc556b094470a84448d6a7a4d2/src/xterm.js#L2568

```
        case 51:
          result.key = "#";
          break;
```

Please help, it's stopping our migration.

Thank you

Ben

**Comment by akalipetis** [comment]
Hello @BenHall - thanks for reporting.

I tried reproducing the issue described but couldn't. I am on OSX/Chrome.

Could you please let me know if this issue is present here? https://7cyoxu8p.apps.lair.io/ 
This is a simple Xterm.js demo on master.

I also checked and when Shift + 3 is pressed the correct keycode/key combination is sent over.

**Comment by BenHall** [comment]
Here is a quick gif of the above environment (sorry for the typos). I tried different key combinations but couldn't get a hash to appear.

![hashbug](https://cloud.githubusercontent.com/assets/82614/16708692/328ec5ca-45f4-11e6-9daf-5e165feb3edb.gif)

this is the window event output when I set a breakpoint on keypress:

```
KeyboardEvent {isTrusted: true, location: 0, ctrlKey: false, shiftKey: false, altKey: true…}
altKey
:
true
bubbles
:
true
cancelBubble
:
false
cancelable
:
true
charCode
:
35
code
:
"Digit3"
ctrlKey
:
false
currentTarget
:
div.terminal.xterm.xterm-theme-default
defaultPrevented
:
false
detail
:
0
eventPhase
:
2
isTrusted
:
true
isTrusted
:
true
key
:
"#"
keyCode
:
35
keyIdentifier
:
"U+0033"
location
:
0
metaKey
:
false
path
:
Array[8]
repeat
:
false
returnValue
:
true
shiftKey
:
false
sourceCapabilities
:
InputDeviceCapabilities
srcElement
:
div.terminal.xterm.xterm-theme-default
target
:
div.terminal.xterm.xterm-theme-default
timeStamp
:
106452.09000000001
type
:
"keypress"
view
:
Window
which
:
35
```

**Comment by parisk** [comment]
@BenHall could you please try this with another browser as well, preferably using incognito (add-on/plugin free) mode?

Also could you please log the keydown and keypress events when pressing `#` and provide the output here?

**Comment by BenHall** [comment]
It's very hard to get the keydown for the # without changing the code. Here is the first snippet which is for the "Right Alt" on the keyboard. To get a #, it's Right Alt + 3.

Atom had same issue - https://github.com/atom/atom-keymap/issues/35


```
KeyboardEvent {isTrusted: true, location: 2, ctrlKey: false, shiftKey: false, altKey: true…}
altKey
:
true
bubbles
:
true
cancelBubble
:
false
cancelable
:
true
charCode
:
0
code
:
"AltRight"
ctrlKey
:
false
currentTarget
:
div.terminal.xterm.xterm-theme-default
defaultPrevented
:
false
detail
:
0
eventPhase
:
2
isTrusted
:
true
isTrusted
:
true
key
:
"Alt"
keyCode
:
18
keyIdentifier
:
"Alt"
location
:
2
metaKey
:
false
path
:
Array[6]
repeat
:
false
returnValue
:
true
shiftKey
:
false
sourceCapabilities
:
InputDeviceCapabilities
srcElement
:
div.terminal.xterm.xterm-theme-default
target
:
div.terminal.xterm.xterm-theme-default
timeStamp
:
116638.41500000001
type
:
"keydown"
view
:
Window
which
:
18
__proto__
:
KeyboardEvent

```

**Comment by parisk** [comment]
Hi Ben, could you please checkout the `issue/169` branch (#178) and try it out? This should fix your issue.

**Comment by BenHall** [comment]
Just had a very quick test but looks good to me.

**Comment by parisk** [comment]
Thanks!
