### ISSUE TITLE
Disable detach

### ISSUE THREAD

**Issue by BenHall** [sourcelair/xterm.js#170]
Is it possible to disable Ctrl+D so a user can never detach from the terminal?

**Comment by TDaglis** [comment]
https://github.com/sourcelair/xterm.js/issues/152 would solve your issue. Until it is implemented though, you could catch the keydown event in your application on the capturing phase, and prevent its propagation when it is <kbd>Ctrl-D</kbd>

**Comment by parisk** [comment]
@BenHall did @TDaglis' proposal solve your case? Are you OK with closing this issue now?

**Comment by Tyriar** [comment]
https://github.com/sourcelair/xterm.js/issues/118 fixes this
