### ISSUE TITLE
The current input will be delayed to next input

### ISSUE THREAD

**Issue by bobinshen** [sourcelair/xterm.js#1715]
Hi there,

I am trying to embed the xterm.js into a vue.js frontend framework. But there is a problem that the response of one input will be delayed to next keyboard entry. Does some have any idea, thanks in advance.

**Comment by Tyriar** [comment]
Can you elaborate a little on the problem? Are you saying you type "ls" and only "l" is printed? This is probably a problem with your backend if so.

**Comment by bobinshen** [comment]
Yes, you are right, it was caused by backend indeed. Thanks Tyriar.
