### ISSUE TITLE
Expose clear function

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#173]
To allow external code to clear the terminal, for example in order to implement a button or ⌘K keybinding to clear the terminal (#118), a clear function should be exposed. This is not as simple as calling `eraseInDisplay([2])`

This clear function should:

- Clear the display above the line the cursor is on
- Scroll the viewport such that the cursor line is at the top

Since it's difficult/impossible to determine whether your prompt spans multiple lines (like my own), I suggest we do what iTerm does on OS X which is to clear all lines except the one the cursor is on.

Related: https://github.com/Microsoft/vscode/issues/6603

**Comment by jerch** [comment]
Additionally to this idea IMHO the hard `reset` should be exposed since there are programs that tend to leave the terminal unusable. With a hard reset button it would be easy to recycle the terminal without quitting and reopen it. To fully implement `reset` on terminal side `termios` support is needed. Is that exposed by pty.js?

**Comment by rohangulati** [comment]
I think this option is already available on bash with `Ctrl+l` shortcut and works with xterms.js.

**Comment by Tyriar** [comment]
@rohangulati I want a function available externally so I can setup a ⌘K keybinding for Mac and allow users to customize it.

**Comment by rohangulati** [comment]
@Tyriar : Can build a wrapper function to capture the clear keyboard event and internally delegate clearing to `bash`?  Additionally, can we expose a functionality to allow users to customise all `bash` shortcuts

**Comment by Tyriar** [comment]
Soe are just how bash reacts to key sequences which shouldn't be changed. Anything custom though should be able to get custom handled via https://github.com/sourcelair/xterm.js/pull/186 after it lands.
