### ISSUE TITLE
Regression: Page up breaks cursor in vim

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#176]
Some time between 8790a94 (what vscode 1.3.0 shipped) and 5b44e36317f875f3e30f95ad32e108cff104208e (latest) this bug has been introduced. Running vim on a large diff, scrolling down and up using page up/down breaks the cursor line.

In this screenshot the : should be on the last line:

![image](https://cloud.githubusercontent.com/assets/2193314/16789837/a3b1faba-4865-11e6-9470-9f710e95893c.png)

**Comment by jerch** [comment]
Hmm I think I didnt touch xterm.js with the PR.

**Comment by Tyriar** [comment]
It doesn't repro for me in vscode at that commit anyway, perhaps it's a problem with the demo or something?

**Comment by parisk** [comment]
Just tried this with the latest version of master (13644ce35190e5bb5119e322f5f5f169ab7a1aa9) and could not reproduce.

**Comment by jerch** [comment]
Just stumbled over this as well in the demo. It might be related to the missing resizing of the underlying pty (#171). 
Behavior: vim fills up all rows down to the bottom when moving the cursor downwards. As soon as you move upwards the ":" cursor jumps to line 25 which is the bottom line of the pty leaving stuff below messed up.

**Comment by Tyriar** [comment]
Pretty sure this is fixed.
