### ISSUE TITLE
newbie question - please help

### ISSUE THREAD

**Issue by adminIBMiOSS** [sourcelair/xterm.js#182]
Good afternoon,

Hope you can point me in the right direction - I don’t want to develop with xterm.js, I simply want to use it as a node app locally.

I’m trying to fire up your xterm.js using npm/node on my mac.  I’m not very confident of all this; and I’m not getting it to work as expected.  I believe I have it installed but when I try to start it, I get errors like this:

Bills-MacBook-Pro:~ bg$ npm start

> xterm@0.33.0 start /Users/bg
> node demo/app

module.js:327
    throw err;
    ^

Error: Cannot find module '/Users/bg/demo/app'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! xterm@0.33.0 start: `node demo/app`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xterm@0.33.0 start script 'node demo/app'.
npm ERR! This is most likely a problem with the xterm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node demo/app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs xterm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls xterm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bg/npm-debug.log
Bills-MacBook-Pro:~ bg$ node demo/app
module.js:327
    throw err;
    ^

Error: Cannot find module '/Users/bg/demo/app'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
Bills-MacBook-Pro:~ bg$

**Comment by Tyriar** [comment]
Can you try with latest and do a fresh clone/install to see if it still occurs? Also what version of node are you running with?

**Comment by adminIBMiOSS** [comment]
Thanks - I tried again with v1.0.0 and had some problems.  I had to do a separate npm install of express, express-ws, pty.js and node-gyp.  My version of node is 4.4.5

It now looks like it is working - cheers!

**Comment by parisk** [comment]
Node 4 is the preferred version to work, since it's the current LTS version.

👍  that it worked out eventually.
