### ISSUE TITLE
Copy & paste

### ISSUE THREAD

**Issue by PhilippeAssis** [sourcelair/xterm.js#185]
To paste is CTRL + SHIFT + V Ok.
But how to copy ?!

**Comment by Tyriar** [comment]
Only <kbd>ctrl</kbd>+<kbd>ins</kbd> copies text currently.

This is a duplicate of https://github.com/sourcelair/xterm.js/issues/118

**Comment by mquinson** [comment]
For the record, Shift + Ins can be used to paste text.
