### ISSUE TITLE
ctrl+left/right doesn't work correctly in vim

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#193]
ctrl+left doesn't jump over words and ctrl+right erases everything to the right of the cursor

## Details
- Browser and browser version: Chrome 51
- OS version: Ubuntu 16.04
- xterm.js version: https://github.com/sourcelair/xterm.js/commit/dc17f0d02e65f06a67ea80236aee17575e501a36

### Steps to reproduce

1. Type the following:
  ```
  vim
  i
  abc
  ```

  ![image](https://cloud.githubusercontent.com/assets/2193314/16959016/e1117872-4d97-11e6-9dc0-4e84e603bb67.png)

2. ctrl+left
  ![image](https://cloud.githubusercontent.com/assets/2193314/16958989/c7041dcc-4d97-11e6-85aa-1f6a1efacfcb.png)

3. ctrl+right
  ![image](https://cloud.githubusercontent.com/assets/2193314/16959001/d3461e50-4d97-11e6-8828-7511b5278b32.png)

**Comment by jerch** [comment]
xterm uses a bit map to handle <kbd>shift</kbd>, <kbd>alt</kbd> and <kbd>ctrl</kbd> status. See [here](http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Alt-and-Meta-Keys)...

**Comment by parisk** [comment]
Unfortunately I won't have access to a Linux machine until tomorrow to try this out and <kbd>Ctrl</kbd> + <kbd>←</kbd>/<kbd>→</kbd> won't work here as they are used by host.

It would help if you could provide us with the code sent by xterm.js when hitting <kbd>Ctrl</kbd> + <kbd>←</kbd> in plain bash, compared with the code in Vim (which should have `applicationKeypad` set to true).

**Comment by jerch** [comment]
The modifier state will be added to the escape sequence as the second parameter (right before the final character) like this:
<kbd>←</kbd> --> CSI D (normal mode with bash) or SS3 D (application mode with vim)
<kbd>Ctrl</kbd>+<kbd>←</kbd>--> CSI 1;5 D
<kbd>Shift</kbd>+<kbd>←</kbd>--> CSI 1;2 D
There is no normal/application mode distinction with a pressed modifier key, they are all sent with CSI. The '1' is there to indicate the other number as second parameter. No clue if it has any other meaning.
Btw the modifier keys are respected for all the keys listed above by xterm.

Modifier states
```
  Code     Modifiers
---------+---------------------------
   2     | Shift
   3     | Alt
   4     | Shift + Alt
   5     | Control
   6     | Shift + Control
   7     | Alt + Control
   8     | Shift + Alt + Control
   9     | Meta
   10    | Meta + Shift
   11    | Meta + Alt
   12    | Meta + Alt + Shift
   13    | Meta + Ctrl
   14    | Meta + Ctrl + Shift
   15    | Meta + Ctrl + Alt
   16    | Meta + Ctrl + Alt + Shift
---------+---------------------------
```

When I get my hand on a linux machine I can create you a complete list of the sequences.

**Comment by jerch** [comment]
These are the arrow key sequences (xterm treats <kbd>home</kbd> and <kbd>end</kbd> as arrow keys):

```
// normal mode
ARROWS = {
    'left': '\x1b[D',
    'right': '\x1b[C',
    'up': '\x1b[A',
    'down': '\x1b[B',
    'home': '\x1b[H',
    'end': '\x1b[F',
    'page up': '\x1b[5~',
    'page down': '\x1b[6~'
}
// application mode
ARROWS_CKM = {
    'left': '\x1bOD',
    'right': '\x1bOC',
    'up': '\x1bOA',
    'down': '\x1bOB',
    'home': '\x1bOH',
    'end': '\x1bOF',
    'page up': '\x1b[5~',
    'page down': '\x1b[6~'
}

// replace %s with the modifier state
ARROWS_MOD = {
    'left': '\x1b[1;%sD',
    'right': '\x1b[1;%sC',
    'up': '\x1b[1;%sA',
    'down': '\x1b[1;%sB',
    'home': '\x1b[1;%sH',
    'end': '\x1b[1;%sF',
    'page up': '\x1b[5;%s~',
    'page down': '\x1b[6;%s~'
}
```
