### ISSUE TITLE
Proposal: Change name to xtermjs without the .

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#195]
The presence of the `.` introduces some issues:

- No `.`'s in GitHub organization names https://github.com/xtermjs
- No `.`'s in web pages, as we can't own xterm.js.org (js.org)
- Referring to the module in JavaScript/TypeScript etc must be done in quotes

**Comment by parisk** [comment]
I think that if xterm.js is importable as `xterm` (which is the case if it is being installed through npm; https://npmjs.org/xterm) we will have no further issues with it.

Also, this way it will behave exactly like React.js

> No .'s in GitHub organization names https://github.com/xtermjs

https://github.com/reactjs

> No .'s in web pages, as we can't own xterm.js.org (js.org)

We own xtermjs.org (as React owns reactjs.org which redirects to its GitHub page)

> Referring to the module in JavaScript/TypeScript etc must be done in quotes

Referring to it as plain `xterm` should solve the issue as well.

**Comment by Tyriar** [comment]
Closing, it's good as is
