### ISSUE TITLE
It would be cool if xterm.js described its mission or distinguishing features

### ISSUE THREAD

**Issue by vincentwoo** [sourcelair/xterm.js#198]
There's beginning to be a bunch of JS terminal emulators in active development and use, in addition to this one. Notably, 

* [Hyperterm](https://hyperterm.org/) with [hterm](https://chromium.googlesource.com/apps/libapps/+/master/hterm) underneath. I don't know too much about hterm.
* [term.js](https://github.com/chjj/term.js/), which xterm.js is based on.
* [terminal.js](https://github.com/Gottox/terminal.js), which tries to support several renderers.

As a user, it can be hard to know which one to pick. I think it would be great if the Readme included a statement concerning:

* What use cases xterm.js focuses on
* What limitations xterm.js has at this time
* What important things are planned for the future
* How xterm.js differs from other libraries, either in implementation or philosophy

What do you think?

**Comment by Tyriar** [comment]
I agree, it would be good to have some more detail in the README. Here are some of my thoughts on the topic, in no particular order:

- xterm.js succeeds term.js, pushing it forward as the original author no longer has the time to maintain term.js
- The current use case being focused on is editor integration as the two main products integrating it are VS Code and SourceLair
- To be clear: hterm is comparable to xterm.js, Hyperterm is not.
- IME support will be a big stand out feature once it lands #175, I know hterm doesn't handle this, not sure about terminal.js
- Currently while performance is not perfect by any means (#134, #150), xterm.js seems to perform significantly better than hterm when processing large amounts of data.
- Some areas for improvement are general compatibility with xterm and test coverage https://github.com/sourcelair/xterm.js/issues/194 #156

**Comment by parisk** [comment]
This is a great idea @vincentwoo, thanks for proposing! I am putting this into the `1.1.0` milestone, which is set for release approximately one month after the `1.0.0` release.

All of @Tyriar's comments about xterm.js are true. In addition we should mention that xterm.js is a self contained library. This means that it has no external dependencies, thus it is lighter and easier to integrate. While this might change in the future if there are important reasons to do so, we have no such plans right now.

**Comment by vincentwoo** [comment]
Thanks for the responses. Another thing I think could be interesting to say is that xterm might get a lot more eyeballs on it because of its exposure in VS Code. I'm not sure what the relative popularity is like, but it seems like a relevant bit.

**Comment by parisk** [comment]
@vincentwoo could you please take a look at the attached patches at #219? It should clarify things a little bit hopefully 😊 .
