### ISSUE TITLE
Home/End send same sequence in application and normal keypad mode?

### ISSUE THREAD

**Issue by apjanke** [sourcelair/xterm.js#199]
Home and End are sending the application-mode character sequence under both normal and application keypad modes.

## Details

- Browser and browser version: Firefox 47.0
- OS version: OS X 10.10.5
- xterm.js version: Commit dc17f0d02e65f06a67ea80236aee17575e501a36

It looks like the Home and End keys are [coded to send the same character sequence in both normal and application keypad mode](https://github.com/sourcelair/xterm.js/blob/dc17f0d02e65f06a67ea80236aee17575e501a36/src/xterm.js#L2680-L2695).

```
        // home
        case 36:
          if (this.applicationKeypad) {
            result.key = '\x1bOH';
            break;
          }
          result.key = '\x1bOH';
          break;
        // end
        case 35:
          if (this.applicationKeypad) {
            result.key = '\x1bOF';
            break;
          }
          result.key = '\x1bOF';
          break;
```

Home sends `'\x1bOH'` and End sends `'\x1bOF'` in both modes. Those are the application-mode sequences. I think they should send `'\x1b[H'` and `'\x1b[F'` in normal keypad mode.

Looks like they're using the wrong mode, too. I think they should be governed by the cursor keypad mode (`applicationCursor`) and not the numeric keypad mode (`applicationKeypad`).

### Steps to reproduce

I just saw this while looking at the source. I can't actually get xterm.js to run on my machine (Mac OS X 10.10.5).

**Comment by jerch** [comment]
@apjanke Thanks for spotting it. Addressed this in #200.
