### ISSUE TITLE
Right-click paste does not work

### ISSUE THREAD

**Issue by parisk** [sourcelair/xterm.js#202]
Right-click paste does not work. This regression was caused after #175, since we moved input handling to a textarea instead of xterm itself.

## Proposals
This could be solved in the following two ways (additional ideas are always welcome though)

1. Temporarily move the textarea element below the mouse cursor on right click (https://github.com/sourcelair/xterm.js/pull/175#issuecomment-233876524). This would need non-native selection handling though (https://github.com/sourcelair/xterm.js/pull/175#issuecomment-234344851).
2. Temporarily give focus and enable contenteditable on the terminal element to allow pasting without messing with text selection issues.

Out of these two proposals IMO **1.** is the best way to go (it will also fix other bugs like #116), but it will need definitely more work, while **2.** is a quick hack that could do the job for now.

## Details
- Browser and browser version: All browsers
- OS version: All OSes
- xterm.js version: >= 10fbf0dcccdb1f8a9f065029c788ca86fb99fce8

### Steps to reproduce

1. Right click on the terminal
2. Notice that there is no **Paste** option in the right click menu, while it should

**Comment by Tyriar** [comment]
This could be fixed by the solution suggested in https://github.com/sourcelair/xterm.js/issues/273, and maybe resizing the textarea on mousedown or redirecting the event to that element?

**Comment by parisk** [comment]
Wouldn't this break the copy event then, since there will be no selection?

**Comment by Tyriar** [comment]
Yeah needs to be thought through a bit, I know it would work with electron but copying is a bit more restrictive without node apis.
