### ISSUE TITLE
Can i connect a server remotly?

### ISSUE THREAD

**Issue by systemroot** [sourcelair/xterm.js#206]
Can i install this in one server, And from this server to connect to a diferent server "remotly" ?
Not to login automatically, The Person Which Will use will login with username and password.
For example.
![](http://image.prntscr.com/image/64dc028e19ef443eaf85e2e229b8df65.png)

## Details
- Browser and browser version:  Chrome Latest.
- OS version: Ubuntu 14.04 (Main)
- xterm.js version: Latest.

**Comment by akalipetis** [comment]
Hey @systemroot - you can install it in the way you say, but you will need to configure the Node server to have the logic you describe.

For example, you can replace the `bash` command with something like `ssh user@example.com`, where `example.com` is the server you'd like to access. Then, the user should enter her password to gain SSH access to your remote server.

Please make sure you check any possible security and/or vulnerabilities of having such functionality open in the wild first.

**Comment by systemroot** [comment]
@akalipetis  Thank You :+1:
