### ISSUE TITLE
Allow demo terminal to be resized

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#211]
It's difficult to test resize behavior on the demo without resorting to running code in the developer tools.

**Comment by parisk** [comment]
Just to clarify this; this proposal is about making terminal resizeable with drag and drop like functionality, right?

**Comment by Tyriar** [comment]
Either resizing with the window or using a slider/text box to control cols/rows. Just some means to call into `resize` without running the console would be nice.
