### ISSUE TITLE
ctrl+shift+up/down no longer scrolls bash on Linux

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#215]
/cc @jerch (https://github.com/sourcelair/xterm.js/pull/200)

## Details
- Browser and browser version: Chrome v52
- OS version: Ubuntu 16.04
- xterm.js version: 65b2be7

### Steps to reproduce

1. ctrl+shift+up should scroll up 1 line
2. ctrl+shift+up should scroll down 1 line

**Comment by jerch** [comment]
@Tyriar I can add this behavior back to xterm.js - since it is not xterm compatible I'd like ask first if all agree to it.

**Comment by Tyriar** [comment]
@jerch if that's true then maybe it can just be added manually by calling `scrollDisp` inside `attachCustomKeydownHandler`? I want to add some documentation at some point to explain the power of that function.

**Comment by parisk** [comment]
If this behavior is not xterm compatible, I think we should close this issue and leave it up to vendors to implement with custom key bindings.

On OS X (where the terminal claims to be xterm) <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>↑</kbd>/<kbd>↓</kbd> do not scroll bash as well.
