### ISSUE TITLE
Viewport should only scroll down on input, not when the pty writes

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#216]
Similar to `gnome-terminal`, if the user is scrolling up to look at past output and the currently running program adds output to the terminal, the viewport should not scroll and interrupt what they are looking at.
## Details
- Browser and browser version: Chrome 52
- OS version: Ubuntu 16.04
- xterm.js version: d2cef6f29db8e4e47b82000f8415b849a7756728
### Steps to reproduce
1. Run `while [ "true" ]; do echo "ping"; sleep 1; done`
2. Scroll up, notice the viewport is moved to the bottom every second

**Comment by jerch** [comment]
This is maybe another candidate for a customisation setting as it is in xterm.
