### ISSUE TITLE
Integrated Terminal Option+Arrow no longer jumps words

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#225]
_From @bfsmith on August 9, 2016 20:29_
- VSCode Version: 1.4
- OS Version: OSX 10.11.4

Steps to Reproduce:
1. Open Integrated Terminal
2. Use Option/Alt+Left Arrow or Option+Right Arrow

Expected: Cursor moves forward and back words.
Actual: Prints character codes to the terminal line (;3D;3C) for Option+Left, Option+Right

This works as expected in VSCode 1.3.1.

_Copied from original issue: Microsoft/vscode#10365_

**Comment by Tyriar** [comment]
@bfsmith could you try repro this on https://github.com/sourcelair/xterm.js ?

**Comment by Tyriar** [comment]
_From @bfsmith on August 12, 2016 14:21_

It repro's there as well.

**Comment by Tyriar** [comment]
@bfsmith thanks for checking, I'm going to move the issue over there.

**Comment by parisk** [comment]
Shouldn't this be fixed after #240?

**Comment by Tyriar** [comment]
Yeah should be. I created #264 which outlines my new thoughts on this.

**Comment by Tyriar** [comment]
This is not fixed on Mac, `\x1b[1;5D` does not skip words on bash on Mac?

**Comment by parisk** [comment]
Marking this as a bug.

**Comment by akalipetis** [comment]
I believe this is an issue with bash on macOS - I can't reproduce on the demo, from either macOS or Ubuntu.

Local terminal has the same issue as with Xterm.js on VS code.

**Comment by bfsmith** [comment]
I'm seeing the expected behavior using the macOS Terminal app (shown below) and in iTerm2.

![opt-arrows](https://cloud.githubusercontent.com/assets/620524/21230192/c0ad660e-c2a9-11e6-923e-d5fe55117a9e.gif)

**Comment by BobReid** [comment]
I repro'd the issue on the demo app on macOS Sierra 

![image](https://cloud.githubusercontent.com/assets/894331/21248948/a1335856-c308-11e6-833f-857d5acb91d6.png)

**Comment by parisk** [comment]
Closed in #417.

**Comment by max-wittig** [comment]
This seem to be broken again

**Comment by Tyriar** [comment]
Generally it's way better to report new issues and link to old ones rather than send out notifications for 9 year old ones.
