### ISSUE TITLE
Spontaneous line wrap in the middle of shell prompt

### ISSUE THREAD

**Issue by kontsevoy** [sourcelair/xterm.js#227]
This issue has originally been [reported here](https://github.com/gravitational/teleport/issues/496#issuecomment-239423452) for Teleprot project which uses term.js

We have verified that it's not related to anything on the server.

### Details

Sometimes when I'm connected to a server via the WebUI the server prompt starts to jump.
Video:
https://www.youtube.com/watch?v=Tx5EGXDXjUk&feature=youtu.be

Chrome on Chrome OS 
Version 52.0.2743.116 (64-bit)
Platform 8350.68.0 (Official Build) stable-channel gandof
Firmware Google_Gandof.6301.155.9
### Steps to reproduce

Unfortunately we can't figure out how to reproduce it outside of this one laptop. We have tried Asus Chromebox to no avail.

**Comment by Tyriar** [comment]
Can you reproduce on the xterm.js demo? It looks like it's related to the blinking cursor, you may have styles that change `.terminal-cursor` or something?

**Comment by kontsevoy** [comment]
We (Teleport team) so far were unable to reproduce (do not have access to the server&laptop of the person who've reported it). But yes - we're trying and we'll continue trying, including your suggestion. :-) Reporting here just in case you guys have seen this or have suggestions to reproduce.

**Comment by Tyriar** [comment]
Also if you use chjj/term.js and not xterm.js we may not be able to help. The codebase has diverged quite a bit at this point around row/col logic with the introduction of IME support and scroll bars.

**Comment by kontsevoy** [comment]
@Tyriar yep, we're re-vendoring to the latest ASAP. Thanks.

**Comment by Tyriar** [comment]
@kontsevoy are you still experiencing this?

**Comment by kontsevoy** [comment]
@Tyriar nope. seems to be gone. Thanks.

**Comment by Tyriar** [comment]
Awesome :+1:
