### ISSUE TITLE
How to connect to a docker container?

### ISSUE THREAD

**Issue by maslick** [sourcelair/xterm.js#23]
Hey, 

I like the design of xterm.js and would like to use it to connect to a docker container. 
In the documentation I can see that in the client you connect to a docker container using the following uri:
url = 'ws://docker/containers/mycontainer/attach/ws/?stdin=1&stdout=1&stderr=1&logs=1'

As far as I understood there is a server application (e.g., node.js) that's exposing the docker terminal over a socket connection. In the docker documentation I can see that you can connect to a socket container via the docker REST API, so I can do http requests to the docker daemon (http://x.x.x.x:4500/containers/json). But how can I connect to my running container using the socket protocol (ws://x.x.x.x:4500/containers/mycontainer/attach/ws/?stdin=1&stdout=1&stderr=1&logs=1')?

Thanks.

**Comment by parisk** [comment]
Hello,

Yes, you need to expose the Docker API using an external server. This can be done very easily with Nginx. A sample configuration for an nginx host that could do this is the following.

```
server {
    server_name your.domain.name;

    location / {
        proxy_pass http://unix:/var/run/docker.sock;
    }

    location ~ws/?$ {
        proxy_pass http://unix:/var/run/docker.sock;
        proxy_http_version 1.1;
        proxy_set_header Upgrade "websocket";
        proxy_set_header Connection "upgrade";
    }
}
```

Attaching to a Docker container using Websocket is documented in the Docker Remote API as well (https://docs.docker.com/reference/api/docker_remote_api_v1.17/#attach-to-a-container-websocket).

While this issue is not directly related to xterm.js, I will keep it open in order to fill in this example in the documentation to make it even clearer on how you can hook an xterm.js terminal on a Docker container.

**Comment by maslick** [comment]
Hey @parisk, thanks! I get this error in the nginx logs:
```
2015/03/09 10:14:25 [crit] 22778#0: *4 connect() to unix:/var/run/docker.sock failed (13: Permission denied) while connecting to upstream, client: 10.5.2.239, server: localhost, request: "GET /containers/docker/attach/ws/?stdin=1&stdout=1&stderr=1&logs=1 HTTP/1.1", upstream: "http://unix:/var/run/docker.sock:/containers/docker/attach/ws/?stdin=1&stdout=1&stderr=1&logs=1", host: "10.5.2.126"
```

**Comment by maslick** [comment]
Ok, I managed to get the server working by changing the nginx user name (in /etc/nginx/nginx.conf) to root, since /var/run/docker.sock is owned by root. 

When I am trying to connect to it from the client using the code provided in the xterm.js documentation, I neither can type anything, nor receive anything from the server, and I just see an empty terminal.

```
<!doctype html>
<html>
    <head>
        <link rel="stylesheet" href="../../src/xterm.css" />
        <link rel="stylesheet" href="../../demo/style.css" />
        <script src="../../src/xterm.js"></script>
        <script src="linkify.js"></script>
        <style>
            body {
                color: #111;
            }

            #terminal-container {
                max-width: 900px;
                margin: 0 auto;
            }

            #terminal-container a {
				color: #fff;
            }
        </style>
    </head>
    <body>
        <div id="terminal-container"></div>
        <script>
            container = document.getElementById('terminal-container');
            var term = new Terminal(),
                url = 'ws://10.5.2.126/containers/maslick/attach/ws?logs=0&stream=1&stdin=1&stdout=1&stderr=1',
                socket = new WebSocket(url);
            
            term.open(document.getElementById('terminal-container'));            
            term.on('data', function (data) {
                socket.send(data);
            });
            
            socket.onmessage = function (e) {
                term.write(e.data);
            }
        </script>
    </body>
</html>
```

**Comment by parisk** [comment]
The handshake response code indicates that you are not allowed to make this request. My guess is that you should authorize `www-data` to channel the Docker socket (**be careful**: this is extremely dangerous if your http server is publicly exposed).

**Comment by maslick** [comment]
In the end I just used docker-browser-server [1].

[1] https://github.com/maslick/docker-browser-server
