### ISSUE TITLE
Wrong sequence on alt + arrow

### ISSUE THREAD

**Issue by parisk** [sourcelair/xterm.js#239]
Pressing Alt + any arrow prints a character, instead of moving word backwards/forward etc.

**Example**: The terminal sends the `\x1b[1;3D` sequence, instead of `\x1bb` or `\x1b[5D` on <kbd>Alt</kbd> + <kbd>←</kbd> (which seem to do the work).

## Details
- Browser and browser version: Chrome 52 on OS X
- OS version: OS X El Capitan
- xterm.js version: 4c3ccc264c52c3860c796d8ffc8bad2ecd2f6e23

### Steps to reproduce

1. Type a command (e.g. `ls -la`)
2. Hit <kbd>Alt</kbd> + <kbd>←</kbd>
3. **Expected**: Cursor move to `l` (in `la`). **Result**: `D` gets printed.

**Comment by ayapi** [comment]
@parisk 
i think it should implement with `customKeydownHandler` on userland.
the reason why is, we can't use each keymaps properly under 8324b43.
for example, my personal config in Vim is,
<kbd>ctrl+left/right</kbd> back/forward word
<kbd>alt+arrow</kbd> move cursor between splitted windows
however, now, i can't use <kbd>alt+arrow</kbd> for move windows...

**Comment by Tyriar** [comment]
Yeah I agree. It's [pretty easy to hook up a handler](https://github.com/Microsoft/vscode/blob/77e9c0bcc674114eaffd2e51caec2d1fd7fd5e42/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L70) if you want it in Sourcelair. We could even consider allowing multiple handlers and putting this in an addon, or an option?
