### ISSUE TITLE
Scroll stops working after running vim

### ISSUE THREAD

**Issue by rgl** [sourcelair/xterm.js#242]
## Details
- Browser and browser version: Chrome 52.0.2743.116 (64-bit)
- OS version: OSX 10.11.6
- xterm.js version: master (01c20807c255911174289a015ed79a986c25dfae) I guess its 1.1.2.

### Steps to reproduce

1. Make sure there is scrollable content on the terminal (e.g. run `dmesg`).
2. Make sure you can scroll the text using normal mouse wheel scrolling.
3. Start and quit `vim`.
4. Realize you no longer can scroll the text (it can scroll again if you press the `ENTER` key).

**Comment by Tyriar** [comment]
Did you actually repro this in master? Something similar was meant to be fixed in https://github.com/sourcelair/xterm.js/commit/588d3b12e0db560fa58a1238efc878695f8d4f1b

**Comment by rgl** [comment]
Yes, I did (as you can see from the revision I've linked). But that fix seems to be disabling scrolling when in application mode. What I'm reporting is that scrolling is not re-enabled after exiting that mode.

So, maybe this is happening because `isApplicationMode` is being set when entering the application mode, but its not unset when leaving it?

**Comment by Tyriar** [comment]
Put out a PR that I think should fix this.
