### ISSUE TITLE
Publish v1.1.2 to npm

### ISSUE THREAD

**Issue by yuvipanda** [sourcelair/xterm.js#244]
Hello! Awesome work on v1.1.2, looking forward to trying out the IME support :) However, it hasn't been published to npm yet - last version there is 1.0. Do you know if it is maintained as part of the release process, or maintained separately? Would be awesome to have them published as they are tagged!

Thanks for your work!

**Comment by parisk** [comment]
@yuvipanda thanks for reporting this. Some 💩  happened because of a mistake I did during the release.

Version ❗ **[1.1.3](https://www.npmjs.com/package/xterm/1.1.3)**❗ is available at npm now 😊.
