### ISSUE TITLE
Move the addons directory into src

### ISSUE THREAD

**Issue by parisk** [sourcelair/xterm.js#250]
By moving the `addons` directory into `src` users will be able to load addons with relative URLs much more intuitively than using the [`loadAddon`](https://github.com/sourcelair/xterm.js/blob/243ce59806349d12001ab4edb125eeae7df30f19/src/xterm.js#L1073) method.

This could help with #247 and #245.

**Comment by 131** [comment]
I dropped the loadAddon and proposed a new API for loading in #245 , maybe this will be acceptable for you ?

**Comment by Tyriar** [comment]
Done
