### ISSUE TITLE
Strange column behavior in bash

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#259]
@rebornix was able to reproduce this strange behavior:

![image](https://cloud.githubusercontent.com/assets/2193314/18148497/c613893e-6f8e-11e6-8fa9-04e3a99a5ea5.png)
## Details
- Browser and browser version: Within vscode v1.5.0 Insiders
- OS version: OSX
- xterm.js version: 220828f
### Steps to reproduce
1. Run `ls`

Notice the 4th column (`Pictures`) is being pushed way out to the right. Inspecting the element shows many `&nbsp;` characters before the `P` on the first line. Running this command on iterm showed the 4 columns correctly spaces.

**Comment by akalipetis** [comment]
Hey @Tyriar, I tried to reproduce but couldn't on VSCode 1.4.0 (same specs as the one reported).

Is there a way to get the 1.5.0 Insiders to test there as well?

**Comment by Tyriar** [comment]
You can grab the Insiders build at http://code.visualstudio.com/insiders

**Comment by akalipetis** [comment]
Thanks @Tyriar - I can confirm this happens but after changing the terminal height, this stops happening. I guess that's an initialization issue in VSCode and not an Xterm.js issue. Could you please check?

**Comment by Tyriar** [comment]
@akalipetis I inspected it the DOM and it seems like way too many `&nbsp;`'s are being created which make the awkward column sizes. Regardless of terminal dimensions, should the columns be spaced evenly?

**Comment by akalipetis** [comment]
Yes, they should be spaced evenly. They should take this from the initial geometry, which might be problematic in such case. Could you please try doing a `xterm.fit()` after the terminal is initialized? This should fix the issue.

**Comment by parisk** [comment]
@Tyriar did you give a try to `fit` after terminal initialization? Does this fix the issue?

**Comment by Tyriar** [comment]
I haven't had time to look at this, we don't use the fit addon to do this though, this is what vscode does https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L306

**Comment by Tyriar** [comment]
I don't think this is important enough to mark v2, will leave it open until I can verify it's status with @rebornix

**Comment by dzy321** [comment]
![image](https://cloud.githubusercontent.com/assets/14145866/19230613/12b4adca-8f08-11e6-8caa-b12510cc09c2.png)
i have the same behavior

**Comment by Tyriar** [comment]
@dzy321 yeah that's exactly what I've been seeing, I've seen it since again. It seems difficult to reproduce, also I'm not sure I've repro'd it on anything other than a Mac. What OS are you on?

**Comment by dzy321** [comment]
@Tyriar I use mac,chrome 53.0.2785.116.
i also use vscode 1.5.2,it has same issue
![image](https://cloud.githubusercontent.com/assets/14145866/19255643/b123b8ae-8f92-11e6-8751-dd1a8ce559d6.png)

**Comment by parisk** [comment]
This does not happen to me neither on the demo using the latest version of master.

Could you please try the demo as well and let us know if this is still an issue there?

**Comment by Tyriar** [comment]
I can still repro:

VS Code:

<img width="1192" alt="screen shot 2017-01-17 at 11 04 37 am" src="https://cloud.githubusercontent.com/assets/2193314/22035448/e65cfa3a-dca4-11e6-9fab-3dade9b41089.png">

Demo (Mac, 120 columns):

<img width="1217" alt="screen shot 2017-01-17 at 11 06 10 am" src="https://cloud.githubusercontent.com/assets/2193314/22035493/045b8b28-dca5-11e6-9917-d772b405859d.png">

**Comment by Tyriar** [comment]
Here is what is sent from the pty process:

```
"AUTHORS			Procfile.dev		demo			lib			tsconfig.json
CONTRIBUTING.md		README.md		dist			node_modules		tslint.json
Dockerfile		bin			docker-compose.yaml	out			typings.json
LICENSE			bower.json		gulpfile.js		package.json
"
```

Looks like this could be related to tab stops not working correctly?

**Comment by Tyriar** [comment]
I think it's happening due to crazy `nextStop` logic. I added an impl of what I would expect it to be and it works just fine, I need to read up on spec though to see if this is correct.

<img width="1217" alt="screen shot 2017-01-20 at 2 11 20 pm" src="https://cloud.githubusercontent.com/assets/2193314/22167295/5a26f4d0-df1a-11e6-9986-063fb46e9c7a.png">

**Comment by Tyriar** [comment]
Oh, it breaks because `setupStops` is not called in the right spot during a `resize`.
