### ISSUE TITLE
Allow xterm.js to exist and receive/send data before it's attached to the DOM

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#266]
In v1.6 of VS Code the newly introduced Terminal API will allow processes to exist before the actual terminal panel/element is created. While this is currently possible, xterm cannot be initialized until the element exists, which means the output before the element is attached is lost. It would be good if everything was functional only no rendering took place until `open` is invoked.

**Comment by parisk** [comment]
Sounds legit. Would it make sense to export the renderer into its own module for this?

**Comment by Tyriar** [comment]
Ideally, not sure how difficult that is right now
