### ISSUE TITLE
Linkify addon breaks the terminal when typing anything that gets linkified

### ISSUE THREAD

**Issue by TDaglis** [sourcelair/xterm.js#27]
Before:
![image](https://cloud.githubusercontent.com/assets/3427236/7387177/c5df7886-ee63-11e4-8fb3-a6cc7a676c64.png)

After:
![image](https://cloud.githubusercontent.com/assets/3427236/7387179/cda737e8-ee63-11e4-9d41-eb092d9ee021.png)

After ++:
![image](https://cloud.githubusercontent.com/assets/3427236/7387186/e25dcd0a-ee63-11e4-8998-c0acfd3beee6.png)
The situation gets worse with every keystroke.

This problem occurs only when you type the url. If it appears in another way it is properly likified
This is especially annoying since typing for any reason a file name breaks the terminal (#26)

**Comment by Tyriar** [comment]
Closing in favor of #455
