### ISSUE TITLE
SIGINT signal

### ISSUE THREAD

**Issue by TaiAivaras** [sourcelair/xterm.js#281]
Hello,

Sorry if this is a stupid question, but how would i go about sending SIGINT signal to a terminal instance programmatically?

Thanks

**Comment by jerch** [comment]
I guess you want to send SIGINT to the slave foreground program. For unaltered default termios settings sending Ctrl-C does the trick which is `term.send('\x03')` (see [termios settings](https://linux.die.net/man/3/termios) and [control codes](https://en.wikipedia.org/wiki/C0_and_C1_control_codes)).

**Comment by TaiAivaras** [comment]
Thanks, that worked nicely. I was also having another unrelated issue, maybe you have an idea? When using demo app from this repo, after some time of terminal being open - terminal seems to automatically detach and close the session.  Any idea what's the cause of this? How could i avoid it?

**Comment by jerch** [comment]
Do you access the demo locally or from a browser on a different machine? No clue what could cause this, I've never seen that with the demo app (tested only locally). Even after hours of sitting unused it is still working. Do the logs (server and browser) give any hints? My only guess is a faulty network link (Any drops? Switching IPs?) between browser and server part, if you do it remotely.

**Comment by TaiAivaras** [comment]
Yea, i'm accessing it from remote machine, with nginx IPv6 reverse proxy. From what i can see in the logs - it's a clean exit on the serverside, websocket closing on the clientside.

**Comment by jerch** [comment]
How far do you get with your setup, is the websocket upgraded correctly? (You should get at least some prompt output and be able to type something.) Maybe try changing the `proxy_read_timeout`?

**Comment by TaiAivaras** [comment]
I got the terminal working all the way - eveything is fully functional, just having this issue. After ~10 min of being open terminals detach. In this case i had 2 xterm terminal instances open and both websockets emit close event: 
![image](https://cloud.githubusercontent.com/assets/10296742/18669614/7d03b73a-7f44-11e6-901d-6e512e315a61.png)

i'll try and play around with config settings.

**Comment by rubenanapu** [comment]
I'm having the same problem and exactly with NGINX Proxy.

I've seen that you closed the issue, but how did you solve the problem, @TaiAivaras?

**Comment by TaiAivaras** [comment]
Hey, it's been a while - but if i remember correctly i  set up something like a heartbeat process - to push empty messages to the websocket, thus keeping it alive. Not sure it's the perfect solution tho.

**Comment by rubenanapu** [comment]
I see that my connections are closed after ~1 minute of inactivity.

I'll do the same as you: send empty messages every ~30 seconds just to keep it alive.

Thanks @TaiAivaras !

**Comment by rubenanapu** [comment]
Even if the heart beat worked, I tried to find a solution that attacks directly the source of the problem (nginx).

I finally [found it](http://blog.carbocation.com/post/51529889500/how-to-fix-nginx-websockets-that-disconnect-after). In case if the link get broken, the solution was to use [proxy_read_timeout](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout), like in the example below that sets the timeout for 7 days:

```
server {
    location /chat/ {
        proxy_read_timeout 604800;
    }
}
```

**Comment by Kaijun** [comment]
@TaiAivaras @rubenanapu "empty messages" means `""` or some special character?
