### ISSUE TITLE
Paste programatically

### ISSUE THREAD

**Issue by TaiAivaras** [sourcelair/xterm.js#284]
Hey,
 
Got one more question, i can paste into terminal using [Shift-Insert], but how would i go about executing this command programatically?

Thanks

**Comment by parisk** [comment]
Pasting is not possible in browsers, especially without a user action (like a keypress or a click) as you can't access the keyboard.

You should be able to do this in Electron apps (like Visual Studio Code) though normally. Just fetch the terminal and write the contents to the terminal using the [`write`](http://docs.xtermjs.org/module-xterm_src_xterm.html#write) method.

Does this cover your case?

**Comment by TaiAivaras** [comment]
Not exactly.. as i said in browser xterm terminal paste from clipboard works fine using [Shift+Insert] keys, i was wondering how to send that same exact signal to terminal programatically.

**Comment by parisk** [comment]
I don't think that this can be implemented easily. You should be able to use [`execCommand`](https://developer.mozilla.org/en/docs/Web/API/Document/execCommand) here, but I know that it's tough to get it working with paste.

From what I have read, it needs additional permissions from the user. If you manage to trigger the `paste` command, this should do the job for you.

**Comment by TaiAivaras** [comment]
Alright, thanks

**Comment by Tyriar** [comment]
All I do in vscode to paste is:

```js
xterm.focus();
document.execCommand('paste');
```

I think `document.execCommand` has some restrictions due to security concerns in browsers though.
