### ISSUE TITLE
Alternative keyboard shortcuts for copy and paste

### ISSUE THREAD

**Issue by ManojkumarV** [sourcelair/xterm.js#292]
Right now copy and paste is done using Ctrl+Insert and Shift+Insert shortcut keys. 
I need to achieve copy using Ctrl+Shift+C and paste using Ctrl+Shift+V.
How to achieve this functionality.

**Comment by parisk** [comment]
Hi @ManojkumarV Ctrl + Shift + C and Ctrl + Shift + V should be working without issues. Over which version of xterm.js did you test this?

**Comment by ManojkumarV** [comment]
Hi @parisk Ctrl + Shift + C is opening web inspector since it is the default shortcut for web inspector. The selected text is not getting copied. I need to copy the selected text if the focus is on the terminal. 
Also Ctrl + Shift + V is pasting the copied text only in Chrome browser and is not working in firefox. 
I tested in version 1.1.3. And I used Ubuntu OS to test.

**Comment by Tyriar** [comment]
@parisk I don't think ctrl+shift+c ever worked for the web client, ctrl+shift+v works however.. I needed to implement this using `attachCustomKeydownHandler` in vscode.

At some point all these custom shortcuts should be pulled out and easily disabled/enabled.

**Comment by parisk** [comment]
Yes, it would be really handy if we decoupled keyboard shortcuts at some point.

@ManojkumarV what you could do for now is attach a custom keydown hadnler like @Tyriar indicated and use `execCommand` to copy on Ctrl + Shift + C.

This should do the work (tried and worked for me):

```javascript
term.attachCustomKeyDownHandler(function (e) {
  // Ctrl + Shift + C
  if (e.ctrlKey && e.shiftKey && (e.keyCode == 3)) {
    var copySucceeded = document.execCommand('copy');
    console.log('copy succeeded', copySucceeded);
    return false;
  }
});
```

**Comment by ManojkumarV** [comment]
@parisk Thanks for the solution. Now copy works fine. But Ctrl + Shift + V works only in chrome browsers. But its not working in firefox. Is there any way to work around the same in all browsers?

**Comment by TDaglis** [comment]
If I recall correctly, Ctrl + Shift + V does not work in Firefox because it is sometimes used by plugins like Adblock plus

**Comment by parisk** [comment]
Also, it's really hard to paste programmatically in a browser. It seems you need extra permissions: https://github.com/sourcelair/xterm.js/issues/284#issuecomment-250404517.

Should we move forward and close this?

**Comment by ManojkumarV** [comment]
@parisk Thanks. I'll close this issue

**Comment by TDaglis** [comment]
Well if Shift + Insert successfully pastes in Firefox the issue with Ctrl + Shift + V is that it is handled by someone else and it never arrives to the xterm.js handlers. Since in this case pasting is triggered by a user action (keyboard event), the programmatically pasting issue does not apply here.

**Comment by BobVul** [comment]
AFAICT, Ctrl+Shift+V does not work even if nothing else is handling it in Firefox (e.g. clean profile, nothing installed). In fact, the event gets through just fine any JS handler.

The problem appears to be that xterm.js is specifically listening for a `paste` event, not they key sequence. In Firefox, Ctrl+Shift+V does not trigger a paste event.

Unfortunately, I don't think listening for the key event will help. Sure, it's possible (easy, even) to catch Ctrl+Shift+V — but I don't think there's any way to access the clipboard from there (for security reasons). The only way around that would be to create a browser extension that can run more privileged code.

The only other alternative (apart from Shift+Insert) is to stop catching Ctrl+V and use that for pasting instead. But of course that stops you from entering `^V` into the terminal, so there'd need to be a way around that — another key sequence or a popup asking which action? — which would be a bit of a mess.

**Comment by l0gicgate** [comment]
For people who want to support `Ctrl + V` as paste:

```js
xterm.attachCustomKeyEventHandler(e => {
  if (e.key === 'v' && e.ctrlKey) {
    return false;
  }
});
```

This works for me cross browser.
