### ISSUE TITLE
Right-click paste does not work in Firefox and IE

### ISSUE THREAD

**Issue by croiuki** [sourcelair/xterm.js#310]
Since 2.0 version, Right-click paste work in Chrome, but does not work in Firefox and IE.

Details

Browser and browser version: Firefox 49.0.1.6109 / IE 11.0.9600
OS version: Windown 7
xterm.js version: 2.0.0 / 2.0.1

**Comment by croiuki** [comment]
I think that it is because the following code do not work in FireFox
```
if (!clickIsOnSelection) {
	term.textarea.style.position = 'fixed';
	term.textarea.style.width = '10px';
	term.textarea.style.height = '10px';
	term.textarea.style.left = x + 'px';
	term.textarea.style.top = y + 'px';
	term.textarea.style.zIndex = 1000;
	term.textarea.focus();
	...
}
```

**Comment by goflatworld** [comment]
I have the same issue. My issue is that right click doesn't work on IE, Firefox and Chrome.

**Comment by parisk** [comment]
Thanks for reporting @croiuki @goflatworld.

Can you please describe in some more details what happens? Do you get a right-click menu that does not have the paste option or you don't get any right-click menu at all?

**Comment by croiuki** [comment]
I get a right-click menu that does not have the paste option. I think it is because right-click menu does not  notice term.textarea is editable at that time.

**Comment by parisk** [comment]
Cool. I 'll give it a try.

**Comment by goflatworld** [comment]
My issue is that right click popup the menu, but paste is greyed out.

**Comment by parisk** [comment]
@croiuki I just opened #342 which seems to be fixing this issue.

Can you please give a try to the `issue-#310-cross-browser-right-click` (please remember to build it after checking out!) and let me know if it works for you?

**Comment by croiuki** [comment]
@parisk  I try it ,but it also does not work.
