### ISSUE TITLE
The library seems to work in IE10 

### ISSUE THREAD

**Issue by jcubic** [sourcelair/xterm.js#311]
After including [promise-polyfill](https://github.com/taylorhakes/promise-polyfill) it seems to work in IE10. I've run terminal, executed `vi` and everything seems to be working.

**Comment by Tyriar** [comment]
Strange, I'm quite sure there are no promises used. I double checked dist/xterm.js in case Babel did something and it doesn't contain "promise" either. Perhaps that introduces another polyfill that we rely on? We made a decision to only support IE11+ anyway. /cc @parisk

**Comment by parisk** [comment]
@Tyriar is right. Promises are not used in xterm.js ([except for the demo](https://github.com/sourcelair/xterm.js/blob/0f8fc63a5e5a27a83101ba9bea3f127b0465a7f6/demo/main.js#L65)).

While xterm.js might work in IE10, we do not want to support and guarantee this officially. Thanks for pointing out though, it's good to know it seems to work on IE10!
