### ISSUE TITLE
contextmenu  does not   work  (Right-click)

### ISSUE THREAD

**Issue by guo-guo** [sourcelair/xterm.js#312]
It does not work   When I  use it , please Tell me  How to solve it. (xterm.js-446)

**Comment by parisk** [comment]
Hi @guo-guo,

Context menu works for me in the demo app on macOS on Chrome.

Did you try using the context menu in the demo app? If it works in the demo, but not in your app that uses xterm.js, this seems to be an issue with your app.

Can you provide also the OS, browser and browser version that you used?

**Comment by guo-guo** [comment]
@parisk  I   want to  click  on the right  then the pop-up menu

**Comment by parisk** [comment]
@guo-guo does the demo app of xterm.js work for you? (To start it just clone the repo and run `npm install && npm run`)

Can you provide the following information also:

1. OS and OS version
2. Browser and browser version

**Comment by guo-guo** [comment]
@parisk    These are my code . I want to copy the selected text . It  does not  work .please help me
on(this.element, 'contextmenu', function (ev,item) {
    console.log('contextmenu');
     var menu = ReactDOM.render(
            <ContextMenu
            items={[
                {
                  name: context => 'copy',
                    onClick: context => {
                      copyHandler.call(this,ev,term);   //There is a mistake
                    },
                },
                {
                    name: context => 'paste',
                    onClick: context => {
                        console.log(context);
                    }
                },
            ]}
            />,  document.getElementsByClassName('xterm-viewport')[0]);
    menu.show({top: ev.layerY, left: ev.layerX}, {elem: item});
    rightClickHandler.call(this, ev, term);
});

**Comment by guo-guo** [comment]
@parisk   Problem has been solved,    Thank you  very much

**Comment by parisk** [comment]
Great! Can you share with us what was the problem and how did you manage to solve it?
