### ISSUE TITLE
Document Terminal constructor & options

### ISSUE THREAD

**Issue by takluyver** [sourcelair/xterm.js#313]
In the source code, it looks like an options object can be passed to the terminal constructor, but this is not in the API docs. We're passing options in to the constructor, so I hope it is meant to be part of the public API.

The `getOption` and `setOption` methods are documented, but I don't see a list of options to use with them.

**Comment by Tyriar** [comment]
@parisk we should take this opportunity to clean up the options, I don't think colors has worked for a long time for example.

**Comment by parisk** [comment]
Yep, sounds like a good idea. Adding this to the next milestone.

I think that the most important options to support are `geometry` and `cursorBlink`.

Is there anything else in mind?

**Comment by takluyver** [comment]
We pass in `rows` and `cols`.

**Comment by Tyriar** [comment]
FYI we do all ours after via `setOption` since that's necessary for our settings system to control things anyway.
