### ISSUE TITLE
Document 'title' event

### ISSUE THREAD

**Issue by takluyver** [sourcelair/xterm.js#315]
Jupyter listens for a 'title' event to update the tab title for the terminal. This still appears to be present in the code, but it's not documented. Is it intended to be part of the public API?

**Comment by Tyriar** [comment]
I didn't even know it did this, I listen to `ChildProcess.on('message')` https://github.com/Microsoft/vscode/blob/9e5eab5aa72c6c9503122223a80006f7dac2eb3f/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L269

**Comment by parisk** [comment]
@takluyver indeed this event exists, but is not part of the public API yet. We can document it and include it in the public API. Seems like a good candidate.
