### ISSUE TITLE
! completion in zsh not working correctly

### ISSUE THREAD

**Issue by octref** [sourcelair/xterm.js#319]
## Details
- Browser and browser version: Chrome 54.0.2840.71 (64-bit)
- OS version: OS X 10.11.6
- xterm.js version: master
### Steps to reproduce
1. `zsh`
2. `ls -la`
3. `!ls<Tab>`

Expected to see `ls -la`, instead see `ls -la -la`

Originally repoted at https://github.com/Microsoft/vscode/issues/14177

**Comment by akalipetis** [comment]
Can you please verify this has been fixed @octref? I can't reproduce this on VS code on macOS.

**Comment by octref** [comment]
I can't repro it either. This seems to be fixed but I'm not sure. @Tyriar should know better.

**Comment by Tyriar** [comment]
Not sure what could have fixed it but... 🎉 😉
