### ISSUE TITLE
Data loss when resizing

### ISSUE THREAD

**Issue by blink1073** [sourcelair/xterm.js#325]
Resizing should preserve the existing text.
## Details
- Browser and browser version: 
- OS version: OSX 10.11
- xterm.js version: 269540bfedc9fc4b160d75d15e54a2e07854f7e5
### Steps to reproduce
1. Run the demo
2. Reduce the column count
3. Increase the column count and the original data is not restored.

Iterm2 handles this by reflowing the rows when you decrease the width.

<img width="522" alt="screen shot 2016-10-25 at 2 22 25 pm" src="https://cloud.githubusercontent.com/assets/2096628/19700850/8f8794a4-9abe-11e6-8dbb-4b243e4d55c0.png">

<img width="344" alt="screen shot 2016-10-25 at 2 22 43 pm" src="https://cloud.githubusercontent.com/assets/2096628/19700851/93541a08-9abe-11e6-9ea7-fc5106900457.png">

vs.

<img width="804" alt="screen shot 2016-10-25 at 2 23 48 pm" src="https://cloud.githubusercontent.com/assets/2096628/19700907/cac3112e-9abe-11e6-8201-c086e7e3baa9.png">

<img width="512" alt="screen shot 2016-10-25 at 2 24 01 pm" src="https://cloud.githubusercontent.com/assets/2096628/19700910/cf7d4cf2-9abe-11e6-89d0-5ff336a145b3.png">

<img width="832" alt="screen shot 2016-10-25 at 2 24 11 pm" src="https://cloud.githubusercontent.com/assets/2096628/19700914/d3a2bbe6-9abe-11e6-80bd-b6b7a78741f5.png">

**Comment by parisk** [comment]
Thanks for reporting @blink1073. Will take a deeper look on this.

**Comment by Tyriar** [comment]
I've been closing most of these in favor of https://github.com/sourcelair/xterm.js/issues/103 but they're technically different issues I guess. Let's use this to track not retaining characters off screen (Related request to support wrapping https://github.com/sourcelair/xterm.js/issues/166) and #103 to track only the prompt.

**Comment by waywaaard** [comment]
I've experienced the same errors as I am using xterm.js without a *"real"* process (I am using https://github.com/skulpt/skulpt). I am just piping in my stdin and stdout streams.

**Comment by Tyriar** [comment]
I believe fixing this may fix some of the escape sequence tests. I think the reason t0021-CUB.in is failing for example is because the cursor position is reset to 0 after a line is wrapped but it should be cols.

**Comment by ppot** [comment]
@Tyriar Any input on when this resizing issue will be resolve?

**Comment by Tyriar** [comment]
@imsnif was handling this one. Still a WIP, see https://github.com/sourcelair/xterm.js/issues/404

**Comment by ppot** [comment]
Got it! Looking at it right now.

**Comment by imsnif** [comment]
Still working on it! :)
I don't yet have an ETA, but am close to finishing a prototype (this is a very big change). Hoping to have more information on the weekend, but I don't want to make any promises.

**Comment by ppot** [comment]
@imsnif Any input on what you still need to do?

**Comment by imsnif** [comment]
@ppot - in short: right now in my prototype ```resize```, ```refresh``` and ```write``` are working with the external line index. There are some kinks I need to work out with them (including some performance issues) and then make sure all the other parts of the code work as well (```eraseRight```, etc.)

Then pull from upstream (I'm a little behind), write tests, clean everything up and we're good. Once I get the prototype to work (shouldn't be long now, I hope) I'll have a much clearer ETA of when the rest will be done.

**Comment by blink1073** [comment]
Fixed by #616, thanks @LucianBuzzo!
