### ISSUE TITLE
Tmux ignores mouse scroll events/shits itself on selection events

### ISSUE THREAD

**Issue by wilrnh** [sourcelair/xterm.js#329]
## Details
- Browser and browser version: Chrome 54
- OS version: OSX 10.11.6
- xterm.js version: demo @ https://github.com/sourcelair/xterm.js/commit/996c641a790a0b27c61c62e02b806cadd4bb3f7a
### Steps to reproduce
1. Start demo
2. `tmux attach`
3. Enable mouse mode in tmux `set -g mouse on`
4. Scroll or select text in terminal window

**Comment by wilrnh** [comment]
Microsoft/vscode#14627

**Comment by Tyriar** [comment]
Likely related to https://github.com/sourcelair/xterm.js/issues/426

**Comment by parisk** [comment]
Thanks for reporting this @wilrnh. Scrolling seems to be working fine for me.

I ran into a few issues though, which seem to be related to #434 (rendering issues).

Does anything happen at all when scrolling after running `set -g mouse on` in tmux?

**Comment by julianlam** [comment]
@parisk according to OP's repro steps, he is using `set -g mouse on`

**Comment by piggyslasher** [comment]
Working for me with `set -g mouse on`.

Vim scrolling is also working flawlessly AFAICS. Can you paste your `.tmux.conf` file?

**Comment by Tyriar** [comment]
Fixed in https://github.com/sourcelair/xterm.js/pull/670

**Comment by heamaral** [comment]
Not working on Windows 10 Pro (1809 - 17763.288). Already tried with ConPTY and WinPTY and mouse events are now working.
I've removed the Zoom Out keybinding (CTRL+-), tried to press it on terminal and it doesn't work too.

**Comment by Tyriar** [comment]
@heamaral this issue is on macOS, everything is very different on Windows. I've never even tried to use mouse events on Windows so not sure what the current state is.
