### ISSUE TITLE
Unable to load version 2.0

### ISSUE THREAD

**Issue by oddjobz** [sourcelair/xterm.js#330]
I've just tried to upgrade to 2.0 for an application written using xterm.js as of around six months ago. When the application loads it fails complaining on an unexpected token "import". I am assuming there is a new dependency that I'm missing .. where do I get "import" from please?

## Details
- Latest version of Chrome
- OS version: Ubuntu 16.04
- xterm.js version: current master

### Steps to reproduce

1. attempt to load xterm.js
2.

**Comment by waywaaard** [comment]
xterm.js is now written in ES6 which uses the new module syntax. Either install the npm package to get a transpiled version or use the files in the `/dist` directory.

**Comment by oddjobz** [comment]
Perfect, tvm.

**Comment by parisk** [comment]
Hi @oddjobz, @waywaaard is right. Starting version **2.0** we broke the "import" API.

You can read more about the changes and how to migrate at http://xtermjs.org/blog/articles/2016-10-03-xtermjs-2.0#migrating-from-xtermjs-10-to-20.

Let us know if there is anything missing.
