### ISSUE TITLE
[regression] scroll bar invisible after only column count changes

### ISSUE THREAD

**Issue by yume-chan** [sourcelair/xterm.js#3504]
## Details
- Browser and browser version: Microsoft Edge 96.0.1040.0
- OS version: Windows 10
- xterm.js version: 4.14.1

### Steps to reproduce

https://codepen.io/yume-chan/pen/YzxPJGL

1. When loaded, the scrollbar is visible
2. Scroll the terminal to top
2. Click "Change Width" button (only changes column count), now scroll bar becomes invisible
3. Click "Change Height" button (only changes row count), it becomes visible again

It may be a regression caused by #3398

Use FitAddon may also cause this issue if only width changed.

**Comment by yume-chan** [comment]
A temporary workaround would be calling `(terminal as any)._core.viewport._refresh()` after `terminal.resize()` or `fitAddon.fit()`.

**Comment by SquitchYT** [comment]
This workaround don't work for me. 
However, I have downgraded to 4.13.0 and it works perfectly

**Comment by SquitchYT** [comment]
Seem to be fixed

**Comment by yume-chan** [comment]
Noticed that my repro may not work on high DPI monitors (because the `scrollTop` can be fractional). Updated repro to make it more reliable and inserted an extra repro step (2) in case of it still doesn't reproduce.

**Comment by mduft** [comment]
I still got an issue there. with 4.15.0, scrollbars are overlapped *frequently* but not always. With 4.13.0 everything is OK.

This is using ng-terminal in an angular application (which includes FitAddon). When resizing (by dragging browser window size), the scrollbar sometimes appears, and sometimes disappears - it also seems to jump around in larger increments, not following the resizes exactly. with 4.13.0 there is a smoothly reacting scrollbar all along.
