### ISSUE TITLE
The new version enables the mouse function in VIM mode: after set mouse = a, the mouse click character is no longer highlighted

### ISSUE THREAD

**Issue by yoyo-milktea** [sourcelair/xterm.js#3510]
I recently updated the version to 4.14.1. The previous version was 3.14.4. The new version is in VIM mode: set mouse = a enables the mouse function, the click character is no longer highlighted, and the mouse pulley event is also prohibited. Is this the new version that removes these functions or can be enabled through settings?

**Comment by yoyo-milktea** [comment]
> You use it like the `onData` event, but as bytestring, thus you should not try to convert it with UTF-8. E.g. with `node-pty`:
> 
> ```ts
> term.onBinary(data => pty.write(Buffer.from(data, 'binary')))
> ```
> 
> Also see https://xtermjs.org/docs/guides/encoding/#output.

Is the pty import from 'node-pty'?And the Buffer import from 'buffer'?
Why does the new version of this function need to be accessed and written by itself? How good is the internal processing as before. Now the plug-in is more cumbersome to use

**Comment by jerch** [comment]
Ok, so you prolly send the data to the server with a websocket? Then do the same with `onBinary`. Most likely you need to treat the data from `onBinary` differently on server side to avoid the UTF8 conversions, example:
```javascript
// client side
this.term.onBinary(data => { this.socket.send(JSON.stringify({data, type: 'binary'})) })

// server side with nodejs and ws
// ptyObj is your pty object from node-pty.spawn
ws.on('message', msg => {
  const payload = JSON.parse(msg);
  if (payload.type && payload.type === 'binary') ptyObj.write(Buffer.from(payload.data, 'binary'));
  else ptyObj.write(payload.data);
})
```
If you dont use nodejs on server side you have to do it likewise - pass the bytestring as bytes to the PTY (refer to your server env how to do that).

**Comment by jerch** [comment]
> I don't understand the server.

Then you will have to coordinate that with your backend devs.

> Is there a way to achieve the effect I want without node processing?

You can do that in any backend system normally, e.g. in python you can send binary data to the PTY from JSON strings by doing something like this: `ptyObj.write(json.loads(msg)['data'].decode('ascii'))`

> Do you know the effect I want?

Yes, you can actually test it in the demo app (which forwards `onBinary` correctly under linux/macos).
