### ISSUE TITLE
Browser keep jump to top-left of the page when focusing on terminal

### ISSUE THREAD

**Issue by yangaobo** [sourcelair/xterm.js#357]
Whenever I focus on the terminal, the browser will jump to top because of the following line added
https://github.com/sourcelair/xterm.js/commit/ebbeeefd86bedf5c9654a8edee6f0904756902e8

My terminal is vertically in the middle of my web app, any solution that i can stop the attempt to focus the invisible textarea in `top: -9999rem`?

## Details
- Browser and browser version: Chrome Version 53.0.2785.143 (64-bit)
- xterm.js version: 2.1.0

### Steps to reproduce

1. Render xterm out of ur viewport height
2. Either click the term or type inside will focus on the invisible textarea

**Comment by waywaaard** [comment]
I have the same problem and fixed it by removing/overriding this style. However, I am using xterm inside an iframe embedded on the normal page.

**Comment by Tyriar** [comment]
`top: 0` will probably actually work just as well since it's already off screen to the left.

**Comment by nat64check-admin** [comment]
I'm having this exact behaviour again with xterm 3.8.0. Regression?
