### ISSUE TITLE
scrollback option should be added to API

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#360]
I believe changing `scrollback` via `setOption` will work fine right now but it needs to be confirmed to work, unit tested and documented as an option in the constructor API https://github.com/xtermjs/xtermjs.org.

**Comment by Tyriar** [comment]
Blocked by #360

**Comment by Tyriar** [comment]
Removing from 2.2.0, we want https://github.com/sourcelair/xterm.js/issues/361 resolved before adding to API.

**Comment by parisk** [comment]
Fixed: https://xtermjs.org/docs/api/terminal/#options.
