### ISSUE TITLE
Retrieve terminal content

### ISSUE THREAD

**Issue by tpmai22** [sourcelair/xterm.js#3642]
I followed through the docs but there is no methods help me to retrive the content of the terminal. I think `terminal.getText()` might be usefull for the users

**Comment by tpmai22** [comment]
![image](https://user-images.githubusercontent.com/43376325/154112744-4595899e-0a28-4593-af6e-884197efdbcc.png)
I have something like this but I want to get the `content` displayed inside the `terminal` where I got the use case in which if I receive the same data that has been displayed on the terminal. I will not have to re render it.

**Comment by tpmai22** [comment]
@Tyriar you got any idea about this ?

**Comment by Tyriar** [comment]
@tpmai22 it's a relatively expensive action to fetch the text due to the way it's stored. You need to construct each line like this:

```ts
xterm.buffer.active.getLine(x)?.translateToString()
```
