### ISSUE TITLE
Quick start work???

### ISSUE THREAD

**Issue by 1f7** [sourcelair/xterm.js#365]
Try Quick start from http://xtermjs.org/ and neither version does not work

## Details
- Browser and browser version:  FF 49.0.2
- OS version: puphpet on Ubuntu 16.0.4.1
- xterm.js version: 2.0.0, 2.0.1, 2.1.0, repo xterm.js-master

### Steps to reproduce

1. index.html with Quick start content with correct path to xterm
2. view only terminal window with `Hello from xterm.js $  ` no one key not work

**Comment by Tyriar** [comment]
This is expected as there isn't a shell hooked up to it yet. You should check out the demo in the repo for how it talks to a terminal in the server side. 

@parisk maybe we should link to the demo as a follow up?

**Comment by 1f7** [comment]
**@Tyriar** Thanks for the quick response.
Yes, this demo works 
but in this demo is more than 2 file from Quick start :)
