### ISSUE TITLE
xterm.js simply exports Terminal so it should be called Terminal.js

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#373]
I propose we change `xterm.js` to `Terminal.js` since all it does is export the `Terminal` object. Then on the `browserify` call output it as `./dist/xterm.js`.

**Comment by Tyriar** [comment]
Once Terminal is fully TS it would make sense to be in a Terminal.ts file like the others, what if we had an xterm.ts as well which simply imported and exported `Terminal`?

**Comment by parisk** [comment]
Let me get back to this. I propose closing this along with #374 and always keep a file named `xterm.js` in the repo, even if it serves only as an entry point for the library.

IMO it's intuitive to have a file named like that, based on the library's name. 

Plus, I do not think that there will be much gain by such a rename.

**Comment by Tyriar** [comment]
We'll eventually pull out a `Terminal` object, let's reference it from xterm.ts when we do that.
