### ISSUE TITLE
Proposals for fixing the 'dist' issue: publish on a release branch

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#375]
We could only commit `dist/` on a release branch and publish that instead of master, this is probably the best way to avoid dist diffs showing up in PRs constantly.

For a release we could branch off to say `release/2.2` (or just `release`), when a release is done it could then be tagged (for bower).

**Comment by parisk** [comment]
Based on my comments from #387:

IMO we should re-introduce a git ignored build directory other than dist for temporary builds.

@Tyriar what about using the out dir for temporary build directory?

**Comment by Tyriar** [comment]
@parisk that could potentially lead to accidentally referencing the TS build files from the browserify output, it's much cleaner keeping them separate as then each folder has a specific purpose and it's clear what generated it.

**Comment by parisk** [comment]
👍 . Let's restore the `build` directory then if we have no objections.

IMO the release branch will complicate things more than needed, while the previous set up served it's purpose well.
