### ISSUE TITLE
Consider ignoring all alt+<keypress> events on Windows

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#384]
alt+letter is used to access menus on Windows. I'm not aware of any Windows programs accepting these key sequences so maybe they should just be ignored?

See https://github.com/Microsoft/vscode/issues/10525

**Comment by hjwp** [comment]
Lots of console/terminal applications need the alt key to work correctly.  emacs, vim, bash...  Would this proposal break them?

**Comment by parisk** [comment]
I think this should be handled by the consumer app with [`attachCustomKeydownHandler`](http://xtermjs.org/docs/api/Terminal/#attachcustomkeydownhandlercustomkeydownhandler) and not xterm.js itself. What do you think @Tyriar?

**Comment by Tyriar** [comment]
I might see what powershell, cmd, cmder, etc. do for this in vscode, thanks 😃
