### ISSUE TITLE
With websocket, terminal send twice to websocket

### ISSUE THREAD

**Issue by ChanghyeonYoon** [sourcelair/xterm.js#3870]
## Details
- Browser and browser version: Chrome 102.0.5005.115 (Official Build) (arm64)
- OS version: MAC OS 12.4
- xterm.js version: 4.5.0

### Steps to reproduce

1. I attach webSocket 
```
const socketEventListener = useCallback(({ key }) => {
      if (!socketRef.current) return;
      socketRef.current.send(key);
      socketRef.current.onmessage = (event: MessageEvent) => {
         const { data: res } = event;
         terminal.current.write(res);
      };
   }, []);

   useEffect(() => {
      if (!terminalRef?.current) return;
      console.log('terminalRef');
      terminal.current.open(terminalRef.current);
      terminal.current.onKey(socketEventListener);
      terminal.current.focus();
   }, [terminalRef]);

```
When I type 'A', socket send 'A' twice.
What is the problem??

terminal and socketRef is rapped by useRef

**Comment by Tyriar** [comment]
onKey can file multiple times for different key events, you probably want onData.

**Comment by ChanghyeonYoon** [comment]
@Tyriar But when i changed onKey to onData, same problem

**Comment by Tyriar** [comment]
@ChanghyeonYoon the bug is likely on your end, if `onData` fired 2 times then no user of xterm.js would work.
