### ISSUE TITLE
Failure when building with browserify 

### ISSUE THREAD

**Issue by budde377** [sourcelair/xterm.js#397]
When building my project with browserify and babelify, I get the following error:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module './Generic.js' from '/opt/project/node_modules/xterm/dist'
    at /opt/project/node_modules/resolve/lib/async.js:55:21
    at load (/opt/project/node_modules/resolve/lib/async.js:69:43)
    at onex (/opt/project/node_modules/resolve/lib/async.js:92:31)
    at /opt/project/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
```

This is new from version 2.2.0 and 2.2.1.

## Details
- OS version: ubuntu-12.04
- xterm.js version: 2.2.0 and 2.2.1

### Steps to reproduce

1. Create a project witch `require('xterm')`
2. Build this project with browserify and babelify

**Comment by Tyriar** [comment]
Are you pointing at out/xterm.js or dist/xterm.js?

**Comment by budde377** [comment]
This small example should illustrate what I'm doing:

index.js
```javascript 
var Xterm = require('xterm')
console.log(Xterm)
```

package.json
```json
{
  "name": "xtermex",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "xterm": "^2.2.1"
  },
  "devDependencies": {
    "browserify": "^13.1.1"
  }
}
```

Running `./node_modules/.bin/browserify index.js` will fail with the error mentioned above.

**Comment by parisk** [comment]
OK, I am not sure what causes this and if it's a bug of xterm.js TBH, but:

It seems that it's source is this [line of code](https://github.com/sourcelair/xterm.js/blob/master/dist/xterm.js#L506) in the `dist/xterm.js`.

It seems like it's trying to access the real `./Generic.js` file, which does not exist actually, [despite it is being bundled](https://github.com/sourcelair/xterm.js/blob/master/dist/xterm.js#L522) in `dist/xterm.js`.

I Googled a little bit about issues when requiring standalone bundles (like xterm.js) with browserify but I was not able to find out what might be going wrong.

Any ideas? Maybe an issue at the upstream browserify repo is the best option.

**Comment by budde377** [comment]
I suspect that the script works fine in the browser?

**Comment by budde377** [comment]
I'll take a look at this tomorrow (CET).

**Comment by parisk** [comment]
Yep, script works fine in the browser and with require.js (tested latest release).

**Comment by budde377** [comment]
Can it be something about double browserifying? I mean wouldn't it make
sense if the entrypoint of the package was `src/xterm.js`?

**Comment by Tyriar** [comment]
@budde377 src/xterm.js depends on TS modules that are build to out and then packaged up with browserify in dist.

I guess browserify doesn't know that we redefined `require`. Pointing it at `out/xterm.js` instead would probably work fine as that's the ES5 version before we concat into a single module using `browserify`. You would need to trigger a build manuall to generate that though (and doesn't work on Windows until https://github.com/sourcelair/xterm.js/issues/359 ).

Perhaps there's an option you can pass to browserify?

**Comment by budde377** [comment]
Okay, I think that I have a pretty clear image of the problem now. I have in https://github.com/sourcelair/xterm.js/pull/398 proposed that you add a prepublish script which will build the TS and publish it. This will enable usage with `require('xterm')` of non-browserified code. Please note that I have added a .npmignore file which does not contain the `out/` folder. This will overwrite the `.gitignore` file for `npm publish` and should be updated with the `.gitignore` file.
