### ISSUE TITLE
Deprecate and finally drop Bower support

### ISSUE THREAD

**Issue by parisk** [sourcelair/xterm.js#406]
I think it's time to deprecate support for Bower gracefully and eventually drop it completely in the next major release (3.0.0).

This is a topic that has been discussed a little bit in the past, but I always argued against it since we had users that preferred to use xterm.js via Bower.

Eventually I changed my mind after seeing the weird things that can happen with the built files checked out in the repo and reading https://github.com/codemirror/CodeMirror/issues/4328#issuecomment-255110880, which actually states the fundamental design issue of Bower: **it confuses source repositories (like this) with distribution mechanisms**.

To the point, I propose taking the following steps to make sure that this goes as gracefully as possible for our users:

1. Create a new **xtermjs/bower** repository, where we will point the `xterm.js` Bower package and push the built files of each release there (starting with the current one).
2. Remove `dist` from this repository completely, ignore it from Git and include it in NPM distributions
3. Stop updating the **xtermjs/bower** repository starting from version 3.0.0

/cc @Tyriar

**Comment by Tyriar** [comment]
:fireworks: :tada: :sparkler:

**Comment by kvanberendonck** [comment]
Just pulled xterm using bower, is this deprecation necessary? Probably wouldn't use it if it isn't available on bower.

**Comment by Tyriar** [comment]
@kvanberendonck bower puts additional burden on package maintainers (namely keeping compiled files in the tree and additional release steps) is the main reason for dropping. Any reason you don't use the npm package and bundle it with your bundler of choice?

**Comment by kvanberendonck** [comment]
We generally don't use npm except for build system dependencies. The build system spans across multiple related parts of the project, and each has its own set of bower dependencies and versions

**Comment by parisk** [comment]
@kvanberendonck the main issue with Bower it that it has adopted a practice which is problematic for projects like ours; it has equated the repository with the distribution of the package.

This means what @Tyriar said, maintaining compiled files in tree (which is quite confusing for new contributors), adding additional release steps (extra commit) and be always careful not to commit a new file in `dist` (as it cannot be `.gitignore`d).

What we will do at first is create a new repository, which will replace the old one in bower (this requires no change by you).

Next from version **3.0.0**, we will stop maintaining this repository completely, so you will have to change the way you download xterm.js.

What we could do though, is publish the build artifact as to our GitHub Releases, so you can use the [tar/zip URL format in your dependencies](https://github.com/bower/spec/blob/master/json.md#dependencies).

**Comment by Tyriar** [comment]
Bower has been deprecated https://github.com/bower/bower/issues/2298

We should have 2.6 as the last bower ready release imo.

**Comment by Greenek** [comment]
If anyone is looking for `xterm.js>=3.0` in bower repo, you can use `bower install --save xterm.js-next`. It's [my fork](https://github.com/Greenek/bower-xterm.js) created for personal use, but I try to keep it updated.

**Comment by Tyriar** [comment]
@Greenek thanks for taking that up! 😃
