### ISSUE TITLE
Write Does Not Print The Incoming Request

### ISSUE THREAD

**Issue by cemalgnlts** [sourcelair/xterm.js#4106]
## Details
- Browser and browser version: Chrome 103.0.5060.53
- xterm.js version: latest

### Steps to reproduce

The following request is coming from my server and I'm trying to print:
```
[ 'dstern' will expire in 364 days - Please 'validate' your account soon ]

Please press your BACKSPACE key: [H[2J
=======================================================================
SDF host uptime report for Seattle WA, Dallas TX (USA) and Germany (EU)
             Please use 'tty.sdf.org' for general access
=======================================================================

SERVER          DAYS+HOUR:MIN       USERS   MACHINE LOAD
```

This is the result I get when I print this data:
```
=======================================================================
SDF host uptime report for Seattle WA, Dallas TX (USA) and Germany (EU)
             Please use 'tty.sdf.org' for general access
=======================================================================

SERVER          DAYS+HOUR:MIN       USERS   MACHINE LOAD
```

For some reason, when it receives this character, it deletes the previous ones.
`Please press your BACKSPACE key: [H[2J`

**Comment by jerch** [comment]
> For some reason, when it receives this character, it deletes the previous ones.
Please press your BACKSPACE key: �[H�[2J

Sure it does, as those codes literally say: CUP (move cursor to home position), ED 2 (erase whole display). So thats the expected behavior.
