### ISSUE TITLE
Import broken in jspm/systemjs

### ISSUE THREAD

**Issue by jgillich** [sourcelair/xterm.js#412]
Not sure what is going on here, but I'm importing xterm.js via SystemJS and it fails horribly:
```
 GET XHR http://localhost:3000/app/jspm_packages/npm/xterm@2.2.1/dist/Generic.js [HTTP/1.1 404 Not Found 1ms]
// many more...
```
Somehow the browserify bundle doesn't work correctly and it instead calls `require` from SystemJS.
Not sure what's going here.

To reproduce:
1. Install jspm
1. Create a new directory and run `jspm init`
1. `jspm install npm:xterm`
1. In your index.js, do `import Terminal from 'xterm'`
1. Load the page

It works when I use `jspm instal github:sourcelair/xterm`, in which case jspm doesn't even touch `dist/xterm.js`. I have absolutely zero idea why, and maybe I should be reporting this against jspm instead.

**Comment by parisk** [comment]
This seems to be a duplicate of #397, can you please try this using the latest version on master?

**Comment by jgillich** [comment]
Ah, that would explain why it works when installing from GitHub. Thanks! (a new npm release would be great though :)

**Comment by parisk** [comment]
👍  nice idea: https://github.com/sourcelair/xterm.js/releases/tag/2.2.2
