### ISSUE TITLE
Missing CSS file in npm package

### ISSUE THREAD

**Issue by blink1073** [sourcelair/xterm.js#414]
Current release (2.2.2) does not include the `src/xterm.css` file.

**Comment by blink1073** [comment]
I am happy to submit a PR with a script that copies the file over before publishing:  cf https://github.com/jupyterlab/jupyterlab/blob/bda6c803494a0e6ddf5df673749be5a9590bf719/scripts/copyfiles.js

**Comment by Tyriar** [comment]
The copy is meant to be done here https://github.com/sourcelair/xterm.js/blob/master/bin/build#L29, maybe it's not being published due to `files` in package.json?

**Comment by blink1073** [comment]
It must only include JS files by default: https://github.com/jupyterlab/jupyterlab/blob/bda6c803494a0e6ddf5df673749be5a9590bf719/package.json#L97

**Comment by parisk** [comment]
On it.

**Comment by parisk** [comment]
@Tyriar and @blink1073 feel free to take a look at #416. I will merge ASAP.

**Comment by parisk** [comment]
Should be fine with [`2.2.3`](https://github.com/sourcelair/xterm.js/releases/tag/2.2.3)

**Comment by blink1073** [comment]
The copy script still didn't do the trick, because the release has the CSS in the `src/` folder but not the `lib/` folder.
