### ISSUE TITLE
Scroll not responding on OSX

### ISSUE THREAD

**Issue by BenHall** [sourcelair/xterm.js#421]
I just tried to integrate 2.2.3 replacing the older fork of xterm.js. Everything looks great, but scroll no longer responds. Is there anything else I need to do?

**Comment by BenHall** [comment]
The demo works as expected, which is why I'm surprised. Can you think of anything which would stop it from scrolling?

**Comment by BenHall** [comment]
Ahh, fixed it. I had a left over `position:absolute` being assigned to `.xterm-scroll-area`. I removed that and it looks good!

**Comment by parisk** [comment]
Happy it worked out!
