### ISSUE TITLE
Reconsider XON/XOFF PR to keep slave in sync with terminal

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#425]
See if https://github.com/sourcelair/xterm.js/pull/146 performs better after https://github.com/sourcelair/xterm.js/pull/422 lands. It could also be changed to let larger chunks of data (~1 viewport page?) as that should suffice for keeping ctrl+c more responsive as well as making commands such as `time` accurate.

**Comment by Tyriar** [comment]
I think pausing the process once a certain threshold is hit so xterm.js can catch up is the best thing to do here. The threshold could be quite large as well, say 1000+ lines or something, it's just commands that send a tonne of output will always outrun us.

**Comment by parisk** [comment]
Should we consider implementing this eventually? I think that after #422 performance improved radically and I am quite skeptical about this as it seems more like a hack, rather an actual performance improvement.

**Comment by Tyriar** [comment]
This is a must imo after looking into perf over the last week. Running a command such as `yes` will send too much output for xterm.js to possibly handle, meaning it will be chugging as fast as it can all the time and interrupting such a process is only possible once the output has been processed. Definitely not hacky, it improves stability significantly in certain use cases in addition we support XON (ctrl+s) and XOFF (ctrl+q)!
