### ISSUE TITLE
Connecting xterm.js using host , port , websocketurl

### ISSUE THREAD

**Issue by PradeepJaiswar** [sourcelair/xterm.js#433]
I am trying to integrate my local xterm.js setup inside atom editor. I am using https://github.com/learn-co/learn-ide/ as wrapper to  wrap xterm.js

I am running my local xterm.js as below 
```
Local url :: http://0.0.0.0:3000/
host :: 0.0.0.0
port :: 3000
path :: '/terminals'
web-socket url :: ws://0.0.0.0:3000/terminals/
```

To wrap xterm.js using https://github.com/learn-co/learn-ide/ it needs host , port , websocket url in config file as => https://github.com/learn-co/learn-ide/blob/master/lib/config.coffee 

Can anyone confirm i am using the right details as above. Because i am not able to connect to using wrapper, thought might be missing somethign while providing  host , port , websocket url.

**Comment by parisk** [comment]
Hi @PradeepJaiswar,

Thanks for posting. The best place to go and ask questions about integrating xterm.js into your application is our Gitter chatroom: https://gitter.im/sourcelair/xterm.js.

Also, please post some console logs/errors as they are really helpful.

We use GitHub issues almost exclusively for issues with xterm.js itself, so I'll move on with closing this.

**Quick comment**: Seems like your configuration depends on environment variables, so make sure you set the right values.
