### ISSUE TITLE
Big output in tmux (application) mode breaks rendering

### ISSUE THREAD

**Issue by parisk** [sourcelair/xterm.js#434]
Printing lots of output in tmux (application) mode results in broken rendering

## Details
- Browser and browser version: Chrome 55
- OS version: macOS
- xterm.js version: 23472e6fb4b1def129ed6b3f77a53a5e3a16afd3

### Steps to reproduce

1. Run the demo and open it in the browser
2. Run `tmux`
3. Run `ls -lR` into xterm.js' directory

#### `tmux`
![image](https://cloud.githubusercontent.com/assets/1188592/21576561/bd8e044e-cf2c-11e6-8d48-b056dacd4b6d.png)

#### `ls -lR` (no tmux status bar)
![image](https://cloud.githubusercontent.com/assets/1188592/21576559/b14a1038-cf2c-11e6-9341-0d781ee9e9ce.png)

**Comment by parisk** [comment]
Noting also that this produces no console logs or errors at all.

**Comment by Tyriar** [comment]
Does this happen before the circular list?

**Comment by parisk** [comment]
Likely not. Tried this on SourceLair (which uses 2.2) and the output gets rendered fine.

![image](https://cloud.githubusercontent.com/assets/1188592/21576980/6c857302-cf40-11e6-8e39-618bc31e920c.png)

**Comment by Tyriar** [comment]
I think I know what caused this.
