### ISSUE TITLE
Copying a wrapped line results in a newline at the end of the wrapped line

### ISSUE THREAD

**Issue by akalipetis** [sourcelair/xterm.js#443]
Copying and pasting a wrapped line, introduces a newline character at the position the line was wrapped.

### Steps to reproduce

1. Open the demo
2. Paste a long `echo` line, like the one below:
    ```
    echo this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big
    ```
3. When copied, the resulting line should be:
    ```
    this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big
    ```
4. It actually is:
    ```
    this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-
    is-big-this-is-big-this-is-big-this-is-big-this-is-big-this-is-big
    ```

**Comment by akalipetis** [comment]
For a real-world example, you can see franela/play-with-docker#66

**Comment by marcosnils** [comment]
@Tyriar do you think this is easy to fix?

**Comment by Tyriar** [comment]
@marcosnils not at the moment as this is blocked on https://github.com/sourcelair/xterm.js/issues/325, that change wwill properly track and re-wrap lines when resized, This should encode information for lines spanning multiple rows.

Once that is done though, `ClipboardHandler` [here](https://github.com/sourcelair/xterm.js/blob/ff29fd69a316c59f55dbec1cc86f00c262b73275/src/handlers/Clipboard.ts#L26) will just need to grab that line/row information and remove the problem new lines.

**Comment by cancan101** [comment]
Now that #325 is fixed, where does this issue stand (I am seeing it on: https://github.com/jupyter/notebook/issues/2256)?

**Comment by Tyriar** [comment]
The PR for #325 only fixed a portion of the problem, this is now blocked on https://github.com/sourcelair/xterm.js/issues/622 which has a (big) PR out.
