### ISSUE TITLE
"no such package available : @types/node" during npm install

### ISSUE THREAD

**Issue by jan-osch** [sourcelair/xterm.js#448]
node v6.4.0
npm  v3.10.3

**Comment by Tyriar** [comment]
Maybe it was a temporary outage? The package is certainly there https://www.npmjs.com/package/@types/node

**Comment by pparke** [comment]
While troubleshooting my own issues I came across this but it was complaining about @types/mocha, just happened 5 minutes ago.  The funny thing is this was after I had successfully installed and built on a different machine.  I'm having other problems with xterm.js though #451

**Comment by Tyriar** [comment]
I'm pretty sure this is an npm availability issue, closing this off.
