### ISSUE TITLE
Applications such as vim and htop hang, occurs in demo and own project

### ISSUE THREAD

**Issue by pparke** [sourcelair/xterm.js#451]
I'm not sure if there is an issue with running programs such as vim or htop but after I cloned the repo and tried running the demo I'm able to use the terminal in my browser until I enter a program such as vim.  After that it seems as though all input and output ceases.  

I've tried setting up a few different back ends just in case that was the issue (tty.js, the one included in the demo, an adaptation of ttyd) and I get the same issue every time.  I've also tried logging the data that is being received on the socket and I see output right up until I start vim/htop and then all output ceases.  I do see a closed event fired when I close the client.

I've even tried sending data manually from the client using term.send() just in case there was some issue client side.  I'm hoping that there's an easy fix to this and that I'm just overlooking something but since it happens when I run the demo I'm not so certain.  I've removed node_modules and rebuilt as well just in case.

I had a colleague try cloning and building on his machine but it complains about the @types/mocha dependency.

If anyone has any suggestions or tips I'd be happy for the help.

## Details
- Browser and browser version: 
Chrome 55.0.2883.87 (64-bit)
Opera 36.0.2130.65

- OS version: 
Xubuntu 4.4.0-57-generic

- xterm.js version: 
2.2.3

### Steps to reproduce

1.  I cloned the repo and ran npm install and npm start and then visited localhost:3000
2. run vim or htop and try to use any of the keys, terminal will be inactive

**Comment by Tyriar** [comment]
Yes I can reproduce, this is to do with https://github.com/sourcelair/xterm.js/pull/432 so you can move back before that was merged and it should work in the meantime https://github.com/sourcelair/xterm.js/commit/23472e6fb4b1def129ed6b3f77a53a5e3a16afd3

**Comment by pparke** [comment]
That worked, thanks so much :smiley:
