### ISSUE TITLE
how to use in angular2 app (service)

### ISSUE THREAD

**Issue by vtolstov** [sourcelair/xterm.js#454]
I have angular2 service that must provide tty console to some vm.
How can i import xterm only for this service ?
If i write import { Xterm } from 'xterm'; i get error
```
ERROR in ./src/app/ttycon.service.ts                                                                                                                   Module build failed: Error: /var/home/vtolstov/devel/panel/src/app/ttycon.service.ts (2,10): Module '"/var/home/vtolstov/devel/panel/node_modules/@types/xterm/index"' has no exported member 'Xterm'.)
    at _checkDiagnostics (/var/home/vtolstov/devel/panel/node_modules/@ngtools/webpack/src/loader.js:116:15)
    at /var/home/vtolstov/devel/panel/node_modules/@ngtools/webpack/src/loader.js:141:17
 @ ./src/app/ttycon/ttycon.component.ts 11:0-50
 @ ./src/app/app.module.ts
 @ ./src/main.ts                                                                                                                                        
@ multi main
```

I have installed xterm and @types/xterm

**Comment by Tyriar** [comment]
I believe you want:

```js
import { Terminal } from 'xterm';
```

**Comment by vtolstov** [comment]
This is not worked.

**Comment by vtolstov** [comment]
May be @types/xterm wrong?

**Comment by Tyriar** [comment]
Actually try this one:

```js
import * as xterm from 'xterm'
```

This is how I import it in [vscode](https://github.com/Microsoft/vscode/blob/019ce0eb56e03d07d50148385e87f28eb1d00e9e/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L15):

```
import xterm = require('xterm');
```

**Comment by vtolstov** [comment]
import * as xterm from 'xterm'
Works

**Comment by vtolstov** [comment]
Thanks!

**Comment by Kaijun** [comment]
@Tyriar How about importing addons?

**Comment by Tyriar** [comment]
@Kaijun there is a [loadAddon](https://github.com/sourcelair/xterm.js/blob/1fbd3c8f654f088943e7cda0dbda5d86dc4bba1f/src/xterm.js#L631) function for node but it's not officially part oft he API yet so it may change across versions (pending #306).
