### ISSUE TITLE
Improve tmux support

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#456]
Originally reported https://github.com/Microsoft/vscode/issues/18182 from @elithrar:

> - VSCode Version: Version 1.8.1 (1.8.1)
> - OS Version: OS X 10.11.6
> 
> **Summary**: Highlighting text between tmux splits, and scrolling within tmux, does not work reliably when using the native terminal vs. (e.g.) iTerm2. Mouse support (clicking between splits) is also not supported.
> 
> Steps to Reproduce:
> 
> 1. Have tmux running inside your shell
> 2. Open a split (prefix + %)
> 3. Try to highlight text within a split with the mouse (ends up crossing splits, and putting them both into 'normal' mode)
> 4. Try to scroll within a split, or use PgUp, and it breaks the tmux history.
> 
> ![tmux-vscode](https://cloud.githubusercontent.com/assets/18544/21691713/920eccf8-d32e-11e6-8b10-c70a01ba80ee.gif)

**Comment by Tyriar** [comment]
@elithrar are you expecting the selection to only select text in one of the splits? `gnome-terminal` doesn't seem to do that.

Scrolling seems fine from what I can see, I don't typically use tmux though so you could give exact steps? This is what I was doing:

1. `tmux`
2. ^B %
3. Page up
4  Page down
5. Up arrow
6. Down arrow

**Comment by elithrar** [comment]
"As is" on iTerm2 (not in selection mode): just selecting w/ mouse within a split doesn't bleed across splits):

![tmux-selection-split](https://cloud.githubusercontent.com/assets/18544/21735633/30d33274-d420-11e6-8929-b162d7320415.gif)

---

prefix + pgup/pgdn within a split -> does not impact the other split.

![pgup](https://cloud.githubusercontent.com/assets/18544/21735695/ae7427ba-d420-11e6-9d68-b12a9f4b7f9e.gif)

Hope that's clear.

**Comment by Tyriar** [comment]
Thanks, that's super useful :smiley:

**Comment by elithrar** [comment]
Also @Tyriar - [Hyper](https://github.com/zeit/hyper) appears to handle this as expected, so there may be some approaches that xterm.js can look to emulate.

**Comment by whitecolor** [comment]
Also In windows (with Ubuntu bash shell) I experience different visual bugs after adding panels and resizing the window:
![image](https://cloud.githubusercontent.com/assets/736697/21748370/b527f4a2-d5a5-11e6-9f25-57a6c34f52e2.png)

![image](https://cloud.githubusercontent.com/assets/736697/21748375/d291b3b6-d5a5-11e6-8e1f-bf76ed4fb70e.png)

`tmux` reacts badly on window resize events, and doesn't react on on minimize/maximize window and going to full-screen, resizing terminal panel.

**Comment by leonfs** [comment]
I think running tmux within vscode termina;, I think it's a great way to enhance the terminal experience within VS Code but I also found the issues mentioned above. I'm happy to help to fix those issues.

**Comment by Tyriar** [comment]
@leonfs I'm curious how iterm2 does the split. If you have ideas on how they determine when the buffer should be split that would be good. If the terminal does get told to split its buffer somehow like this, actualy doing it would probably be non-trivial.

I also couldn't repro the page up/down thing also.

**Comment by whitecolor** [comment]
btw why VS code doesn't take ala VIM's approach to splited winodws, where any window could be filled with any content needed, for example terminal could be placed in any window, then need in terminal multiplexers would be much less.

**Comment by Tyriar** [comment]
@whitecolor the terminal in VS Code is contained within a panel which right now must be attached to the bottom and there can only be one. The main reason I'm not particularly for this is because the terminal keybindings/commands need to be reworked and would be a lot less consistent (what does it mean to toggle the terminal). While putting them in editors may seem simpler to some power users, I don't think it would benefit the wider user base.

We need to wait for panel position configurability https://github.com/Microsoft/vscode/issues/2806 and terminal splitting https://github.com/Microsoft/vscode/issues/7504 for movement on this sort of thing.

**Comment by mofux** [comment]
I wonder if this is related to the following problem 🤔

**xterm.js**
HTML content is selected, no matter if the app supports mouse integration
![xterm](https://cloud.githubusercontent.com/assets/2785983/22598378/96e14cee-ea33-11e6-89a7-2338a6b27165.gif)

**hyper/hterm**
hterm seems to disable HTML content selection if the app supports mouse integration
![hyper](https://cloud.githubusercontent.com/assets/2785983/22598508/f26ec9ba-ea33-11e6-9e07-374a2c8e2164.gif)

Steps to reproduce:

- open a file in vim `vim file.txt`
- try to select some text, you will get the html selection in both, hyper and xterm
- type `:set mouse=a` to enable mouse support
- try to select again, hyper will disable the html selection, xterm will still do it

**Comment by Tyriar** [comment]
Very likely that's the reason.

**Comment by parisk** [comment]
If this is true, I am curious if we could hack the clipboard mechanism even more in order to let the user copy what is selected in the back-end terminal.

**Comment by Tyriar** [comment]
This is related to, but not necessarily blocked by https://github.com/sourcelair/xterm.js/issues/207

**Comment by Tyriar** [comment]
Fixed in https://github.com/sourcelair/xterm.js/pull/670
