### ISSUE TITLE
Set up a test suite

### ISSUE THREAD

**Issue by parisk** [sourcelair/xterm.js#46]
xterm.js should be well tested in order to ensure that new releases and add-ons do not break any functionality introduced before.

## Candidate libraries
- https://github.com/facebook/jest
- http://mochajs.org/#getting-started
- https://github.com/avajs/ava
- https://jasmine.github.io/

**Comment by Tyriar** [comment]
I'm a fan of [ava](https://github.com/avajs/ava) ([example test](https://github.com/gwtw/js-fibonacci-heap/blob/master/test/fibonacci-heap-decrease-key-test.js)), it's pretty easy to setup coveralls to get code coverage as well ([example](https://github.com/gwtw/js-fibonacci-heap)).

Setting up a framework asap would be better than later as tests could be included with the bug fix commits that are made to prevent regressions.

**Comment by parisk** [comment]
I was investigating several testing solutions the last days and I think the best one would be going with [mocha](http://mochajs.org/). Seems quite established and straightforward.

Thanks a lot for submitting #104 though, but my main issues with ava are that it is not stable yet and that it has more futuristic syntax, which might feel cool for several people (me included), but I prefer going with something more down to earth.

**Comment by Tyriar** [comment]
No worries, it only took 5 minutes to put together :)
