### ISSUE TITLE
Better support for unicode characters

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#467]
Apparently the characters that `vtop` outputs are not supported currently by xterm.js (whereas they are in hterm. We should support them!

https://github.com/MrRio/vtop

Additional context: https://github.com/zeit/hyper/issues/1275#issuecomment-271679999

**Comment by Tyriar** [comment]
hyper:

![image](https://cloud.githubusercontent.com/assets/2193314/21822761/6d84a2d8-d72d-11e6-829b-248190b11cc0.png)

xterm.js:

![image](https://cloud.githubusercontent.com/assets/2193314/21822747/5e49b09c-d72d-11e6-9b7d-b89c9751e0b8.png)

**Comment by Tyriar** [comment]
The glyphs (eg. `⣿`) are not monospace, Hyper appears to have explicitly sized spans for every character which would be a performance hit, at least from the way we're doing it. If we want to support these we would want to keep some object pooling (as in https://github.com/sourcelair/xterm.js/pull/450) and/or grid system to reuse the spans.

**Comment by Tyriar** [comment]
I believe our current char width code is reasonably accurate right now (though could be improved), it's just the explicit width thing we would need to look into. As well as its performance if this is the direction we go, but that could be deferred.

**Comment by Tyriar** [comment]
It's pretty easy to do this as a modification on the https://github.com/sourcelair/xterm.js/pull/450 PR

![image](https://cloud.githubusercontent.com/assets/2193314/21828754/1f527e0e-d747-11e6-9d9f-420a6bb4ca79.png)

@rauchg was there anything another than the braille characters I need to test?

**Comment by jerch** [comment]
@Tyriar performance wise it might be best to go with on-the-fly glyph measuring as they are used for the first time.

To reduce memory consumption and runtime penalty one could use three bitfields with the codepoint as index:
- first one to indicate a glyph was already measured - no remeasuring needed
- second one to indicate, if explicit styling with a span around the glyph is needed; ASCII chars and most of the other lower chars will not need any special styling as they tend to have the intended width
- third one of half (0) and full (1) width explicit style rule (lookup only needed if 2nd bitfield entry was true for a particular char)

This would introduce at least 2 bitfield lookups for *every char* and a third one for chars that need special styling (bitfield lookups are quite cheap though). The latter will also raise the painting penalty since they will insert more spans to the DOM which is likely to have a noticeable impact.

**Comment by mofux** [comment]
@Tyriar xterm.js currently has another problem related to this. Emojis and other unicode characters are inserted with their actual width, which causes the line to grow bigger than it should (the cursor leaves the visible area of the screen without causing a line break). As far as I remember, hyper's hterm modification measures the width of every character, and if it violates the standard monospace width, it puts a span around it that sets the width accordingly. You can validate this by copying this: 😊

Just insert many of them to the terminal, and you will notice that the line will not break where it is supposed to.

**Comment by Tyriar** [comment]
Yeah I noticed the hyper version was using `runes` to do some magic, I'll have to test it out.

**Comment by Tyriar** [comment]
Moving the emoji-specific discussion to https://github.com/sourcelair/xterm.js/issues/469, this issue will handle enforcing the character size.

**Comment by rauchg** [comment]
@tyriar I think that app covers a lot. @mrrio is there anything else that comes to mind?

**Comment by rauchg** [comment]
Also +1 to what @mofux says. Emojis basically have to "overflow" the fixed-width span (which is also a bug we have in hterm, the overflow is hidden). If you type two emojis next to each other in vim, you should seem them overlapping, not extending the total row's width.

**Comment by Tyriar** [comment]
@rauchg emojis overflow even with a double width cell?

**Comment by rauchg** [comment]
Notice in Terminal.app how the brush emoji is overlapping the caret:
![image](https://cloud.githubusercontent.com/assets/13041/21863717/6736e226-d7f3-11e6-9394-3238882ec39e.png)

Right now in Hyper we hide the overflow so the emoji looks cut

**Comment by Tyriar** [comment]
Same thing on `gnome-terminal`, do you see any reason why these should not be considered wide characters though? 

![image](https://cloud.githubusercontent.com/assets/2193314/21864011/97068b18-d7f4-11e6-946a-48e2899e1292.png)

**Comment by rauchg** [comment]
Some info http://denisbider.blogspot.com/2015/09/when-monospace-fonts-arent-unicode.html

**Comment by rauchg** [comment]
While it doesn't specifically mention emoji, a [HN comment does](https://news.ycombinator.com/item?id=10206656). I guess emoji are simply not double width according to the UTF8 spec?

**Comment by Tyriar** [comment]
Ah, the Hyper behavior is a little weird as you say. It appears to be a little different to your screenshot for me though. The string `😛😛😛abc` gives the following:

### hyper v1.1.0 (Linux)

The cursor gives an allowance for a double width character but the characters rendered and only take up single character width:

![image](https://cloud.githubusercontent.com/assets/2193314/21867049/622ce7d6-d801-11e6-8cfc-a4a885bdb736.png)

Hovering the first 😛:

![image](https://cloud.githubusercontent.com/assets/2193314/21867135/b27799de-d801-11e6-81b8-7f2762068886.png)

### xterm.js (master)

![image](https://cloud.githubusercontent.com/assets/2193314/21867268/4cc732b0-d802-11e6-8c52-2f3a9fd38ce9.png)

Hovering the first 😛:

![image](https://cloud.githubusercontent.com/assets/2193314/21867279/572caf28-d802-11e6-97dd-980a551f3a99.png)

### gnome-terminal

![image](https://cloud.githubusercontent.com/assets/2193314/21867080/7e77ad9a-d801-11e6-8337-15f5ed7a85c6.png)

Hovering the first 😛:

![image](https://cloud.githubusercontent.com/assets/2193314/21867150/c4b24c02-d801-11e6-9c3b-ce73551f4f48.png)

**Comment by Tyriar** [comment]
I'm not so sure xterm.js needs more work in this regard except for support for the Mac IME? Making them double width seems like it would be the wrong decision as all other terminal emulators seem to treat them as single width.

**Comment by rauchg** [comment]
What I included was the Terminal.js behavior. We still have some fixes to make for the actual rendering of emojis. What I mentioned to you that was missing from xterm.js was the actual emoji popover:

![image](https://cloud.githubusercontent.com/assets/13041/21867916/30624238-d805-11e6-8931-e43564b5b589.png)

This atm doesn't work on xterm.js (renders detached, and clicking on an emoji doesn't include it)

**Comment by Tyriar** [comment]
@Displee did you test if it happens off the master branch? If so please create a new issue, this one is ancient and almost certainly not the problem you're seeing.
