### ISSUE TITLE
text-selection is lost when data is written outside of the viewport

### ISSUE THREAD

**Issue by foot** [sourcelair/xterm.js#468]
This is sort of a sub-case of #318 that feels like it could be an easier fix. 

Perhaps we could avoid redrawing the terminal if the updated lines fall outside the current viewport. I'm not sure if this would be an easy fix so please close this issue if time would be better spent pursuing a proper fix for #318 etc.

Big use case here is scrolling back through `tail -f`'d logs and trying to copy and paste them.

## Details
- Browser and browser version: Chrome Version 55.0.2883.95 (64-bit)
- OS version: OSX 10.11.6 (15G1108)
- xterm.js version: 2.2.3

### Steps to reproduce

1. `while true; do echo 1; sleep 1; done`
2. Wait for echos to hit the bottom of the term. 
3. Scroll back up, so that terminal appears fairly static (new echos are coming in below the last visible line).
3. Try and select text - selection is lost on next echo

Cheers!

**Comment by Tyriar** [comment]
Great idea @foot! Should be an easy fix and a great optimization for when you're looking at scrollback. I mention something similar in the linkify proposal https://github.com/sourcelair/xterm.js/issues/455 where I want us to shift rows up instead of redrawing the entire viewport when there is a new row. I'll keep this open to make sure this case is handled :smiley:

**Comment by SimonHui931208** [comment]
When can this problem be solved?I had tried to sovle it by adding other MouseEvents in my local codes. Firstly, I add the actual row number on each div,which is in the function '_refresh' that in the file of Renderer.ts,as follows:
>this._terminal.children[y].setAttribute("row", row);
>this._terminal.children[y].innerHTML = out;

Then I use the API document.caretRangeFromPoint to get the Range Informations when mousedown and mouseup. Then, the Terminal.lines._array had cached will to be used to select the actual Range which user chooses.Finally,window.getSelection.addRange(Range).

Howerver, it is so difficult.The selection will disappear when I user the scrollDisp(1).    :(

**Comment by Tyriar** [comment]
@SimonHui931208 selection is going to be completely rewritten soon in https://github.com/sourcelair/xterm.js/issues/207 which should fix this by managing what is selected ourselves, rather than trying to bend standard web selection to our will.

**Comment by Tyriar** [comment]
Fixed in https://github.com/sourcelair/xterm.js/pull/670
