### ISSUE TITLE
Resizes and refreshes can apparently be interleaved

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#473]
I believe this is the root cause for the crash in https://github.com/Microsoft/vscode/issues/18415

Adding a couple of null checks seems to fix this issue.

**Comment by parisk** [comment]
Should we investigate why resizes and refreshes get interleaved and fix the root cause?

Or this is inevitable based on the current logic?

**Comment by Tyriar** [comment]
I don't think it's worth the effort right now, putting in these checks avoids all crashes and I've seen crashed caused by this same code before so we should have these checks regardless. Speaking of which, I'll close off https://github.com/sourcelair/xterm.js/issues/385
