### ISSUE TITLE
Terminal is not defined

### ISSUE THREAD

**Issue by JeromeVi** [sourcelair/xterm.js#483]
I want to add your terminal in my app so I import the JS like this this 
`    <script src="js/xterm.js" type="text/javascript"></script>` 
and it's imported if I check in the dev terminal.

Then in want to add the terminal like you did in your example:
```
<div id="terminal"></div>
             <script>
               var term = new Terminal();
               term.open(document.getElementById('#terminal'));
               term.write('Hello from \033[1;3;31mxterm.js\033[0m $ ')
             </script>
```

But I got the error `Terminal is not defined` on the line `var term = new Terminal();`

## Details
- Browser and browser version:  Chrome  55.0.2883.95
- OS version: OS X El Capitan 10.11.6
- xterm.js version: the one of the 16th January 2017

**Comment by parisk** [comment]
Hi @JeromeVi, I guess that xterm.js is not an officially built bundle.

How did you install and import xterm.js? Take a look at the following articles, which might be helpful:

- http://xtermjs.org/docs/guides/download/
- http://xtermjs.org/docs/guides/import/

**Comment by JeromeVi** [comment]
So I got no error with the install of xterm.js using `meteor npm install xterm` then I import it by adding `<script src="js/xterm.js" type="text/javascript"></script>` at the bottom of my main.html page

**Comment by parisk** [comment]
How is `js/xterm.js` produced? You have to include the built file shipped with the repository in `dist/xterm.js`.

**Comment by JeromeVi** [comment]
I did a clone of your repo, then I moved /dist/xterm.js into my app folder /public/js/xterm.js

And with Meteor we don't need to put the /public in path that's the reason why I don't have it

**Comment by JeromeVi** [comment]
I'm still fighting against this error.

**Comment by JeromeVi** [comment]
Now I have `TypeError: Terminal is not a constructor
`

**Comment by JeromeVi** [comment]
Ok now after all these steps:
 1) remove the <script>
 2) add the xterm.js in /client/compatibility
 3) put ```
var term = new Terminal();
    console.log("term:  " + term);
    term.open(document.getElementById('#terminal'));
    term.write('Hello from \033[1;3;31mxterm.js\033[0m $ ');
``` in my template.onCreated function

I can display that:
<img width="299" alt="capture d ecran 2017-01-16 a 12 54 16" src="https://cloud.githubusercontent.com/assets/22610050/21982075/e9128d90-dbea-11e6-9bd8-6654d6b459d0.png">

**Comment by JeromeVi** [comment]
<img width="299" alt="capture d ecran 2017-01-16 a 12 54 16" src="https://cloud.githubusercontent.com/assets/22610050/21982080/f16f64fe-dbea-11e6-979d-9156f237e097.png">

**Comment by JeromeVi** [comment]
And now I have : 
<img width="595" alt="capture d ecran 2017-01-16 a 12 59 24" src="https://cloud.githubusercontent.com/assets/22610050/21982234/a1b734d6-dbeb-11e6-97e5-fd09ad2153a6.png">

But I don't understand why it's full page, it should be fit into the `<div id="terminal"></div>`

**Comment by Tyriar** [comment]
> I did a clone of your repo, then I moved /dist/xterm.js into my app folder /public/js/xterm.js

You should probably install via `npm` or `bower`, I don't think `dist/` is up to date on `master`.

**Comment by JeromeVi** [comment]
I did it and it worked +/- as you can see, now I can't fit the terminal despite I have imported fit.js..

**Comment by Tyriar** [comment]
For web clients you're probably going to want the bower build as all the JS files are concatenated. More info: http://xtermjs.org/docs/guides/import/ https://github.com/sourcelair/xterm.js#getting-started

(Disclaimer: I've never used meteor nor do I know what the `meteor` command does)

**Comment by JeromeVi** [comment]
The file fit.js is imported in my client and I can see the file on the dev console. I think you are able to help me without knowing Meteor because it doesn't change a lot of things :)

**Comment by Tyriar** [comment]
I think installing via bower and pulling in dist/xterm.js as in https://github.com/sourcelair/xterm.js#getting-started will probably help you

**Comment by JeromeVi** [comment]
Ok I have installed it but can you just tell me if I'm wrong : 
The script fit.js is loaded at the beginning of the app, then the terminal appear only when I click on a button ! So I got this error : 
```
fit.js:51 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at fit.js:51
    at fit.js:30
    at fit.js:32
```

It's because I load fit.js before the terminal is displayed on the page ?

**Comment by Tyriar** [comment]
If you're using the right build under a browser environment (with no module system),  dist/xterm.js.js creates window.Terminal.

**Comment by parisk** [comment]
@JeromeVi does meteor use any kind of "module system" for it's front-end assets (e.g. RequireJS, Browserify/CommonJS etc.)?

*(Please open the browser console, type `console.log(require)` and send back a screenshot of the result.)*

I am pretty sure the issue lies somewhere there, because:

- The xterm demo uses a plain browser env and loads both xterm and the fit addon without issues
- SourceLair uses require.js and loads both xterm and the fit addon without issues
- VS Code uses Node's require and loads xterm (not sure about fit) and works

**Comment by Tyriar** [comment]
VS Code has it's own fit logic, no addons used there right now, I imagine `loadAddon` would work though.
