### ISSUE TITLE
Option for configurable tab width?

### ISSUE THREAD

**Issue by vincentwoo** [sourcelair/xterm.js#488]
`xterm.js` inherits from `term.js` the [default tab width of 8 characters](https://github.com/sourcelair/xterm.js/blob/ed13218f9098a997283d996e7570d5cdb24ed87f/src/xterm.js#L3146):

```js
for (; i < this.cols; i += 8) {
  this.tabs[i] = true;
}
```

I think it would be very useful, especially for space-constrained web applications, to be able to set this width to a lower setting.

**Comment by Tyriar** [comment]
This seems like something that we probably need to align with xterm, and there doesn't seem to be a nice way to configure it for that from a cursory search.

**Comment by vincentwoo** [comment]
Is this project meant to be a strict interpretation of real xterm? I really did not get that vibe from the way you self-describe in the README and that other issue I opened.

**Comment by Tyriar** [comment]
Not super strict, my main concern is applications relying on 8 being hard coded.

**Comment by parisk** [comment]
I agree with @Tyriar, especially because the tab has a stricter meaning in terminals.

Could this mess up with programs emitting "tabular" output?

Also does any terminal application provide this kind of customization? Terminal.app in macOS does not.

**Comment by Tyriar** [comment]
Disclaimer: I'm by no means an authority on the matter, I'm not sure if anything I use even uses tab stops :smile:

**Comment by vincentwoo** [comment]
It's certainly possible to change tabwidth from within a normal TTY: https://linux.die.net/man/1/tabs

This is more difficult on the web unless you want to have terminals secretly run the specific commands emitted by a program like `tabs`. I think saner is to configure default tab stop width.

Any program that does any kind of tricky spaced display almost certainly does not depend on hard tabs.

**Comment by Tyriar** [comment]
I think you've convinced me :smiley:

**Comment by parisk** [comment]
Yep me too. I have to admit that I was not aware of `tabs` or how programs display tabular UIs in the terminal.

I think that a `tabStopWidth` (no need for `initial` I think?) option, defaulting to 8, would be 👍 . What do you think @vincentwoo?

**Comment by vincentwoo** [comment]
I am fine with whatever nomenclature you deem appropriate!

**Comment by parisk** [comment]
@vincentwoo please take a look at #497 and put your comments there about the implementation.
