### ISSUE TITLE
not only just one person feel your doc is very hard to use 

### ISSUE THREAD

**Issue by birenjack** [sourcelair/xterm.js#4908]
## Details
- Browser and browser version: 
- OS version: 
- xterm.js version: 

### Steps to reproduce

1. 
2. 
![image](https://github.com/xtermjs/xterm.js/assets/126436313/99b1151b-0d02-4089-9f3d-af6d8f338003)

**Comment by Tyriar** [comment]
@birenjack a _screenshot_ of a foreign language really isn't useful. At least if it were text we could machine translate it to see if it's useful.
