### ISSUE TITLE
Support git-bash on Windows

### ISSUE THREAD

**Issue by ficristo** [sourcelair/xterm.js#503]
Instead of seeing the terminal embedded in the browser it open a new git-bash window.

_I'm using the MINGW64 version of git-bash_

## Details
- Browser and browser version: Firefox 50.1.0
- OS version: Windows
- xterm.js version: 2.2.3

### Steps to reproduce

1. In the demo I've substituted `cmd.exe` with `C:\\Program Files\\Git\\git-bash.exe`
2. run `npm start`

**Comment by Tyriar** [comment]
Try setting it to `C:\Program Files\Git\\bin\bash.exe`

It will not work that great until `node-pty` is upgraded to `0.6.2`.

**Comment by ficristo** [comment]
Actually I'm working on a project which already use node-pty 0.6.2 and indeed, after I've changed the path, it worked. (I've used the demo to verify my issue)
Thank you!

**Comment by parisk** [comment]
Happy that it worked out! Let's keep this open until we update `node-pty`.

**Comment by Tyriar** [comment]
Done some time ago :smiley:
