### ISSUE TITLE
Paste doesn't work on oh-my-zsh under macOS

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#511]
This appears to be a recent regression. Pasting behaves really strangely.

See https://github.com/Microsoft/vscode/issues/18833

**Comment by Tyriar** [comment]
A bisect shows it's caused by https://github.com/sourcelair/xterm.js/pull/447 (fc528f6c0ce969c457353bacce63af14ee130d0f)

**Comment by Tyriar** [comment]
It only happens when pasting strings larger than 5 characters.

**Comment by Tyriar** [comment]
It's happening because `^S` is the zsh shortcut for `fwd-i-search` but we're sending that to the terminal as `XOFF`.

**Comment by Tyriar** [comment]
Additionally, zsh appears to disable flow control by default which causes problems.

**Comment by Tyriar** [comment]
^S works in Terminal.app with `zsh` to pause output so it looks like we're doing something wrong.

**Comment by parisk** [comment]
There's a chance that Terminal.app utilizes system calls to achieve this, so it might never pass from `zsh`.

What I was thought is that we could "test" the usage of `^S/^Q` in the terminal, so we could send an identifying `^S` at some point and if we can somehow detect that it worked, then we can continue using this mechanism, or else we switch it of.

Does this make sense?

**Comment by Tyriar** [comment]
After looking at it more I think zsh does respond to ^S but only when a program is running, if not it will start a `fwd-i-search`. I think the best course of action it probably to disable to `XOFF` catch up mechanism within x ms of a keypress (or some other event).

I believe this behavior isn't shown in other terminals due to the longer round trip we have to make when send an `XOFF` signal (node -> websocket/node native -> pty).

This might be easier if we know if the terminal is interactive, is there a good way of determining that? Checking the cursor visibility might work?

**Comment by parisk** [comment]
Not sure if it is a great idea. Sounds quite crude assuming that the terminal is interactive only if it has a cursor.

What if we just expose an option for this and let this up to the consumer application to determine it's usage?

I would propose `false` as the default.

**Comment by Tyriar** [comment]
It would seldom be turned on if it was false by default, this feature keeps ctrl+c (and other signals) responsive which makes things feel a lot better. We only need to workaround this specific case when people use oh-my-zsh on OSX.

**Comment by Tyriar** [comment]
Here's what I've come up with after looking into this.

**Only use flow control (XON/XOFF) when the cursor is hidden**

This won't work, at least not in general as many programs don't hide the cursor.

**Timeout on keydown/press**

Ensuring XOFF doesn't fire shortly after keydown/press wouldn't work because paste is handled by the `paste` event.

**Timeout on paste**

This would fix the immediate problem but it would still potentially lead to flaky behavior. All that needs to happen to trigger an XOFF is at least 5 pieces of data being in the write queue. I can see this potentially firing when a command finishes but the renderer is still catching up.

**Documenting how to work around the issue**

The issue can be worked around by running `bindkey -r ^S ^Q` to unbind oh-my-zsh's keys. This would lead to a crappy experience due to required configuration and loss of user's keybindings.

**New option, disabled by default + documentation**

This is the direction I think we should go after finding the alternatives are not adequate for a good out of the box experience for everyone. Having an option which is disabled by default will allow xterm.js consumers to choose how best to approach the use of flow control and whether to bother at all. I plan on introducing a new `flowControl` setting to vscode with the default being `false` if `$SHELL` is `zsh` and `~/.oh-my-zsh` exists, otherwise `true`.
