### ISSUE TITLE
Setting scrollback to infinite?

### ISSUE THREAD

**Issue by aashidham** [sourcelair/xterm.js#518]
How is it possible to set the scrollback to be infinite? Basically, I want the CircularList to never overwrite old data and increase to the memory limits of the browser.

**Comment by Tyriar** [comment]
You can always set it to a really large number. I don't think we could increase to the memory limits of the browser, nor would it be good for stability.

I don't think we should support an explicit infinite due to the expected low usage, stability problems and easy workaround.

**Comment by aashidham** [comment]
In that case, is there a variable that is set when data begins to get truncated?

**Comment by Tyriar** [comment]
```js
var term = new Terminal({ scrollback: 9999999 });
```

or

```js
term.setOption('scrollback', 9999999);
```
