### ISSUE TITLE
Xterm steel electron accelerator Command

### ISSUE THREAD

**Issue by ppot** [sourcelair/xterm.js#527]
Xterm seem to be steeling electron accelerator
Keys like:
`cmd+Alt+left`
`cmd+Alt+right`
`cmd+Alt+up`
`cmd+Alt+down`

Might be related to #487
## Details
- Browser and browser version: (Electron)
- OS version: OSX
- xterm.js version:  lastest master e0639e1b62dbbb0a110dcc36ab8c668f7c2af1c3

**Comment by Tyriar** [comment]
You need to prevent the key events from being passed to xterm by attaching a keydown handler http://xtermjs.org/docs/api/Terminal/#attachcustomkeydownhandlercustomkeydownhandler

xterm.js will consume any key events that a terminal app may find useful.
