### ISSUE TITLE
zprezto plugin puts cursor in wrong position

### ISSUE THREAD

**Issue by tleunen** [sourcelair/xterm.js#528]
Coming from https://github.com/Microsoft/vscode/issues/19901

When using my zsh with the git plugin from zprezto, I'm getting a weird issue with the cursor (See the screenshots in the other ticket).

I have a basic zprezto installation, here's my config: https://gist.github.com/tleunen/f18eb18c3ed9249669c97ca836cc60a8
And my theme is this one https://gist.github.com/Veraticus/1b30a6b6cbe8dae57e9f

**Comment by Tyriar** [comment]
I would guess it's related to some escape sequence used by the git status info not behaving.

@tleunen do you know what the icons are meant to mean? That will help track down the issue.

**Comment by tleunen** [comment]
The icons specify if there are changes, additions, removal, ... in the current state.

But I just tested again with the recent new version 1.10.1 and the issue is gone. :)
