### ISSUE TITLE
npm install xterm

### ISSUE THREAD

**Issue by czb** [sourcelair/xterm.js#537]
When I do

    npm install xterm --save
    npm install
    npm start

I get `Error: Cannot find module '.....\xterm\demo\app'`

when I download the repo manually and do

    npm install
    npm start

Everything works just fine.

Is that an expected behaviour?

**Comment by Tyriar** [comment]
Yes it is expected, installing via npm will fetch the library, not the demo. You will need to copy the demo to your project that uses xterm.js as a dependency to get it working.
