### ISSUE TITLE
Terminal background initially has wrong size

### ISSUE THREAD

**Issue by takluyver** [sourcelair/xterm.js#539]
We've started seeing this since we upgraded xterm from 2.2.3 to 2.3.1 in Jupyter:

![terminal problem](https://cloud.githubusercontent.com/assets/327925/22826050/48b9f0f2-ef88-11e6-8fe0-9a09f861f5f7.png)

We're passing in `rows` and `cols` options when we instantiate `Terminal`, and I've checked that `rows` is being passed a sensible value, but the background (`xterm-viewport` div) is not getting the correct height. As soon as resizing the window triggers the terminal to resize, it corrects itself and displays correctly.

Apologies if we're doing something stupid here, but we're currently stumped as to what it could be.

## Details
- Browser and browser version: Reproduced on Firefox 51 and Chromium.
- OS version: Ubuntu 16.04
- xterm.js version: 2.3.1

Cross-linking jupyter/notebook#2172

**Comment by Tyriar** [comment]
I can repro this if I disable calls to `resize` in the demo, it's caused by optimizations to the system that measures character width/height size (`CharMeasure`).

**Comment by takluyver** [comment]
Thanks, upgrading to 2.3.2 does indeed solve the issue we saw.
