### ISSUE TITLE
xterm.js disable "Autowrap Mode" after "Soft Terminal reset".

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [sourcelair/xterm.js#540]
When xterm.js receive "Soft Terminal Reset" command function "[**\[!p**](http://www.vt100.net/docs/vt510-rm/DECSTR.html)" from server side, than xterm.js disable Autowrap Mode([DECAWM](http://www.vt100.net/docs/vt510-rm/DECAWM.html)), but by default XTERM has activated DECAWM. This bug is not reproducible on the demo(I tested on Linux), because demo server side  doesn't send this command function for reset terminal.
I investigated reason this bug: if was changed default "wraparoundMode" value for XTERM: https://github.com/sourcelair/xterm.js/commit/4afa08da8d7bd5a91133dc609813e8b415c16633#diff-d4f745d6f29faa0617f2e02bb95f0c44R255  then we should change this default value for "soft reset" XTERM too: https://github.com/sourcelair/xterm.js/blob/4afa08da8d7bd5a91133dc609813e8b415c16633/src/xterm.js#L4304

## Details
- Browser and browser version: Google Chrome 53.0.2785.143 (64-bit)
- OS version: Fedora 24, Ubuntu 16.04 
- xterm.js: 2.2.3 - 3.0.1.
- server side: https://github.com/eclipse/che/tree/master/agents/exec/src/term

### Steps to reproduce
1. Run xterm.js with connected to the websocket terminal;
2. Type command "reset" to reset terminal;
3. Type command longer then terminal row.
Actual result: Autowrap Mode dissable.
Expected result: Autowrap Mode should be enabled for XTERM after reset terminal.

**Comment by parisk** [comment]
Closed in #541.
