### ISSUE TITLE
how config or set the charset

### ISSUE THREAD

**Issue by hktalent** [sourcelair/xterm.js#547]
1、server
linux
china utf-8，gbk
2、browser
safari

[root@appserver ~]# df -h
ÎÄ¼þÏµÍ³ ÈÝÁ¿ ÒÑÓÃ ¿ÉÓÃ ÒÑÓÃ%% ¹ÒÔØµã
/dev/mapper/VolGroup-lv_root
507G 153G 328G 32% /
tmpfs 16G 1.2M 16G 1% /dev/shm
/dev/xvda1 485M 52M 408M 12% /boot
192.168.10.123:/MyWork
985G 223G 712G 24% /MyWork

the “¹ÒÔØµã” cannot display，is china word

**Comment by Tyriar** [comment]
Can you please fill out the issue template? We need to know operating system, xterm.js version, browser/environment version.

**Comment by tsl0922** [comment]
UTF-8 encoded byte string from pty need to be decoded before sending to xterm.js, this is what I did for ttyd : https://github.com/tsl0922/ttyd/blob/master/html/js/utf8.js

@Tyriar The Integrated Terminal of VSCode has this issue too. You can test this with the command: `touch Intel®`, the created file's name is `Intel%C2`, not correct.

**Comment by Tyriar** [comment]
Thanks @tsl0922!

**Comment by ioquatix** [comment]
Why don't you make this an add-on?

**Comment by ioquatix** [comment]
Actually, after testing this, I found it was an issue when `LANG` was not set, and I didn't need this after all.

**Comment by zhanyouwei** [comment]
@tsl0922 404?

**Comment by tsl0922** [comment]
I’m using TextDecoder now, so that file is not needed anymore.

Jason <notifications@github.com>于2018年5月4日 周五17:42写道：

**Comment by tsl0922** [comment]
@zhanyouwei https://github.com/tsl0922/ttyd/blob/1.3.3/html/js/utf8.js
