### ISSUE TITLE
Resizing the terminal removes lines

### ISSUE THREAD

**Issue by joerick** [sourcelair/xterm.js#55]
Hello!

I'm using xterm in a new Electron-based IDE we're developing for [Tingbot](http://github.com/tingbot). Thanks for the library, it's proving to be super-useful.

I'm running up against some strange behaviour when resizing the terminal, which occurs more often than most terminals due to our window layout - the terminal is a panel at the bottom of the window that slides up and down

![](http://cl.ly/2B0z260O1v0N/Screen%20Recording%202016-05-19%20at%2011.02%20am.gif)

When resizing this panel we see unexpected behaviour from the terminal, when it's getting smaller, it removes lines from the top of the scrollback, and when getting bigger, it adds lines to the bottom - so it moves text off the screen if it's closed/opened.

I've had a look at the source and the problem seems to be around [xterm.js:2526](https://github.com/sourcelair/xterm.js/blob/master/src/xterm.js#L2526) - I think the terminal could just adjust its scroll position, rather than adding/removing rows.

I'd be happy to submit a pull request, if somebody could give me a pointer about how the scroll position is stored - I've seen two variables - `this.ydisp` and `this.ybase` - what do these do?

**Comment by parisk** [comment]
Hi @joerick, thanks for reporting!

Investigating this right now in order to reproduce. Possibly it got introduced after merging this PR: https://github.com/sourcelair/xterm.js/commit/685bc54bf297b094ec9f02b911f4396a56593a40.

**Comment by parisk** [comment]
Hi @joerick, could you please checkout the latest commit on xterm.js' master branch (cf9d2348a1c315f0c8d46000550e7bc91ac18121) and let me know if this is fixed?

This should not be the case after we merged #101.

Also, remember to resize the back-end pty manually every time you adjust the front-end terminal's dimensions.

**Comment by joerick** [comment]
Hey @parisk, just tried again. Still having a problem-

![](http://cl.ly/3i3c0I3t1U14/Screen%20Recording%202016-06-09%20at%2001.30%20pm.gif)

However, it's improved by the fact that the lines aren't being removed any more, so the logging data is still in the scrollback. Perhaps the solution is to only add new lines to the bottom of the terminal if the scrollback is too small to fill the screen?

**Comment by parisk** [comment]
Hi @joerick could you please checkout the latest version of master and try again? After merging #112 this should be fixed.

**Comment by joerick** [comment]
Confirmed - this is fixed! :)

![](http://cl.ly/1o2h2K3f3o1E/Screen%20Recording%202016-06-10%20at%2009.54%20am.gif)
