### ISSUE TITLE
buffer is truncated when resizing terminal rather than wrapping

### ISSUE THREAD

**Issue by AlmirKadric** [sourcelair/xterm.js#552]
I'm not sure if this is an intended behaviour, but when a terminal is resized, characters which exceed the terminal width are truncated and lost rather than wrapping.

## Details
- Browser and browser version: Electron
- OS version: All
- xterm.js version: 2.3.1

### Steps to reproduce

1. Create a terminal
2. Write characters to fit current column width
3. Resize terminal to be less than sentence character width, characters not wrapped, instead truncated
4. Resize terminal back to previous wider column width, characters lost not re-appearing

**Comment by Tyriar** [comment]
Duplicate https://github.com/sourcelair/xterm.js/issues/325
