### ISSUE TITLE
[Question] is it a documentation that list all methods ? 

### ISSUE THREAD

**Issue by JeromeVi** [sourcelair/xterm.js#560]
Hi,
I can't find a documentation who list the methods and actions that we can perform with `term`, but I'm sure one exists.

So could someone give me the link ?

**Comment by tsl0922** [comment]
http://xtermjs.org/docs/api/Terminal/

**Comment by JeromeVi** [comment]
Thank you ! I think i'm blind

**Comment by JeromeVi** [comment]
@tsl0922 is it me or there isn't a method to delete character ? (when we press "return" for example)
