### ISSUE TITLE
[Question/Request] How to delete a character when pressing "return" ?

### ISSUE THREAD

**Issue by JeromeVi** [sourcelair/xterm.js#561]
Hi,
I try to remove character when I press "return" but in [the Terminal doc](http://xtermjs.org/docs/api/Terminal/) I can't find any method to do that. So is this function available ? And if yes how to make it ?

**Comment by JeromeVi** [comment]
After reading your source code I have founded that writting `\b \b` delete chars so it's ok

**Comment by Displee** [comment]
I do have a question about this. I'm trying to delete a character at a certain index. It kind of works, but not as I expected. I expect the text to shift to the left when deleting a character.
But it just replaces the character with `\b \b`. Here's a gif:

https://i.imgur.com/svUmBVX.gif

Here's the code I'm using:

```
public backspace(): void {
        let text = this.text;
        if (text && text.length > 0) {
            this.terminal.write('\b \b');
            this.text = text.substr(0, this.cursorPosition - 1) + text.substr(this.cursorPosition);
            this.cursorPosition--;
        }
    }
```

Using xterm version:
https://cdnjs.cloudflare.com/ajax/libs/xterm/3.8.0/xterm.js

**Comment by privatenumber** [comment]
If you're keeping track of the entered `command`, you can write the remaining text along with `\b \b` to overwrite the rest of the line:

```ts
const cursor = xterm._core.buffer.x;
const CURSOR_DEL = '\b \b';
const CURSOR_LEFT = '\u001B[1D';

const remainingText = command.slice(cursor);
xterm.write(
	CURSOR_DEL
	+ remainingText
	+ ' ' // Clear last character (To offset the deleted character)
	+ CURSOR_LEFT.repeat(remainingText.length + 1) // Move cursor back
);

command = command.slice(0, cursor - 1) + remainingText;
```
