### ISSUE TITLE
How to use xterm in Angular2 typescript applications?

### ISSUE THREAD

**Issue by PiPiNaN** [sourcelair/xterm.js#568]
Hi, I need your help to use xterm in my angular2 application, in which xterm is intended to be terminal of docker container. 
In my try, I installed the @types/xterm, and write an angular component as follows:
import * as xterm from "xterm";
...

export class XtermComponent implements OnInit {
    public term: xterm;
    container: HTMLElement;

    ngOnInit() {
        this.term = new xterm();
        this.container = document.getElementById('terminal-container');
        this.term.open(this.container);

        this.term.writeln('Welcome to xterm.js');
        this.term.writeln('This is a local terminal emulation, without a real terminal in the back-end.');
        this.term.writeln('Type some keys and commands to play around.');
        this.term.writeln('');

        this.term.on('key', function (key, ev){
            this.term.write(key); //Error here, not found the 'write' property, this.term is not recognized correctly.
        });
    }
}

so how to handler the callback? or anyone can provide an example of xterm in angular2 app? Thanks.

**Comment by Tyriar** [comment]
@PiPiNaN In:

```js
    this.term.on('key', function (key, ev){
        this.term.write(key); //Error here, not found the 'write' property, this.term is not recognized correctly.
    });
```

The inner `this` refers to the function, now `XtermComponent`. This should work instead:

```js
    this.term.on('key', (key, ev) => {
        this.term.write(key);
    });
```
