### ISSUE TITLE
Inverse text styles are not applied correctly

### ISSUE THREAD

**Issue by petschekr** [sourcelair/xterm.js#57]
I'm using xterm.js in conjunction with [ssh2](https://github.com/mscdex/ssh2) to build a SSH client, which has been working quite well so far (thanks for the awesome library!). One issue that I have encountered though is that inverse text styles appear as normal text. For example, on nearly any terminal, running `nano` will show the nano editor with a white status bar across the top implemented using inverse styles. In xterm.js, these appear as normal text instead. This issue also appears when using the [colors.js](https://github.com/Marak/colors.js) library.

Peeking into the code, the problem seems to lie in the styles being applied by [`Terminal.prototype.refresh()`](https://github.com/sourcelair/xterm.js/blob/master/src/xterm.js#L1058). For inverse text, the classes applied to the surrounding `<span>` in each `div.xterm-rows` is `xterm-bg-color-257  xterm-color-256` neither of which are defined in `xterm.css` and aren't valid xterm-256 colors. The correct classes should be `xterm-bg-color-15  xterm-color-0` for a white background with black text.

For nano, the `data` variable that sets the inverse text in `Terminal.prototype.refresh()` is 2228992 (I'm not sure if that helps but that seems to be the value that causes `bg` and `fg` to evaluate to incorrect values).

**Comment by parisk** [comment]
Hi @petschekr thanks reporting. Taking a look at it right now.

**Comment by parisk** [comment]
Just opened a PR for this: #58.

@petschekr can you checkout the branch `issue/57` and let me know if it works fine for you?

**Comment by petschekr** [comment]
@parisk #58 fixes my issue completely. Thank you very much!

**Comment by petschekr** [comment]
@parisk I just realized that this issue originally stemmed from [this part of the term.js codebase](https://github.com/chjj/term.js/blob/master/src/term.js#L408) where the default background and foreground were set to 256 and 257 which was [removed in xterm.js](https://github.com/sourcelair/xterm.js/blob/master/src/xterm.js#L338). Thanks again for fixing this.

**Comment by parisk** [comment]
Yes, this seemed to be an edge case when inverting terminal text that has not explicitly set foreground and background colors.
