### ISSUE TITLE
this is a bug?

### ISSUE THREAD

**Issue by smalltimoo** [sourcelair/xterm.js#575]
## Details
- The number of characters is the same, why the width of the two lines are not the same
-

### datas

1. ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
2. ┠─────────────────────────────────────────────────────────┨

**Comment by parisk** [comment]
@smalltimoo I am not sure what you are talking about here. Please update your issue with all requested information and steps to reproduce, or else we are not able to help.

Closing this for now.
