### ISSUE TITLE
PR builds should not fail when code coverage is decreased

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#585]
It makes PRs confusing, look at https://github.com/sourcelair/xterm.js/pull/579 for an example with all the crosses, despite decreasing only 0.04%

**Comment by parisk** [comment]
I can see only one cross in the bottom. Is it that bad?

**Comment by Tyriar** [comment]
I think we can mark certain builds as important so they don't break the PR. That would lower the chance of accidentally merging something that breaks tests.

**Comment by Tyriar** [comment]
@parisk I think this can be configured in the coveralls settings https://github.com/lemurheavy/coveralls-public/issues/565#issuecomment-120924694 failing only on 1%+ or 2%+ would probably be best

**Comment by Tyriar** [comment]
Another reason this bugs me :smile: 

![image](https://cloud.githubusercontent.com/assets/2193314/23670266/09c9d2f2-031c-11e7-9328-694f5b3d4dc0.png)

**Comment by parisk** [comment]
I see! I put the threshold to 1% for now. If it is still annoying, I will increase it to 2%.
