### ISSUE TITLE
How to set terminal colors?

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#59]
I was looking into using xterm.js for vscode's integrated terminal but the colors seem to be gone after I swapped out [jeremyramin/term.js](https://github.com/jeremyramin/term.js).

![image](https://cloud.githubusercontent.com/assets/2193314/15687440/a01af774-2729-11e6-9c00-aed6160359ff.png)

Expected:

![image](https://cloud.githubusercontent.com/assets/2193314/15687457/c2730b9a-2729-11e6-9077-b3906c033ff5.png)

This is how I was setting the colors:

```ts
terminal.colors = [...]; // array of 16 string in format '#rrggbb'
terminal.refresh(0, terminal.rows);
```

**Comment by petschekr** [comment]
I believe xterm.js uses an external stylesheet instead of styles embedded into the JavaScript like term.js. Therefore you have to import [`xterm.css`](https://github.com/sourcelair/xterm.js/blob/master/src/xterm.css) in your HTML. If you want to change the default colors, the stylesheet makes it a lot easier to override certain color rules. Adding it also makes the `<textarea>` used for input disappear.

**Comment by Tyriar** [comment]
Thanks, that clears that up :)

**Comment by parisk** [comment]
Hi @Tyriar, @petschekr got it completely right; xterm.js depends on xterm.css for proper color rendering, in order to allow theming of the terminal.

I guess it would be helpful to document this in a more visible place though 😊 .

**Comment by zwhitchcox** [comment]
This does not allow you to set the background color of the terminal

**Comment by zwhitchcox** [comment]
I set the background terminal color with
```js
term._core.renderer.colorManager.colors.background = {
  css: "#fdf6e3",
  rgba: "rgb(253, 246, 227)",
}
```

**Comment by Tyriar** [comment]
@zwhitchcox the current way to do this:

```ts
const term = new Terminal({
  'theme', { background: '#fdf6e3' }
});

// or

term.setOption('theme', { background: '#fdf6e3' });
```

**Comment by sdegutis** [comment]
On a related note, are there any known themes out there or NPM packages containing themes?

**Comment by Tyriar** [comment]
@sdegutis not that I'm aware of

**Comment by sdegutis** [comment]
@Tyriar Thanks, I'll just check out the ones VS Code comes with.

**Comment by Zzy-OvO** [comment]
Have you solved it?

**Comment by Zzy-OvO** [comment]
Have you solved it?
What if I want to implement specific content using different colors?
