### ISSUE TITLE
Clicking / dragging scroll bar doesn't scroll 

### ISSUE THREAD

**Issue by aashidham** [sourcelair/xterm.js#590]
xterm.js pops open a scroll bar, but you can't click it / drag it anywhere. How do I fix this?

## Details
- Browser and browser version: Chrome 
- OS version: OSX 10.9.5

**Comment by aashidham** [comment]
ping?

**Comment by vincentwoo** [comment]
perhaps dupe of #512

**Comment by aashidham** [comment]
Was this ever resolved?

**Comment by parisk** [comment]
Scrollbar works great for me on the demo on Chrome 56.

Did this happen on the demo for you?

**Comment by Tyriar** [comment]
Yes this looks like a duplicate of https://github.com/sourcelair/xterm.js/issues/512
