### ISSUE TITLE
use xterm.js in angular2  --- Can't resolve 'xterm'  when new xterm() 

### ISSUE THREAD

**Issue by caihongyanChu** [sourcelair/xterm.js#593]
I installed the @types/xterm，then 
import * as xterm from "xterm";
...
export class TerminalComponent implements OnInit {
   public term: xterm;

  ngOnInit() {
        this.term = new xterm();     //"Can't resolve 'xterm' " erro show  when runing
   }
}

how to resolve?

**Comment by parisk** [comment]
Have you installed xterm.js with `npm install xterm`?

Also please take a look at the **Downloading** and **Importing** guides of xterm.js, which are known to still work:

- https://xtermjs.org/docs/guides/download/
- https://xtermjs.org/docs/guides/import/

Closing this as it is not a direct xterm.js.

**Comment by caihongyanChu** [comment]
I resolve it,thanks
