### ISSUE TITLE
Help providing the minify files

### ISSUE THREAD

**Issue by sufuf3** [sourcelair/xterm.js#602]
Hi @sourcelair ,
We are cdnjs team, we're going to host this library.
Could you please provide `xterm.min.js`, `xterm.min.css` and the minify files under `dist/addons`? 

If there is any suggestion, please let me know.
Thank you.

[cdnjs/cdnjs#10764](https://github.com/cdnjs/cdnjs/pull/10764)

**Comment by Tyriar** [comment]
@sufuf3 We actually plan to remove `dist/` all together as built (unminified) files are published to `npm` in `lib/` (see https://github.com/sourcelair/xterm.js/pull/420 for more context).

You could probably write a script pretty easily that clones the git repo at a release tag, runs `npm i && npm run build` and then minifies `./build/*` with your library of choice. FYI 2.4.0 is now the latest.

@parisk maybe we should add a minify gulp task and upload those assets to [releases](https://github.com/sourcelair/xterm.js/releases) for use cases like this and to enable quick download without a package manager?

**Comment by parisk** [comment]
Hi @sufuf3, thanks for offering to host the library 👍 .

As @Tyriar already said, we plan to remove the `dist/` directory, but what we plan to do is create an extra repository to keep these files (as described in #406).

Would it be OK for you if these files resided in https://github.com/xtermjs/dist (or something like that), instead of this directory?

If yes, I can move with setting this up immediately.

**Comment by parisk** [comment]
Another solution (as @Tyriar proposed) would be uploading an archive of all build artefacts in GitHub Releases.

Would this work as well?

**Comment by sufuf3** [comment]
Now, we will host this library from this GitHub repository and use minify tool by [uglify-js](https://www.npmjs.com/package/uglify-js).
When this library change to another repository, we will update the file structure and auto-update info.
Thank you very much.

**Comment by Tyriar** [comment]
I think we can close in favor of https://github.com/sourcelair/xterm.js/issues/406 then as you have a workaround, thanks for including in cdnjs!
