### ISSUE TITLE
terminal.send support

### ISSUE THREAD

**Issue by ficristo** [sourcelair/xterm.js#605]
I wanted to send a command to my terminal and after trying with `terminal.write` and `terminal.writeln` without success, I found the `send` command and worked: is it supported?
If so could be documented at https://xtermjs.org/docs/api/terminal/?

## Details
- Browser and browser version: 
- OS version: 
- xterm.js version: 2.4.0

### Steps to reproduce

1. `var eol = platform === "win" ? "\r\n" : "\n";`
2. `xterm.send("cd \"" + path + "\"" + eol);`

**Comment by Tyriar** [comment]
You want to send the command to your shell process that will send data to xterm.js. For example:

1. Tell cmd.exe to cd to a path
2. cmd.exe will tell xterm.js to print both the command and output.
