### ISSUE TITLE
Pasting in 日本語 adds an unexpected line break after 本 which puts the cursor off screen

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#61]
![image](https://cloud.githubusercontent.com/assets/2193314/15737962/d45ef9d8-285d-11e6-81d7-89b45348b529.png)

**Comment by parisk** [comment]
Hi @Tyriar thanks for reporting. Investigating right now.

**Comment by Tyriar** [comment]
I notice it seems to happen on the last CJK character in the pasted text, pasting "안녕하십니까?" results in:

```
안녕하십니
까?
```

The question mark is a regular ascii char.

**Comment by Tyriar** [comment]
I think this is related to https://github.com/sourcelair/xterm.js/issues/62. Because the extra space on the right is filled with `&nbsp;`, this causes unexpected characters to wrap so the `&nbsp;` line can fit.

**Comment by Tyriar** [comment]
`white-space: nowrap;` makes the problem go away but of course unexpected characters could then go off screen.

**Comment by parisk** [comment]
I hope I will be able to take a deeper look into double characters today.

**Comment by parisk** [comment]
This is caused because of #62. Closing this, in order to continue conversation over there.
