### ISSUE TITLE
Get current line text

### ISSUE THREAD

**Issue by jiayihu** [sourcelair/xterm.js#620]
How can I get the text of the current line (for example when `Enter` is pressed)? Of course I could keep track of it listening the `key` event but I'm thinking if there is a better solution.

Great work anyway! 🤘 

## Details
- xterm.js version: 2.4.0

**Comment by Tyriar** [comment]
No easy way to do this right now, and it wouldn't be a reliable method of pulling out the command that was run if that's what you're thinking for the following reasons:

- Different shells/users have different prompt formats
- Pressing enter doesn't necessarily mean the line is a command (think random enter presses, applications like vim, opening a " and typing, etc.)

I'm going to close this in favor of https://github.com/sourcelair/xterm.js/issues/576 which aims to extract more state from the shell.
