### ISSUE TITLE
Horizontally resizing will not reflow terminal until input is changed or arrow is pressed

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#63]
Original:

![image](https://cloud.githubusercontent.com/assets/2193314/15738153/d3c535c2-285e-11e6-9302-bdac0593840e.png)

Reduce width:

![image](https://cloud.githubusercontent.com/assets/2193314/15738165/df6f62d0-285e-11e6-8137-36ce5207f8b1.png)

Restore width:

![image](https://cloud.githubusercontent.com/assets/2193314/15738179/eed7fe30-285e-11e6-916a-41443e5cbda2.png)

Press left arrow:

![image](https://cloud.githubusercontent.com/assets/2193314/15738183/fa0478a6-285e-11e6-954c-5e76e71de49a.png)

Notice the first line is not restored at all.

**Comment by parisk** [comment]
This seems to be an issue of www.sourcelair.com and not the terminal itself. Resizing happens in the back-end and then implemented by the terminal, so it's not up to xterm.js when to resize, but up to the controlling app.

Closing this, but thanks a lot for reporting 😄 .

**Comment by Tyriar** [comment]
Are you sure? The space seems to be filled with `&nbsp;` indicating to me that the terminal was resized correctly, just not refreshed.

![image](https://cloud.githubusercontent.com/assets/2193314/15739437/e524cbb0-2864-11e6-8b45-eeda9c166cff.png)

![image](https://cloud.githubusercontent.com/assets/2193314/15739445/ef366ea6-2864-11e6-8621-012bb8f037ea.png)

**Comment by parisk** [comment]
Not sure if this is the case. The line is always filled with trailing `&nbsp;`s.

**Comment by Tyriar** [comment]
This is definitely a problem with xterm.js, plugged into vscode which resizes the terminal correctly results in the same problem.

Notice lines above which should be reflowed/redrawn after a resize. The command is also cut off until I hit <kbd>&larr;</kbd> which reveals the rest.

![image](https://cloud.githubusercontent.com/assets/2193314/15798969/a515d73c-2a01-11e6-855a-ac46f55c2c0c.png)

**Comment by parisk** [comment]
Okay, re-opening this. Could you please supply me with some instructions on testing this with vscode?

**Comment by Tyriar** [comment]
@parisk it repros on sourcelair just the same as vscode. You can try on vscode though using the [tyriar/xtermjs_terminal](https://github.com/Microsoft/vscode/tree/tyriar/xtermjs_terminal) branch.

Instructions are [here](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source) to setup. After the regular npm install you'll probably need to install xterm explicitly to get around the npm-shrinkwrap.json

```
npm i xterm
```
