### ISSUE TITLE
How change port from 3000?

### ISSUE THREAD

**Issue by seanvree** [sourcelair/xterm.js#630]
how do I change the default port from 3000? also, If I'm serving this behind my webserver, do I need to configure my FQDN for reverse proxy?

I'm also not able to connect to the local service from another machine on my lan: 192.168.1.20

```
 Not Found: /

```

## Details
Chome Version 57.0.2987.133 (64-bit)
- OS version: Windows 10
* master 18a9f05 Merge pull request #628 from saulcosta18/patch-1

### Steps to reproduce

1. Launch browser on LAN from remote machine:  http:192.168.1.20:3000
2. LOCALHOST:3000 works fine on the server where xterm.is running. 
3. Firewall disabled.

**Comment by parisk** [comment]
Hi @seanvree, xterm.js is a front-end library so it has nothing to do with ports.

If you are talking about the demo though, just run the following command in your terminal and you should be ready to go:

```
PORT=11235 npm run dev
```

😄

**Comment by seanvree** [comment]
thanks @parisk ,

I'm still a bit confused about the CMD tho.  

 - are you sure the PORT attrib goes before NPM? when I run that command I get 'PORT' is not a recognized cmd?


````

C:\WINDOWS\system32>cd C:\xterm

C:\xterm>PORT=8200 npm run dev
'PORT' is not recognized as an internal or external command,
operable program or batch file.

C:\xterm>port
'port' is not recognized as an internal or external command,
operable program or batch file.

C:\xterm>nohup PORT=8200 npm run dev
nohup: ignoring input and appending output to 'nohup.out'
nohup: failed to run command 'PORT=8200': No such file or directory

C:\xterm>npm start PORT=8200

> xterm@2.5.0 prestart C:\xterm
> npm run build


> xterm@2.5.0 build C:\xterm
> gulp build

[09:26:31] Using gulpfile C:\xterm\gulpfile.js
[09:26:31] Starting 'tsc'...
[09:26:34] Finished 'tsc' after 3.21 s
[09:26:34] Starting 'browserify'...
[09:26:34] Finished 'browserify' after 231 ms
[09:26:34] Starting 'sorcery'...
[09:26:34] Finished 'sorcery' after 66 ms
[09:26:34] Starting 'build'...
[09:26:34] Finished 'build' after 41 μs

> xterm@2.5.0 start C:\xterm
> node demo/app "PORT=8200"

App listening to http://127.0.0.1:3000

```

So what am I doing wrong?

**Comment by parisk** [comment]
I see. My instructions were for Unix-like systems like macOS and Linux.

Not sure how you can set environment variables on Windows tbh.
