### ISSUE TITLE
Using addons in coffeescript

### ISSUE THREAD

**Issue by Zundrium** [sourcelair/xterm.js#633]
The normal way to include an addon with xterm.js is like this:
```
<script src="node_modules/dist/xterm.js"></script>
<script src="node_modules/dist/addons/fit/fit.js"></script>
```
But in CoffeeScript, I can't seem to find a way to import these together under a single object. 

```
Terminal = require 'xterm'
xterm_fit = require 'xterm/dist/addons/fit/fit.js'
```
The `new Terminal` works fine, but obviously the `fit()` method isn't appended to the prototype. Can anyone tell me how to do this?

**Comment by parisk** [comment]
Hi @Zundrium!

That's because you should use the [`loadAddon` method](https://xtermjs.org/docs/api/terminal/#loadaddonaddon-callback) to load an add-on and "overload" the `Terminal` prototype 😃 .
