### ISSUE TITLE
Preventing page scroll on initialization

### ISSUE THREAD

**Issue by saulcosta18** [sourcelair/xterm.js#640]
I'm trying to place terminal scrolled out of view on a page, however when it's initialized the page scrolls to the terminal element. I've been through the source code some and don't see a clean way of disabling this functionality ― any suggestions?

**Comment by parisk** [comment]
Hi @saulcosta18! What if you avoid [`open`ing](https://xtermjs.org/docs/api/terminal/#openparent) it, until you need it.

The way we hide terminals in SourceLair though is with CSS.

**Comment by Tyriar** [comment]
@parisk does `open` force a focus or something?

**Comment by saulcosta18** [comment]
@Tyriar Yep, looks like it [does one](https://github.com/sourcelair/xterm.js/blob/master/src/xterm.js#L700) to ensure that `focus` exists?

I overrode `Terminal.prototype.focus` which is doing what I need, but not the cleanest solution.

**Comment by Tyriar** [comment]
Yeah I'm not so sure why that's there then, the comment is a little puzzling as it's actually focusing, not checking the existence of the function (which shouldn't be necessary). @parisk any issues with removing this line?

**Comment by parisk** [comment]
The best way to go is make it an easy-to-use option, in order not to break the API.

I opened up a PR for this: #645, which solves this by passing an argument to `open.
