### ISSUE TITLE
Stop focusing automatically when opening the terminal in a DOM node

### ISSUE THREAD

**Issue by parisk** [sourcelair/xterm.js#646]
When using `open` to expose an xterm.js terminal in the DOM, the terminal gets focus automatically.

This may be useful for very simple use cases (like the demo of xterm.js), but it can make it difficult for more complex applications to control where the focus is.

The best thing to do here is stop focusing on the terminal inside `open` and let the user decide when to focus.

Initiated from #640.

**Comment by manoletto** [comment]
Ok, but how to set focus so,
and make the cursor appear ?!

**Comment by totomz** [comment]
@manoletto I guess we have to explicitly call `term.focus()`
