### ISSUE TITLE
vi gets double input

### ISSUE THREAD

**Issue by cbyzy2016** [sourcelair/xterm.js#650]
I use xterm with websocket to be ssh client on browser.It's nice when I use without vi command.
![it s very nice](https://cloud.githubusercontent.com/assets/25931296/25654321/3284b958-3023-11e7-999a-d15abbafaab1.jpg)
But, if I try to edit some file with vi, 
![double input](https://cloud.githubusercontent.com/assets/25931296/25654365/55aa3502-3023-11e7-8f2b-5ad00df28585.jpg) it looks like this.
How can I fix it？

xterm version : 2.5.0

var term = new Terminal(80, 24, function(key){
// this use websocket send data; I found it execute twice, even though I click keyboard one time
})

**Comment by cbyzy2016** [comment]
xterm version : 2.5.0

var term = new Terminal(80, 24, function(key){
    // this use websocket send data; I found it execute twice, even though I click keyboard one time
})

**Comment by cbyzy2016** [comment]
use term.on('data', func) fixed it

**Comment by WonderZC** [comment]
I  use term.on('data', func)  but has the same problem, could you please tell me how to fix it ?

**Comment by Tyriar** [comment]
@WonderZC if you're seeing double characters, that means you're sending each character twice to xterm.js.

**Comment by JaswandiLande** [comment]
Hi @cbyzy2016 , I am facing similar problem when I am using terminal.onKey event. Like you said, Using terminal.onData will resolve the double input issue.
But another problem is there.
When I press spacebar, page is automatically being scrolled up/down . To prevent this, I used preventdefault for domevent in onkey. As onkey has keyboard event and actual string. But ondata does not have keyboardevent/domevent property. So what can be done in that case to prevent scrolling?
Can anyone help please?

**Comment by Tyriar** [comment]
@JaswandiLande I think space should only be doing that if you mess with the event in either `onKey` or `attachCustomKeyEventHandler`. You could try reproduce the issue in [the demo](https://github.com/xtermjs/xterm.js/wiki/Contributing#running-the-demo) to see if it's a bug on our end or yours.
