### ISSUE TITLE
Terminal links with mixed styles don't work

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#654]
VS Code issue: https://github.com/Microsoft/vscode/issues/25991

**Comment by Tyriar** [comment]
This also happens when the cursor is in the middle of a link as the cursor is a top-level span:

<img width="750" alt="screen shot 2017-06-09 at 11 42 16 am" src="https://user-images.githubusercontent.com/2193314/26989687-d36fb262-4d08-11e7-9131-c72b8e91809c.png">

**Comment by LucaT1** [comment]
Is this still reproducible with the new render?

**Comment by Tyriar** [comment]
Yep, no more dealing with DOM nodes 😃
