### ISSUE TITLE
Terminal offset after echoing certain Unicode strings.

### ISSUE THREAD

**Issue by MartyGentillon** [sourcelair/xterm.js#656]
In the terminal, type `echo '<胡雨軒 Петр>'` after which, the terminal display is misaligned as demonstrated below.  It will remain so until the line containing <胡雨軒 Петр> scrolls off screen.

```
Marty @ C:\Users\Marty
> echo '<胡雨軒 Петр>'
<胡雨軒 Петр>
                                                                                                                    Mar
ty @ C:\Users\Marty                                                                                                 >
```

This affects other shells like bash:

```
> bash
[Marty@Bolt:Marty]<265>$ echo '<胡雨軒 Петр>'
<胡雨
軒 Петр>                                                                                                          [Mart
y
@Bolt:Marty]<266>$
```
## Details
- Browser and browser version:  Visual Studio code
- OS version: windows 10 creators
- xterm.js version:   "xterm@2.5.0"

**Comment by Tyriar** [comment]
This is related to the Windows 10 Creators Update. See https://github.com/Microsoft/vscode/issues/19665
