### ISSUE TITLE
Copying terminal output copies all trailing whitespace

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#66]
Copying this:

![image](https://cloud.githubusercontent.com/assets/2193314/15738520/8d5c1234-2860-11e6-9fc0-10ebe9641ce9.png)

Pasted result:

![image](https://cloud.githubusercontent.com/assets/2193314/15738530/9f62cc02-2860-11e6-8c92-beaa024d486a.png)

**Comment by parisk** [comment]
Thanks for reporting. Will take a look into how could we avoid that. Most probably it will be a hook on the `copy` event.

**Comment by Tyriar** [comment]
What are your thoughts on pulling in an npm dependency so that xterm.js is no longer self contained? Specifically [clipboard.js](https://clipboardjs.com/) as copying to clipboard seems especially tricky in a browser scenario.

**Comment by parisk** [comment]
@Tyriar we prefer keeping xterm.js as a self-contained library. It seems that we managed to fix this relatively easy in c02cc8449856f5952eae02d2346c3e2c298cb408 though, without any external dependencies.

Feel free to try this out! It would help us moving forward with merging of #78.

**Comment by Tyriar** [comment]
I was doing essentially the same thing only `ev.clipboardData.setData('text/plain', copiedText);` didn't seem to be working in Chrome (needed more tinkering) and support across other older browsers is limited with this approach.

**Comment by parisk** [comment]
I tried across multiple browsers and this seemed to work everywhere.

Support across older browsers is not a priority for this library though at the moment, thus let's keep this simple until another issue comes up with this.
