### ISSUE TITLE
Is Addons also compatible with browsers?

### ISSUE THREAD

**Issue by maruilian11** [sourcelair/xterm.js#665]
Hi, I'm from [cdnjs](https://github.com/cdnjs/cdnjs). Recently we want to host your popular lib on https://cdnjs.com. Just want confirm that are `attach.js`, `fit.js`, `fullscreen.js`, `linkify.js` and `terminado.js` also compatible with browsers? Thank you!

https://github.com/cdnjs/cdnjs/pull/10764

**Comment by Tyriar** [comment]
linkify.js has been removed and was buggy. In general addons are supported in the same list of browsers as xterm.js.
