### ISSUE TITLE
The .xterm-helpers element containing textarea prevents selection in top left corner of terminal

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#67]
Cursor is over the second character `y` in this image:

![image](https://cloud.githubusercontent.com/assets/2193314/15738582/dd4df37a-2860-11e6-8a66-95ea584a3707.png)

**Comment by parisk** [comment]
We have decided to drop the hidden textarea, and I am already working on a branch to replace it. I guess I will put it in higher priority since we are not the only ones running into them.

**Comment by Tyriar** [comment]
Another problem with the textarea, after adding the styles to vscode integration I see the textarea resizer when the terminal has focus.

![image](https://cloud.githubusercontent.com/assets/2193314/15798976/fe231240-2a01-11e6-850d-0b68e626d0f3.png)

**Comment by parisk** [comment]
Most probably this won't exist after merging of #78.
