### ISSUE TITLE
paste still doesn't work

### ISSUE THREAD

**Issue by xujihui1985** [sourcelair/xterm.js#671]
## Details
- Browser and browser version: 
- OS version: 
- xterm.js version: 

Browser  chrome
OS  mac
xterm.js latest version

### Steps to reproduce

1.  run demo project use fake terminal without websocket

**Comment by parisk** [comment]
Thanks for reporting this @xujihui1985.

Can you checkout the patch attached in #674? This should fix the issue.

**Comment by xujihui1985** [comment]
awesome, I will check that out, thank you @parisk

**Comment by xujihui1985** [comment]
@parisk, I have tested this patch, it works.
