### ISSUE TITLE
Reconnect with same PWD 

### ISSUE THREAD

**Issue by PradeepJaiswar** [sourcelair/xterm.js#677]
I am using xterm.js in my project. Every time I refresh my page or reconnect socket when a socket connection is broken due to internet fluctuation from the client. The current PWD directory is lost and it falls to specified `CWD` directory which is user home in my case. So again I have to do cd where I was working.

How can I connect and remain at same PWD where I was last time before page refreshing or socket disconnect?

One of the things I tried is to store `term` object and connect through the same object when reconnecting if it is already present. Not deleting process and object in on WebSocket disconnect.

```
var http = require('http');
var express = require('express');
var app = express();
var expressWs = require('express-ws')(app);
var pty = require('node-pty');
var cors = require('cors');
app.use(cors());
app.options('*', cors());
var terminals = {}; //global terminals

function getUser(token) {
    return new Promise((resolve, reject) => {
      try {
        return http.get({
            host: '',
            path: '',
            headers: {'token': token}
        }, function(response) {
            // Continuously update stream with data
            var body = '';
            response.on('data', function(d) {
                body += d;
            });
            response.on('end', function() {
                return resolve(JSON.parse(body));
            });
        });
      } catch (err) {
        console.log('Api failed');
        console.log(err);
        reject;
      }
    })
}

app.ws('/terminals/:user_id', function (ws, req) {
  try {
    getUser(req.params.user_id) /* cheking with api if user exist in my database*/
      .then(user_info => {
        if(terminals[parseInt(req.params.user_id)]){
          var term = terminals[parseInt(req.params.user_id)];
        }else {
          var term = pty.spawn(process.platform === 'win32' ? 'cmd.exe' : 'bash', [], {
            name: 'xterm-color',
            cwd: cwd,
            env: process.env
          });
          terminals[parseInt(req.params.user_id)] = term;
        }

        term.on('data', function(data) {
          ws.send(data);
        });

        ws.on('message', function(msg) {
          term.write(msg);
        });

        ws.on('close', function () {
          // process.kill(term.pid);
          // delete terminals[parseInt(req.params.pid)];
          // delete logs[req.params.pid];
        });
      })
      .catch(err => {
      })
  } catch (err) {
      console.log('Terminal webSocket failed');
      console.log(err);
  }
});

app.listen(3000);

```

This is not working for me. This gets me connect only first time but when I refresh my page terminal does not connect with existing store object.

Also, this has a problem if the spawned process is killed by the system but it still remains in javascript object and script try to reconnect with same term object it will fail.

Update:: I noticed that on event in not getting bind again to new term object which was saved.

Any guidelines how to achieve reconnect with same PWD.

## Details
- OS version: Mac OS
- xterm.js version: 2.2.3

**Comment by Tyriar** [comment]
So there's 2 options:

1. Record the cwd on your server and when it reconnects initialize the pty with that cwd.
2. Keep the pty running when the client disconnects and then wait on https://github.com/sourcelair/xterm.js/issues/595 to be implemented which will allow xterm.js to save/restore state.

**Comment by PradeepJaiswar** [comment]
Going with the first approach and I am able to record the CWD of the user.

Can you guide why cwd option is ignored when I user `sudo su - username` while spawning the process. It takes me to `/home/user_name` no matter what I pass in cwd

```
  var term = pty.spawn('sudo', ['su','-',user_name], {
          name: 'xterm-color',
          cwd: stored_cwd,
          env: process.env
        });
```

**Comment by exsilium** [comment]
@PradeepJaiswar You could potentially use tmux or screen to setup the session and during reconnection you just restore the multiplexer's session for the user.

I've been trying to store the terminal object in the session myself. Example implementation you can see here: https://github.com/exsilium/cloud9/blob/development/plugins-server/cloud9.ide.terminal/tty.js#L125 (you can try it out if you have some time). However, when migrating over to node-pty and xterm I've ran into some low level node issues as i've documented here: exsilium/cloud9#30

**Comment by Tyriar** [comment]
@PradeepJaiswar not sure, maybe something like this would work better?

```js
pty.spawn('bash', ['-i', '-c', 'sudo su - ' + user_name]
```

**Comment by PradeepJaiswar** [comment]
@Tyriar thanks for reply but it did not worked :(

**Comment by PradeepJaiswar** [comment]
If anyone facing the same issue. This can be also solved by just updating the `~/.bashrc`

Putting below two line in `~/.bashrc` file worked for me
```
PROMPT_COMMAND+='printf %s "$PWD" > ~/.storepwd'
[ -s ~/.lastdirectory ] && cd `cat ~/.lastdirectory`
```

Ref https://stackoverflow.com/questions/767040/save-last-working-directory-on-bash-logout
