### ISSUE TITLE
Selection goes crazy when you start dragging and then use mouse wheel

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#68]
Start:

![image](https://cloud.githubusercontent.com/assets/2193314/15738918/78877e50-2862-11e6-91bc-17fbcb4ab59b.png)

Mouse wheel up:

![image](https://cloud.githubusercontent.com/assets/2193314/15738936/8ae2c244-2862-11e6-99d0-5e9f72df7c61.png)

**Comment by parisk** [comment]
Wild guess is that this is related to #67.

**Comment by Tyriar** [comment]
I think it's to do with the DOM being changed radically after a scroll, so the cursor ends up at the top-left (start) of the terminal.

**Comment by parisk** [comment]
This could be the case as well. Implementing natural scrolling, instead of virtual one, seems like could fix most of these issues.

**Comment by Tyriar** [comment]
That would probably lead to perf issues if the terminal buffer is too big, plus scrolling would not jump in character length blocks which would feel strange.

**Comment by parisk** [comment]
We could apply a limit to the terminal buffer size, which is something that even native apps do (e.g. [Terminal.app](https://discussions.apple.com/thread/2123671?tstart=0)).

**Comment by Tyriar** [comment]
I think it would be worth trying to get around the scrolling issues doing something like https://github.com/sourcelair/xterm.js/issues/69 before considering this route. That's a lot of DOM elements and imo the way it currently works is one of the great things about term.js; that it's footprint on the DOM is relatively small while maintaining a large buffer.

Plus it would probably need to recreate most lines on resize which could cause performance issues with a reasonably sized buffer limit.

**Comment by Tyriar** [comment]
Fixed in https://github.com/sourcelair/xterm.js/pull/670
