### ISSUE TITLE
Improve focus/blur state

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#681]
Currently clicking in the terminal will cause a blur on mousedown and a focus on mouseup (provided there is no selection). This results in the cursor showing a non-focused state even though technically the terminal is still focused and keyboard input will go to the shell.

Notice the selection and the cursor state:

![image](https://user-images.githubusercontent.com/2193314/26891381-acf4ca1e-4b69-11e7-826e-ae2a9ded56ec.png)

We should put a layer in between the browser textarea blur/focus events and expose our own events, that way we can cover these mouse-related edge cases without affecting the cursor state.

**Comment by mofux** [comment]
I believe this can be closed as it seems solved by #670

**Comment by Tyriar** [comment]
Yeah you're right, thanks for pointing it out! :+1:

**Comment by Tyriar** [comment]
Reopening and fixing it in my canvas_render branch. It looks like both focus and blur get triggered twice.

**Comment by twifty** [comment]
I'm calling `Terminal.focus` directly after launching a pty process. I noticed the focus was elsewhere on the page, yet a `console.log(document.activeElement)` after the `focus` call confirms the terminal was given focus.

Is there anything going on internally to cause the last focused element to regain focus?

I cannot find anything in my own code which could be doing this.

**Comment by Tyriar** [comment]
@twifty might be worth creating a new issue with versions, screenshots, etc. looks like a different problem to this issue.

**Comment by twifty** [comment]
@Tyriar I'd prefer to rule out my own code before making an issue of it
