### ISSUE TITLE
Issues with pasting on Windows in 2.7.0

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#683]
I'm seeing some weird behavior after https://github.com/sourcelair/xterm.js/pull/659. For the following string:

```
a
b
c
```

Cmd pastes on same line:

![image](https://user-images.githubusercontent.com/2193314/26909807-28f40f0a-4bb8-11e7-9496-b7d64064bcc3.png)

Powershell pastes in reverse and the cursor is on the first line:

![image](https://user-images.githubusercontent.com/2193314/26909782-f7b7109a-4bb7-11e7-9a32-084c3e54123b.png)

**Comment by KrishnaV-MSFT** [comment]
@Tyriar I believe the PowerShell issue of pasting in reverse is because of PSReadline module. If you run "rmo PSReadline" and paste, it behaves like cmd. However the cmd behavior is also wrong. We need to replicate pressing the "Enter" button.

**Comment by Tyriar** [comment]
Keep in mind this may be related to node-pty being out of date, if everything works fine in the new node-pty I should work towards updating that in xterm.js.
