### ISSUE TITLE
Selection is only possible on the text in the current viewport

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#69]
While potentially difficult, it's probably possible to do a smooth selection over multiple pages by:
- Recording start selection position
- Scroll the terminal up when dragging from terminal and cursor is close to/beyond top
- Scroll the terminal down when dragging from terminal and cursor is close to/beyond bottom
- Whenever the terminal is scrolled, reset the selection position
- When copy is triggered, intercept and select the text between the start and end (probably won't work in older browsers)

**Comment by parisk** [comment]
I think that this will be handled across with all other scrolling issues. The best thing to do IMO is bring scrolling as close as possible to native terminals found in modern OSs (e.g. Ubuntu Terminal and Terminal.app)

**Comment by Tyriar** [comment]
[hterm](https://chromium.googlesource.com/apps/libapps/+/HEAD/hterm) handles this really well but only has the currently displayed viewport in the DOM. We should see how they implement it.

**Comment by parisk** [comment]
We could mimic the way https://github.com/codemirror/codemirror does it. This could also help with #77.

**Comment by Tyriar** [comment]
Fixed in https://github.com/sourcelair/xterm.js/pull/670
