### ISSUE TITLE
Moving over CJK text jumps 2 characters at a time

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#70]
Related: https://github.com/sourcelair/xterm.js/issues/61

Initial:

![image](https://cloud.githubusercontent.com/assets/2193314/15739200/d8f27dca-2863-11e6-9620-66b58c7f7ede.png)

<kbd>&larr;</kbd>

![image](https://cloud.githubusercontent.com/assets/2193314/15739222/e42be014-2863-11e6-999c-715acf2df966.png)

Text: 안녕하십니까?

**Comment by parisk** [comment]
Thanks for reporting. Will take a look at it, along with the rest of international character issues.

**Comment by parisk** [comment]
Closed in #144.
