### ISSUE TITLE
unicode characters repeat in link

### ISSUE THREAD

**Issue by shihaonan369** [sourcelair/xterm.js#706]
## Details
- Browser and browser version: Visual Studio Code 1.13.0
- OS version: Windows 10 15063.332
- xterm.js version: 2.6.0

### Steps to reproduce

1. change director to a unicode folder(e.g. chinese folder)
2. unicode characters repeat in link
![powershell](https://user-images.githubusercontent.com/24843709/27124189-ce731fba-5122-11e7-905d-8cc8d1dc2004.png)
![vscode](https://user-images.githubusercontent.com/24843709/27124188-ce65502e-5122-11e7-9327-5a4ba63d1255.png)

**Comment by Tyriar** [comment]
This is fixed in master, coming in 2.8.0. Duplicate https://github.com/sourcelair/xterm.js/issues/642
