### ISSUE TITLE
Reloading sourcelair put cursor at start of line

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#71]
Either a Sourcelair bug or an issue with restoring state?

![image](https://cloud.githubusercontent.com/assets/2193314/15739330/64411436-2864-11e6-9dd4-092070afb8d0.png)

After <kbd>ctrl</kbd>+<kbd>c</kbd>:

![image](https://cloud.githubusercontent.com/assets/2193314/15739338/73d8ac06-2864-11e6-981d-e31122048885.png)

**Comment by parisk** [comment]
This is a known issue with implementation in SourceLair. Will be fixed soon, but does not have to do with this code base.

Thanks for taking the time to report though!
