### ISSUE TITLE
Invert colors on selection

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#75]
This would make it easier to read in addition to just being plain cool

```
/* blink/webkit */
.element::selection {
  color: fg;
  background-color: bg;
}
/* -moz-selection (probably deprecated) */
```

![image](https://cloud.githubusercontent.com/assets/2193314/15740365/74f25592-2869-11e6-9725-28783ee15baf.png)

**Comment by Tyriar** [comment]
Something like this would certainly be a lot easier to implement if the colors were still set via javascript instead of CSS.

**Comment by parisk** [comment]
That's true, but I think the better solution to combine both is to use a preprosessor like SCSS.

**Comment by Tyriar** [comment]
Even with a preprocessor, if the consumer wants to support more themes than are available they need to write all the styles themselves. If this is considered a feature, they will have to write the `::selection` rules.

You can see how I put this together with VS Code [here](https://github.com/Microsoft/vscode/blob/7f404bfceb141e5c7994b40c183ac3fc1d020454/src/vs/workbench/parts/terminal/electron-browser/terminalPanel.ts#L91), I could probably transform it into a theme addon relatively easily if that's preferable to adding it to xterm.js.

**Comment by parisk** [comment]
Eventually I am not sure about this. It could make the Terminal look quite weird.

Terminal.app just changes the background of the selection to gray. @Tyriar could you please provide us with a screenshot of how gnome-terminal handles this?

## Terminal.app screenshot
![image](https://cloud.githubusercontent.com/assets/1188592/15967590/fab4b832-2f30-11e6-9652-eb76bf8d29f5.png)

**Comment by Tyriar** [comment]
It sets fg to bg and bg to fg when selected. The good thing about it is that it's just as readable as the original text.

![image](https://cloud.githubusercontent.com/assets/2193314/15974986/222a4746-2f00-11e6-89f1-33c1de519408.png)

![image](https://cloud.githubusercontent.com/assets/2193314/15974997/2fd29286-2f00-11e6-9406-e967a7522747.png)

**Comment by parisk** [comment]
I think I tend more towards improving the background highlighting. I think that bg/fg color inversion is not what most users are used to right now.

**Comment by Tyriar** [comment]
Closing in favor of https://github.com/sourcelair/xterm.js/issues/692
