### ISSUE TITLE
Multi-line selections do not touch each other

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#76]
At least on Chrome. This is because of:

```css
body {
    line-height: 1.4;
}
```

Before:

![image](https://cloud.githubusercontent.com/assets/2193314/15740606/62ba1968-286a-11e6-8ad1-10ebb6d7fddf.png)

After:

![image](https://cloud.githubusercontent.com/assets/2193314/15740590/4f7263ce-286a-11e6-8155-0c552aa48c46.png)

Same on demo:

![image](https://cloud.githubusercontent.com/assets/2193314/15740639/8a310628-286a-11e6-8278-fd06c610359d.png)

**Comment by Tyriar** [comment]
Ubuntu 16.04/Chrome 49

**Comment by parisk** [comment]
Seems like this is will be more cumbersome than I thought. I am pretty sure that the reason behind this is the mix of DOM Elements and Text nodes in every line.

I guess we will have to make changes in the rendering engine in order to eliminate this.

**Comment by Tyriar** [comment]
Does applying `line-height: normal;` not work?

**Comment by parisk** [comment]
@Tyriar please take a look at #83. Seems like it fixes it. Thanks a lot for helping out.
