### ISSUE TITLE
Terminal size in modal/dialog possible regression starting from 2.2.2 

### ISSUE THREAD

**Issue by marcosnils** [sourcelair/xterm.js#771]
Hi there, I think we've found a regression when trying to render terminals in modals / dialogs starting from xterm 2.2.2. I know I'm referring to a super old version, but during the weekend we updated our old xterm 2.2.2 to the new 2.8.1 and we noticed that this suddenly stopped working. 

Here are two codepen snippets to see the error:

https://codepen.io/anon/pen/weQqbE >> Terminal renders correctly per styles in dialog using xterm 2.2.2

https://codepen.io/anon/pen/PjxENm >> Last xterm.js 2.8.1 version where you can see the error.

The only difference between the two codepens is just the corresponding xterm.js file

**Comment by Tyriar** [comment]
What's the error? Works fine in Chrome v59 for me.

**Comment by marcosnils** [comment]
@Tyriar I accidentally updated the code with a workaround for the master version. Try again now with the second link. 

This is what I get:

![image](https://user-images.githubusercontent.com/1578458/28036819-d1c44654-658f-11e7-94f6-64a2c894a200.png)

**Comment by Tyriar** [comment]
The rows are not being sized correctly:

![image](https://user-images.githubusercontent.com/2193314/28037137-48b558aa-656f-11e7-9853-a44ab72fbef7.png)

**Comment by marcosnils** [comment]
Yup, realized that. Wondering why it works in 2.2.2 but not in 2.8.1 :cry:

**Comment by Tyriar** [comment]
I think it's related to how the popup dialog is being shown/hidden. Can you run xterm.open when you're 100% sure it's visible?

**Comment by marcosnils** [comment]
yup, that works. If this works as expected you can go ahead and close the issue as I already found a workaround. I was just wondering how it worked in 2.2 :)

**Comment by Tyriar** [comment]
Yeah I think this is expected now as it's a result of the more robust character measurement changes that happened some time ago. I think the root cause is that before the character would be measures by appending an element to `body`, now it's enclosed within the terminal container so `.open` needs to be on an element that's visible .

**Comment by Tyriar** [comment]
@marcosnils FYI https://github.com/sourcelair/xterm.js/issues/785

**Comment by marcosnils** [comment]
@Tyriar IIUC you're planning to add a fix for this?

**Comment by Tyriar** [comment]
@marcosnils it may fix this, you may need to call resize again though.
