### ISSUE TITLE
Terminal.resize() needs to check if CharMeasure was initialized before returning early

### ISSUE THREAD

**Issue by chrmarti** [sourcelair/xterm.js#785]
From Microsoft/vscode#20505:

Terminal.resize() needs to check if CharMeasure was initialized before returning early. PR https://github.com/sourcelair/xterm.js/pull/784

**Comment by Tyriar** [comment]
This is a corner case that we ran into in vscode where resize will not properly remeasure characters if the terminal was initialized with the correct cols and rows but was not on the Dom yet.  So the fix for this will improve support for calling `Terminal.open` without the element in the Dom yet.
