### ISSUE TITLE
Changing the font size makes selection incorrect

### ISSUE THREAD

**Issue by ManojkumarV** [sourcelair/xterm.js#787]
Changing the font size to 15px makes the selection incorrect in xterm 2.8.1. 
Is there any proper way to set the font size to terminal?
<img width="1434" alt="screen shot 2017-07-12 at 7 40 03 pm" src="https://user-images.githubusercontent.com/10399151/28121918-430ae722-673a-11e7-86c1-04ea2edc83d9.png">

**Comment by Tyriar** [comment]
When you change the font size you need to tell xterm.js to resize, whether that be by manually calling `Terminal.resize` or by using the fit addon.

**Comment by ManojkumarV** [comment]
@Tyriar I used fit addon. But even after that selection is incorrect. I changed font size directly in xterm.css file. Is this the right way to change or is there any other proper way to change font size?

**Comment by parisk** [comment]
@ManojkumarV you should avoid changing the font size in the files of the library.

You should include your own stylesheets that **override** xterm.js' styles.

Also if you can provide a minimal jsfiddle example to see your issue, that would help 😄.

**Comment by ManojkumarV** [comment]
@parisk I found a workaround for my need. I just changed the font size of the parent element of the xterm container and xterm took the font size of its parent and now the selection is working fine 😄 
Thanks a lot for your reply 😃

**Comment by parisk** [comment]
Happy to hear it worked out at last!
