### ISSUE TITLE
Terminal focus class is lost under certain conditions

### ISSUE THREAD

**Issue by mofux** [sourcelair/xterm.js#789]
The `.terminal.focus` class is unset if a program that supports mouse pointer integration is active, and the terminal receives a `mousedown` event. This causes the terminal cursor to render in an unfocused state, even if the terminal still has focus.

**How to reproduce**
Try to open `mc` or `nvim` - they support mouse pointer integration by default. Inspect the `.terminal` element classes. Once you click on the terminal (sometimes it needs multiple attempts), the `focus` class will be unset, although the terminal still has focus.

**Comment by Tyriar** [comment]
Can repro in the demo but not in VS Code, maybe VS Code's forked xterm.css works around this.

**Comment by mofux** [comment]
I was able to fix this in #781 via https://github.com/sourcelair/xterm.js/pull/781/commits/8648c12ccb31e8daa90e35574e517fda8f05fe70
