### ISSUE TITLE
Show hollow cursor when not focused

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#79]
Right now the solid cursor is shown even when the terminal is not focused, making it more difficult to tell where the application's focus is. Ideally this should be represented by a character something like this:

![image](https://cloud.githubusercontent.com/assets/2193314/15798987/4560ec04-2a02-11e6-99cf-6ee4a7e46960.png)

**Comment by Tyriar** [comment]
Due to the textarea typically having focus over `.terminal`, I don't think this can't be implemented by consumers of xterm.js currently. It needs something like a `focus` class being added to `.terminal` so it can be styled accordingly.

**Comment by parisk** [comment]
Sounds like a great enhancement. I think that after merging #78 (dropping of hidden textarea), this will be  a piece of cake to implement, with plain CSS.

**Comment by Tyriar** [comment]
Awesome :+1:

**Comment by parisk** [comment]
Hi @Tyriar could please take a look at the fix in #82. Nothing special though. Should work out of the box.

**Comment by jdmayfield** [comment]
Hi guys.  Is there a way to detect whether the terminal already has focus?  Like term.isFocused or something like that?

**Comment by parisk** [comment]
Yes @jdmayfield. The terminal object gets the [`focus` class](https://github.com/sourcelair/xterm.js/blob/v3/src/xterm.css#L47).
