### ISSUE TITLE
Terminal is initialised with the wrong cursor style

### ISSUE THREAD

**Issue by mofux** [sourcelair/xterm.js#790]
When creating the terminal, and passing the `cursorStyle` through `options`, the cursor will still be `block`. One has to trigger `setOption` before the cursor style is picked up. This is because the class for the cursor style `xterm-cursor-style-...` is not set when creating the terminal.

**Comment by Tyriar** [comment]
Nice find, repro'd in the demo. I missed this because we apply all options after the terminal is initialized.

**Comment by mofux** [comment]
I was able to fix this in #781 via https://github.com/sourcelair/xterm.js/pull/781/commits/98d9b5e26d417c6e01329ed9d188bb441c87aff6
