### ISSUE TITLE
Potential exception in selection handling code?

### ISSUE THREAD

**Issue by vincentwoo** [sourcelair/xterm.js#801]
Hi, I run xterm.js in prod and have been seeing these errors lately, post 2.8.1. I imagine it is related to the new selection handling stuff. I can't give a reliable repro case, unfortunately, but perhaps this error screenshot will be enough to hint at an obvious hypothesis. Sentry reports that this is only happening on Chrome, which is probably important somehow.

![image](https://user-images.githubusercontent.com/613320/28306567-9ee11486-6b54-11e7-899e-74924e1d89d0.png)

The relevant function here is probably

```js
SelectionManager.prototype._onSingleClick = function (event) {
    this._model.selectionStartLength = 0;
    this._model.isSelectAllActive = false;
    this._activeSelectionMode = SelectionMode.NORMAL;
    this._model.selectionStart = this._getMouseBufferCoords(event);
    if (this._model.selectionStart) {
        this._model.selectionEnd = null;
        var char = this._buffer.get(this._model.selectionStart[1])[this._model.selectionStart[0]];
        if (char[LINE_DATA_WIDTH_INDEX] === 0) {
            this._model.selectionStart[0]++;
        }
    }
};
```

I've also seen other exceptions (not exactly this one) that seem to loosely be a bad buffer dereference. Tricky indexing issue?

**Comment by Tyriar** [comment]
Exception in VS Code: https://github.com/Microsoft/vscode/issues/30939, I believe this is already fixed in https://github.com/sourcelair/xterm.js/pull/784 but we should be more defensive.

**Comment by vincentwoo** [comment]
Looking forward to 2.9.0 then! I'll close and reopen if it comes up again.

**Comment by Tyriar** [comment]
Reopening as I'm going to add a null check just in case :smiley:
