### ISSUE TITLE
Reset to initial state works incorrect.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [sourcelair/xterm.js#814]
Reset command http://vt100.net/docs/vt510-rm/RIS.html  is broken for xterm.js in the current master.

## Details
- Browser and browser version: Google Chrome 59.0.3071.115 (Official Build) (64-bit)
- OS version: Fedora 25 , Ubuntu 16.04
- xterm.js version: master 

On the Linux terminal when you type "reset", then terminal will get control sequence RIS, but for xterm.js test server side sends "Soft Terminal Reset", so I reproduced incorrect behavior with such steps:
### Steps to reproduce
1. Open demo, type some text, for example "ls -a";
2. Type command "echo -e '\033\0143\c'" or simple echo -e '\033c\c';
Expected behavior: terminal should be reset: all previous lines should be clear, terminal should render new prompt line and display cursor.
Actual behavior: terminal didn't clear lines, and cursor disappeared.

P.S: "Reset to initial state" should clear both buffer: alt and normal.

**Comment by AndrienkoAleksandr** [comment]
@Tyriar I found that function "Reset to initial state" is broken in master. I began fix it, but I am confused by side effect of this commits: https://github.com/sourcelair/xterm.js/commit/2c3d98abc8976a77df937aa675b62b77eb2bad25 
 I fixed reset for buffers alt and normal, but terminal incorrect display prompt. Test to reproduce it: 
https://github.com/sourcelair/xterm.js/pull/813/commits/cb34975364040a2cd84183357ac622555890fa3b
Can you get me more information about this fix commit?

**Comment by Tyriar** [comment]
I tried to explain it in that comment. I do not understand why that fixed the problem, but it did. Looking at the code, it looked like the correct state should have been set without it but it wasn't being set correctly.

You shouldn't need to touch the parser state there to fix this should you?

**Comment by Tyriar** [comment]
It was quite the visible bug and reproducible 100% for me if you want to try understand why it was happening https://github.com/sourcelair/xterm.js/issues/662
