### ISSUE TITLE
Output is all messed up when running apt install/remove

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#818]
Seems related to the progress bar is uses.

https://github.com/Microsoft/vscode/issues/31339

**Comment by Tyriar** [comment]
It appears to be a regression from the buffer refactor https://github.com/sourcelair/xterm.js/pull/717

**Comment by parisk** [comment]
Quite interesting. Do you have any quick thoughts on why this might be happening or should I just start digging into it?

**Comment by Tyriar** [comment]
@parisk took me most of the day to figure it out :stuck_out_tongue: fix is in https://github.com/sourcelair/xterm.js/issues/822

**Comment by parisk** [comment]
Awesome, just reviewed it. Looks great!
