### ISSUE TITLE
Expose lineFeed event

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#819]
Currently the only way to listen to things happening inside the terminal is either on refresh (fired even on prompt input) or by listening to the data stream (a huge amount of data, inefficient to parse to check for \n) being fed into xterm.js. It would be useful to have some more granularity here for example if someone wants to know when there is a new line feed added. This would allow programs that integrate with the terminal a greater understanding of what's happening.

**Comment by parisk** [comment]
Reminder to add documentation: https://github.com/xtermjs/xtermjs.org/issues/28.
