### ISSUE TITLE
Cannot focus terminal when text elsewhere on the page is selected

### ISSUE THREAD

**Issue by spadgett** [sourcelair/xterm.js#827]
If I select text somewhere else on the page, I cannot focus the terminal by clicking inside it. It works fine after I clear the selection.

![screencast 2017-08-01 13-27-32](https://user-images.githubusercontent.com/1167259/28838171-86890c58-76bd-11e7-86a6-2ba52177974e.gif)

## Details
- Browser and browser version: Chrome Version 59.0.3071.115 (Official Build) (64-bit)
- OS version: macOS Sierra 10.12.6 
- xterm.js version: 2.8.0 (and current master)

### Steps to reproduce

1. npm install
2. npm start
3. Open http://0.0.0.0:3000 in a browser
4. Select some text on the page outside of the terminal
5. Try to click inside the terminal

Problem: The terminal cannot be focused.

**Comment by mofux** [comment]
I guess this happens because we call evt.preventDefault() in a mouse handler somewhere...

**Comment by parisk** [comment]
Opened #828 to get around with this, before 2.9.0.

This was caused by old code trying to get around with selections on Firefox (#41). Since selection is taken care of by xterm.js now, this code is not needed any more.

**Comment by parisk** [comment]
Thanks for reporting this @spadgett 😄!
