### ISSUE TITLE
Focus terminal on mousedown

### ISSUE THREAD

**Issue by mofux** [sourcelair/xterm.js#830]
At the moment, we focus the terminal on `click`, which means the terminal will only be in focused state after the mouse button comes back up (`mousedown -> mouseup -> click`):
[xterm.js#L750](https://github.com/sourcelair/xterm.js/blob/49c1ca3f57699a824ac79cf5cbd3d4a338b2b8aa/src/xterm.js#L750)

The natural behaviour of inputs is to focus on `mousedown`, which would also allow us to draw the focused state while performing a selection when the terminal was previously unfocused.

Maybe we should remove the current `click` handler completely, and then move the focus() call in the mousedown handler to the very top of the handler here:
[xterm.js#L1023](https://github.com/sourcelair/xterm.js/blob/49c1ca3f57699a824ac79cf5cbd3d4a338b2b8aa/src/xterm.js#L1023)

Any thoughts?

**Comment by parisk** [comment]
Yep, sounds like a great idea. Updating #828, according to your proposal.

Thanks!
