### ISSUE TITLE
Trying to use in Ionic 3

### ISSUE THREAD

**Issue by aircable** [sourcelair/xterm.js#837]
## Environment
- Ionic 3, Typescript
- Browser and browser version: Chrome and Safari
- OS version: OSX and iOS
- xterm.js version: latest

### Steps to reproduce
https://github.com/aircable/ionic-xterm

I created a test project to integrate xterm.js into a new Ionic 3 project.
But it's not working, has many problems, including the integration of addons etc.
It compiles, but just doesn't do it.
Layout is non-existent. Tried many things. Hope you guys can help. Thanks.

**Comment by Tyriar** [comment]
You don't have xterm declared as a dependency? https://github.com/aircable/ionic-xterm/search?utf8=%E2%9C%93&q=xterm&type=

I don't think anyone in the team knows anything about ionic/angular so I don't think we can help.

**Comment by parisk** [comment]
Closing this as it was answered here: https://stackoverflow.com/a/45557432/577598.
