### ISSUE TITLE
Exception when switching buffer after resize

### ISSUE THREAD

**Issue by mofux** [sourcelair/xterm.js#842]
**Problem**

An exception is thrown (latest master and probably before) if we resize the screen to a bigger dimension while being in the `alt` screen buffer. Once the `alt` screen buffer exists and we switch back to the `normal` buffer, the exception will show up, and the terminal will stop working (blank screen).

I think this has the same root cause as #838 and likely others where the line or row data is an `undefined` reference.

<img width="825" alt="screen shot 2017-08-06 at 01 31 28" src="https://user-images.githubusercontent.com/2785983/28999436-0bccbc52-7a47-11e7-823a-3c4454a61c5a.png">

**How to reproduce**
- Start the demo
- Run a command that uses the alt screen buffer (e.g. `vim`)
- Change the rows and/or cols value to a higher value (it happens in both cases)
- Exit the app to switch back to the normal buffer

**Demo**

![crash](https://user-images.githubusercontent.com/2785983/28999420-70f71c72-7a46-11e7-8286-fa2d15da4a36.gif)

**Comment by mofux** [comment]
Obviously this happens because the renderer assumes that the dimensions of the normal buffer are in sync with the rows / cols, but they aren't. I think we have to adjust the size of a buffer to the current dimensions when activating it -- and before the renderer touches it.

**Comment by Tyriar** [comment]
Can reproduce with vim and 40x40

**Comment by Tyriar** [comment]
It appears to only happen when the normal buffer isn't filled.

**Comment by Tyriar** [comment]
Yeah it's related to not filling in the `normal` buffer's rows when the rows increase. Can reproduce with vim and rows+1.

**Comment by Tyriar** [comment]
Related to https://github.com/sourcelair/xterm.js/issues/510. I think when BufferSet was added, checks were removed so we no longer clear the normal buffer when resizing in the alt buffer. Apparently we missed this one case.

**Comment by Tyriar** [comment]
Here's the change that broke it: https://github.com/sourcelair/xterm.js/pull/717/files#diff-5eb84354a70d0df188b3bbb5566120bbL1139

**Comment by Tyriar** [comment]
Here's the line that prevented this: https://github.com/sourcelair/xterm.js/pull/717/files#diff-d4f745d6f29faa0617f2e02bb95f0c44L2039

**Comment by Tyriar** [comment]
The same also breaks when rows change in the other direction, the scrollbar shows there is more content but you can't scroll it (because they're blank lines).

**Comment by Tyriar** [comment]
Obscure bug I ran into while coming up for a fix here. after `activateAltBuffer` if called, there is a hard reset on the terminal which tries to carry `buffers` over but it's initialized and `buffer` (the convenience var) is set to the active buffer that we create and discard.

**Comment by mofux** [comment]
You're a genius, thanks @Tyriar!

**Comment by dgriffen** [comment]
Hey, I just thought I'd report that I'm still having this issue with the 2.9.1 release of xtermjs. Right after I call `term.open(...)` I call `term.fit()` and I get the same exception. It's not 100% consistent but it happens frequently enough to be an issue. 2.8.1 does not have this problem for me.

**Comment by parisk** [comment]
@dgriffen is there any chance that what you are reporting is this: #860?
