### ISSUE TITLE
bell() function never gets called 

### ISSUE THREAD

**Issue by npezza93** [sourcelair/xterm.js#853]
It doesn't appear the `bell()` function is ever getting called. I was trying to play with what sound gets played but I couldn't get the function to be called. I made sure to set visualBell and popOnBell to true. Is there a config I am missing?

In Terminal.app if you press the down arrow you get a sound and same goes with Hyper.

## Details
- Browser and browser version: 
- OS version: MacOS Sierra
- xterm.js version: latest

### Steps to reproduce

1. Press the down arrow

```js
Terminal.prototype.bell = function() {
  if (!this.visualBell) return;
  var self = this;
  this.element.style.borderColor = 'white';
  setTimeout(function() {
    self.element.style.borderColor = '';
  }, 10);
  if (this.popOnBell) this.focus();
};
```

**Comment by Tyriar** [comment]
You're right, it doesn't seem to do much currently.

Related: term.js added a 'bell' event after this was forked to allow custom sounds https://github.com/chjj/term.js/commit/877d6fe53080c1d67d9b7b4c248657a30e502b1b

**Comment by Tyriar** [comment]
hyper/hterm does this by loading in an ogg data uri:

- https://github.com/dbkaplun/hterm-umdjs/blob/c24b05b3aef8f88c54fe6a2784e89681341eae9e/dist/index.js#L13104
- https://github.com/dbkaplun/hterm-umdjs/blob/c24b05b3aef8f88c54fe6a2784e89681341eae9e/dist/index.js#L29568
