### ISSUE TITLE
Can I use xterm for backend only without dom object?

### ISSUE THREAD

**Issue by zhaoyi0113** [sourcelair/xterm.js#854]
I am going to create a terminal web project. But I want to separate frontend and backend. The backend, which is nodejs, will serve restful APIs for frontend. I checked that `xterm.js` works really awesome and want to include `xterm.js` in my backend. 

So the scenario will be that frontend has an editor on the browser, it will send commands to backend when users hit enter. Backend will send the commands into `xterm.js` and listen on its output. Then send the output back to the frontend.  In other words, I want to emulate a terminal in my backend server. 

I checked the `xterm.js` doc and found that `xterm` has to be created with a dom object. Is this possible to use `xterm` without dom object?

**Comment by Tyriar** [comment]
xterm.js is a frontend, it doesn't really work as a backend. You cannot create it without a DOM.

> So the scenario will be that frontend has an editor on the browser, it will send commands to backend when users hit enter.

It sounds like you want a text box that just sends a command to a server which runs a child processes and sends the output? If that's all you want you should not use xterm.js/node-pty as they overcomplicate things and don't do what you want. What you can do if you do a setup like the xterm.js demo however is run interactive programs like git as it's a true terminal.

**Comment by zhaoyi0113** [comment]
Yep, your understanding is correct. I need to use `node-pty` to handle the pty output from a backend process. And it is not easy to deal with `ansi` code. So I want to use `xterm.js` to help me to handle ansi characters. I see `xterm` is listening on websocket channel. 
`xterm` is a javascript library which means it should work with nodejs backend application as well. How about I create an instance of xterm in the nodejs and listen on its output? Is it possible?

**Comment by Tyriar** [comment]
@zhaoyi0113 why not just run the command in a [child process](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options)?

**Comment by zhaoyi0113** [comment]
child process doesn't have pty. The sub-process I am going to create is a `mongo` shell process. It is an interactive terminal. I do need `pty` to handle the input and output. I see that when I call `xterm.write` it will parse the data and render it on the dom. Is it possible that I attach a listener on `xterm` to get the parsed output?

**Comment by Tyriar** [comment]
If you need a pty then use xterm.js on the client side then, that's what it's designed for.

The demo works by sending key/mouse events to the server which are handled by node-pty, node-pty then sends back *both* the output. Note that the output includes the *input* that was send from xterm.js after it's been evaluated by mongo. This is what you want, isn't it?

**Comment by zhaoyi0113** [comment]
That's a good suggestion. But one more requirement is that I need to do some format on `xterm` output before rendering it on the dom. Is there a method or injector I can use to do that?

**Comment by Tyriar** [comment]
There isn't currently. The issue there though is more the renderer has a strict format and you couldn't do that even if it was running on some server.

**Comment by zhaoyi0113** [comment]
I see there is a `Parser.ts` file. Is it used for parsing `ansi` characters? I wonder whether I can use this `parser` class independently?

**Comment by Tyriar** [comment]
Sounds like you need everything though..? The rendering, the input handling, the parsing. If you just take the Parser (ignoring the fact it changes) then you will still need to convert key presses, maintain a buffer, deal with rendering, etc.

**Comment by zhaoyi0113** [comment]
I only need the parsing part and I don't want to handle the key press, render, cursor movement etc. I just need to take the data from pty output then parse it.

**Comment by Dhruv1969Karnwal** [comment]
@zhaoyi0113 find any way of parsing the output ?

**Comment by Tyriar** [comment]
@Dhruv1969Karnwal [`@xterm/headless`](https://www.npmjs.com/package/@xterm/headless) now exists which runs in node

**Comment by Dhruv1969Karnwal** [comment]
@Tyriar my concern is that I only need the parsing part to show terminal emulator output in ui (accordingly)

**Comment by Tyriar** [comment]
@Dhruv1969Karnwal you probably won't find better than that module tbh, a lot of effort went into making it fast and slim wrt to performance. It's so fast VS Code actually runs xterm headless on a different process in order to enable restore terminal contents after reloads/crashes.
