### ISSUE TITLE
How can xterm integrate with react component?

### ISSUE THREAD

**Issue by zhaoyi0113** [sourcelair/xterm.js#859]
I am using reactjs as frontend framework. After read some demos from `xterm`, I found I have to attach a dom to xterm object in order for rendering. But for reactjs, it has its own rendering method. How can I make xterm to render in react component? How does these two libraries integrate with each other?

**Comment by Tyriar** [comment]
Duplicate of https://github.com/sourcelair/xterm.js/issues/260
