### ISSUE TITLE
Potential cannot set property of undefined exception in refresh

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#86]
I've managed to reproduce an issue in jeremyramin/term.js where calling refresh while explicitly indicating an end row can cause a undefined exception, see https://github.com/Microsoft/vscode/issues/7357

Looking at the code for xterm.js it looks like this particular case will still occur so here's what I'm doing:

Calling `this.terminal.refresh(0, this.terminal.rows);` causes an exception within the `refresh` function on the line `this.children[y].innerHTML = out;`. In other words, this.terminal.rows is not sufficiently validated or there are missing children that are expected.

**Comment by Tyriar** [comment]
After investigating this issue further it seems that `this.children.length` is 19, and I was calling `this.terminal.refresh(0, this.terminal.rows);` where this.terminal.rows was 19 as well. So I should be calling `this.terminal.refresh(0, this.terminal.rows - 1);`.

However, the beginning of the method seemingly has a safeguard against this:

```js
  if (end >= this.lines.length) {
    this.log('`end` is too large. Most likely a bad CSR.');
    end = this.lines.length - 1;
  }
```

The issue here is that `this.lines.length` is 225, not 19. So it seems to be validating against the entire buffer (225 rows) when I only care about, and it only makes sense to refresh the contents of the viewport (19 rows).

**Comment by parisk** [comment]
@Tyriar do you consider this still a bug, or could we move forward with closing it?
