### ISSUE TITLE
Error after resizing both row and column at the same time.

### ISSUE THREAD

**Issue by benoitbzl** [sourcelair/xterm.js#860]
In the case the terminal row and column are increased at the same time (calling term.resize() once), only the existing rows have their number of characters increased. The new rows are created with the previous number of columns. It seems to be a regression compared to xterm.js 2.9.0.

At the first refresh of the terminal, the error reported in the browser console is:
Uncaught TypeError: Cannot read property '0' of undefined
    at Renderer.10.Renderer._refresh (Renderer.ts:170)
    at Renderer.10.Renderer._refreshLoop (Renderer.ts:99)

## Details
- Browser and browser version: Chrome 59.0.3071.115
- OS version: Windows
- xterm.js version: 2.9.1

### Steps to reproduce

1.  Create a term object with 1 row and 1 column (for example)
2.  Resize the terminal to 24 rows and 80 columns. 
3.  Check the first row is resized to 80 columns (80 characters), but the second row is defined as a line with only one character (array of one element).

**Comment by parisk** [comment]
Thanks for reporting this! I was able to reproduce in the demo.

**Comment by parisk** [comment]
This will most probably make the cut for `2.9.2`.

**Comment by benoitbzl** [comment]
Thanks! In the meantime, I am working around the issue with two calls to term.resize() so there isn't a rush for a fix on my side.

**Comment by wlib** [comment]
This appears to be the bug I have with 2.9.1. You can reproduce it quite easily by going [here](http://rawgit.com/fauxOS/demo/54597dde8576bfc75cf8ebdb8fc4259f3f1b1f66/index.html)

**Comment by Tyriar** [comment]
Repro using demo: `term.resize(100, 30)`

**Comment by Tyriar** [comment]
I know why it's happening, PR coming soon.

**Comment by Tyriar** [comment]
Fix is out in https://github.com/sourcelair/xterm.js/pull/873 with a regression test.

@parisk once it's merged I'll pull it into `v3` in another PR as there will be conflicts. Also we can do a better fix on the `v3` branch like pulling `blankLine` into `Buffer`?
