### ISSUE TITLE
TypeError on clicking into terminal. Doesn't seem to affect functionality

### ISSUE THREAD

**Issue by Craigzyc** [sourcelair/xterm.js#876]
I'm not sure what is causing this, its possible its something with my implementation but every time I click into the xterm window it throws this error. 
It does seem to be working correctly despite the error.
If this makes any difference the xterm terminal is opened inside a modal.

The 41 number is different everytime 
```
xterm.js:2578 
Uncaught TypeError: Cannot read property '41' of undefined
    at SelectionManager._onSingleClick (xterm.js:2578)
    at SelectionManager._onMouseDown (xterm.js:2542)
    at HTMLDivElement._mouseDownListener (xterm.js:2383)
```

## Details
- Browser and browser version: Chrome 60.0.3112.90
- OS version: windows 7
- xterm.js version: Not sure of version since its not in the code. Im just using xterm.js and xterm.css both downloaded approximately 4 weeks ago

### Steps to reproduce

1. open terminal
2. click

**Comment by mofux** [comment]
Can you try to update to the latest version of xterm.js (2.9.2) and see if the error still persists? We have added some checks in the past few weeks and days to avoid these kind of errors.

**Comment by Craigzyc** [comment]
I have updated, no more issues. Thank you
