### ISSUE TITLE
Require search addon

### ISSUE THREAD

**Issue by ficristo** [sourcelair/xterm.js#881]
I use npm to install my deps also for frontend and requirejs to include them.
When I include addons like fit or attach the following works, but when I try to require the search addon, it seems to work but the `findNext` and `findPrevious` aren't available.
I tryed to use `Terminal.loadAddon` but it doesn't work with any addon.

```js
define(function (require, exports, module) {
    var Terminal = require("node_modules/xterm/dist/xterm"),

    require([
        "node_modules/xterm/dist/addons/fit/fit",
        "node_modules/xterm/dist/addons/search/search"
    ]);

    var term = new Terminal({});
});
```

## Details
- Browser and browser version: I'm using it in a Brackets (a code editor) extension
- OS version: Windows
- xterm.js version: 2.9.2

### Steps to reproduce

1. Use npm
2. Use requirejs
3. Include search addon

**Comment by parisk** [comment]
Hi @ficristo, can you provide any logs from your browser's developer tools console (you can toggle it by hitting <kbd>F12</kbd>).

**Comment by Tyriar** [comment]
I'm assuming I broke requirejs on addons as I didn't test when changing it, @parisk are you familiar with requirejs?

**Comment by parisk** [comment]
Yep, I am. I can take a look next week though.

**Comment by ficristo** [comment]
In the developer tools integrated in Brackets there isn't any error.

If I try to load an existing addon I get:
```js
Failed to load resource: net::ERR_FILE_NOT_FOUND
require.js:141 Uncaught Error: Script error for: node_modules/xterm/dist/addons/foo/foo
http://requirejs.org/docs/errors.html#scripterror
```

**Comment by Tyriar** [comment]
@ficristo does it really say foo or did you replace that?

**Comment by ficristo** [comment]
Sorry, I meant a **non** exisisting addon....

**Comment by ficristo** [comment]
With https://github.com/sourcelair/xterm.js/pull/926 now I see `Uncaught Error: Module name "../../xterm" has not been loaded yet for context: _. Use require([])`

**Comment by Tyriar** [comment]
Maybe a revision of how addons works as suggested in #927 would be required. It would certainly simplify things if there wasn't a cyclic dependency.

**Comment by Tyriar** [comment]
I'm consolidating all bundling/loadAddon related issues into https://github.com/sourcelair/xterm.js/issues/1018, please comment on that issue if you have thoughts :smiley:
