### ISSUE TITLE
How to use with "colors" lib?

### ISSUE THREAD

**Issue by aventurella** [sourcelair/xterm.js#895]
https://github.com/Marak/colors.js
https://www.npmjs.com/package/colors
https://www.npmjs.com/package/chalk

Is there anything preventing this from working with the lib mentioned above? It should just be dealing with the escape sequences correct?

I'm having an issue getting it to work, which is not to say it's an issue with `xterm.js` just that I am not aware of how to make it work or is an alternate color lib would be better suited.

**Comment by mofux** [comment]
How are you using it? Are you generating a coloured string and then directly write it to the xterm.js instance?

**Comment by aventurella** [comment]
Yes, for example, I just tried it with `chalk`

```
terminal.writeln(chalk.blue('Hello') + ' World' + chalk.red('!'));
```

**Comment by mofux** [comment]
I would expect this to work, as long as it generates the correct ansi escape codes for the color. How does the output from xterm look like? An uncoloured string? Can you send a screenshot?

**Comment by aventurella** [comment]
![image](https://user-images.githubusercontent.com/75315/29437227-4a237b0a-8364-11e7-8e30-c0250eca454e.png)

**Comment by Tyriar** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/2193314/29437225-4766deca-8364-11e7-8a64-e339af24f3ed.png)

![image](https://user-images.githubusercontent.com/2193314/29437232-4d3e92e8-8364-11e7-9eac-0702d7854ae9.png)

![image](https://user-images.githubusercontent.com/2193314/29437241-52867ebe-8364-11e7-89c3-3292a4211eb4.png)

Are you on windows? If so what shell are you using?

**Comment by Tyriar** [comment]
Oh wait, Windows shouldn't matter here. You wouldn't even need a shell hooked up for this to work.

I'm not sure why it's not working for you. Any errors in the console?

**Comment by aventurella** [comment]
Ya from the node repl it works, this is in the browser which I think might be the issue.

**Comment by mofux** [comment]
I think @Tyriar was writing in the chrome developer console of the xterm.js demo (see the second screenshot, `term.writeln...`). Could you try with the same string he was using and see if it works for you?

**Comment by mofux** [comment]
@Tyriar Do you think this would also work if the terminal is vanilla and wasn't connected to a tty process that sets up xterm.js first? Just thinking if there are any sequences that xterm.js consumes to set the color mode...

**Comment by Tyriar** [comment]
Works for me 
![image](https://user-images.githubusercontent.com/2193314/29437545-01b4eb9a-8366-11e7-91df-93c5bc7f65ac.png)

**Comment by aventurella** [comment]
If I format the message on the server, instead of running `chalk` in the browser I get colors. If I use `chalk` directly in the browser, I don't get any colors.. lemme try one more thing to be sure I'm not just a total idiot (it may already be too late)

**Comment by Tyriar** [comment]
@aventurella try running the `term.writeln('\u001b[34mHello\u001b[39m World\u001b[31m!\u001b[39m')` directly without `chalk`.

**Comment by aventurella** [comment]
@Tyriar ya, that works fine...

Now this has me wondering if it's not webpack doing something to chalk at bundle time.

**Comment by Tyriar** [comment]
Yeah it seems like a chalk issue then, try logging what chalk is returning or debug into the chalk call.

Closing since it's not a problem with xterm.js, I'm curious to hear the reason though.

**Comment by aventurella** [comment]
@Tyriar ok I figured it out..

Chalk is doing some auto detection to see what it should support, using this lib: https://github.com/chalk/supports-color

Long story short, chalk thinks nothing is supported color wise, so it doesn't process the strings.

```typescript
let options: any = {enabled: true, level: 2};
const forcedChalk = new chalk.constructor(options);
```
^ fixes it

where Levels are:

```
0/1?: All colors disabled
2: Basic color support (16 colors)
3: 256 color support
4: Truecolor support (16 million colors)
```

**Comment by Tyriar** [comment]
Interesting, does chalk check by checking environment variables or something?

**Comment by cdaringe** [comment]
thanks @aventurella!

@Tyriar, ready for it?  https://github.com/chalk/supports-color/blob/master/browser.js

boom.  when chalk creates its config, it asks supports-color, which returns 0 (none) for the browser.

**Comment by Tyriar** [comment]
@cdaringe but I was testing in a browser and it worked earlier? Does this happen only when you build via browserify? Don't you always run chalk through a node process? 😕

**Comment by cdaringe** [comment]
@Tyriar, correct, im talking via a browser bundler [ref](https://github.com/chalk/supports-color/blob/master/package.json#L52).  to clarify, my remark wasn't to highlight any issue with this package, rather, to just help drive further understanding :)

**Comment by mbnatafgi** [comment]
@aventurella thank you! but it seems that `chalk.constructor` is deprecated and may have been removed in the latest versions. We ought to use `chalk.Instance` instead.
