### ISSUE TITLE
Copying from the alt buffer in electron doesn't work

### ISSUE THREAD

**Issue by npezza93** [sourcelair/xterm.js#908]
Put xterm into an electron app (the example electron app inside node-pty works well to demonstrate the issue), and run something like `git log`. If you try to highlight just a SHA, by double clicking the SHA, it highlights the whole line when it shouldn't. If you click and drag to highlight the SHA and try to copy it nothing gets copied to the clipboard. This works however inside the demo app in xterm outside of electron. 

_NOTE_: This was tested on master not the v3 branch.

**Comment by Tyriar** [comment]
I can't seem to repro on v3. I believe https://github.com/sourcelair/xterm.js/commit/c2bb507fe4ffa279a15c85deafaa77ca11d12a1a#diff-5eb84354a70d0df188b3bbb5566120bbR948 fixed this issue in v3.
