### ISSUE TITLE
xtermjs can't load modules in the browser when using typescript + requirejs

### ISSUE THREAD

**Issue by dgriffen** [sourcelair/xterm.js#918]
I'm using xtermjs in the browser and writing the code with typescript compiled to AMD modules and using requirejs as the loader. When I try and run `Terminal.loadAddon('fit')` I get the following error printed to the browser console:
```
Error: Module name "addons/fit/fit" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded
```
If I try to `require(['fit'])` either by editing the primary require method in the HTML I eventually get this error:
```
Error: Load timeout for modules: ../node_modules/xterm/dist/xterm
http://requirejs.org/docs/errors.html#timeout
```
## Details
- Browser and browser version: Firefox Nightly
- OS version: Windows 10
- xterm.js version: 2.8.1

**Comment by Tyriar** [comment]
Is this the same as https://github.com/sourcelair/xterm.js/issues/881 ?

**Comment by dgriffen** [comment]
I don't believe so, #881 seems to indicate that the fit addon works. Also, the error message they give is different.

**Comment by Tyriar** [comment]
I'm consolidating all bundling/loadAddon related issues into https://github.com/sourcelair/xterm.js/issues/1018, please comment on that issue if you have thoughts :smiley:
