### ISSUE TITLE
Error: Could not release an element not yet acquired

### ISSUE THREAD

**Issue by parisk** [sourcelair/xterm.js#919]
Seems like we ran into this error in production in SourceLair and looks like it's breaking `refresh`.

@Tyriar do you have any idea if we can handle this in the object reusing pool or what would be a good practice of handling it downstream?

https://github.com/sourcelair/xterm.js/blob/7645bdd418b37a8bd176a69179c06178c8cb1130/src/utils/DomElementObjectPool.ts#L49-L51

---
## Details
- Sentry Error: https://sentry.io/share/issue/35323433302e333334303630393535/
- Browser and browser version: Chrome 60
- OS version: Windows 8
- xterm.js version: 2.9.2

**Comment by Tyriar** [comment]
The whole performance benefit of this comes from precisely calling acquire and release the correct number of times.

I notice there's probably a leak here as we're not releasing the elements. That's not this problem though.

https://github.com/sourcelair/xterm.js/blob/bfdc468d4bc823b242ada286c7e8ecc7978f2b72/src/Terminal.ts#L1942

**Comment by Tyriar** [comment]
It's hard to say if this is fixed in v3 or not. It could also have something to do sourcelair? I can't see any in our error reporting.
