### ISSUE TITLE
Can't clear the terminal programmatically

### ISSUE THREAD

**Issue by fabiospampinato** [sourcelair/xterm.js#950]
Running `node -e "process.stdout.write ( '\u001Bc' );"` should clear the terminal, but this is what I get if I run it in xterm:

<img width="136" alt="screen shot 2017-09-06 at 23 16 44" src="https://user-images.githubusercontent.com/1812093/30135021-97078290-9359-11e7-9a0a-ce5c38a361c4.png">

If I try to clear it with a `node -e "process.stdout.write ( '\033[2J\033[0f' );"` the whole thing becomes black.

Is there a way it can be cleared properly?

**Comment by Tyriar** [comment]
Using `node -e "process.stdout.write ( '\u001Bc' );" ` or `echo -e '\x1bc'` tell bash to clear, and bash gives back a response to xterm.js. I believe this is why you're seeing the prompt again. You can call `term.write('\x1bc')` to clear only the front end (xterm.js).

**Comment by fabiospampinato** [comment]
What if I don't have access to the xterm instance?

I basically want to clear the terminal when my CLI app starts, how am I supposed to do that if it gets launched from xterm?

**Comment by Tyriar** [comment]
@fabiospampinato it looks like `clear` command on Linux sends `'\x1b[H\x1b[2J'`

That translates into:

- Move cursor to (1,1) (`CUP`)
- Erase all in display (`ED`)

See http://invisible-island.net/xterm/ctlseqs/ctlseqs.html for more info

**Comment by fabiospampinato** [comment]
That works, thank you!
