### ISSUE TITLE
Cannot import addons in Electron

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#96]
`require('xterm')` points at `main` in package.json (`src/xterm.js`). As far as I'm aware, there is no way to grab the addon JS modules from a node API. Something like this would probably work:

&lt;reporoot&gt;/index.js

```js
module.exports = {
  Terminal: require('./src/xterm'),
  addons: {
    fit: require('./addons/fit'),
    ...
  }
}
```

**Comment by parisk** [comment]
We could implement a wrapper function like the following

```javascript
Terminal.loadAddOn = function (addon) {
  return require(__dirname + '/../addons/' + addon);
}
```
