### ISSUE TITLE
Programmatic usage

### ISSUE THREAD

**Issue by dolftax** [sourcelair/xterm.js#971]
I would like to require xterm from another program with a custom configuration and run it along. I don't find docs related to the same. Thanks!

**Comment by parisk** [comment]
Hello @dolftax, does this help 🙂? https://xtermjs.org/docs/guides/import/

**Comment by dolftax** [comment]
I imported `xterm` with `let Terminal = require('xterm');` but the Terminal instance doesn't have any config or start method. I would like to start the xterm server in a custom port on start of another node application.

**Comment by mofux** [comment]
@dolftax This library does not expose any `server` components, it only provides the frontend. However, you can check the xterm demo to see how you could implement the server side: 

All demo files are here:
https://github.com/sourcelair/xterm.js/tree/v3/demo

The backend of the demo that servers the xterm.js client is here:
https://github.com/sourcelair/xterm.js/blob/v3/demo/app.js
