### ISSUE TITLE
Bad letter spacing with canvas

### ISSUE THREAD

**Issue by mofux** [sourcelair/xterm.js#972]
Depending on the font and font size, the letters are spaced inaccurately. For example, using the `monaco` font with a font size of `12px` will result in a real character width of `7.203...px` but charMeasure does `Match.ceil` it to `8px`. This creates a visible `0.8px` additional gap between characters, which causes the font to look somewhat stretched:

Current (with `Math.ceil`):
<img width="539" alt="wide" src="https://user-images.githubusercontent.com/2785983/30279220-e4b93522-970c-11e7-9f2a-fff8e24a51cc.png">

Expected (without `Math.ceil`):
<img width="506" alt="correct" src="https://user-images.githubusercontent.com/2785983/30279201-d9de5dbc-970c-11e7-9950-cd688a30b983.png">

@Tyriar Do we have to Math.ceil the measured dimensions for some reason?

**Comment by Tyriar** [comment]
`Math.ceil` is there to ensure that the font is rendered on a non-floating point coordinate which I read should make it more performant, better looking and to ensure that we can clear the cell afterwards. If it was floating point then the cells would overlap each other.

**Comment by mofux** [comment]
Hmmmm... but why would they overlap? If the grid was built from the floating point values, they should still align in the grid without overlapping? Removing the `Math.ceil` from the charMeasure seems to provide a good looking result, without weird rendering or overlapping glitches (see the second shot). I think it is the responsibility of the canvas engine to render the coordinates to a pixel perfect representation on the screen, not ours.

**Comment by Tyriar** [comment]
They can overlap if they're floating point, this is exactly the situation I was afraid of:

![image](https://user-images.githubusercontent.com/2193314/30351427-22f1a8d8-97d0-11e7-9f60-02ecb16726b5.png)

However, it doesn't look like the fonts overlapping is such an issue really. There may be a shared 1px line in-between each character. This shared line will just be cleared whenever either of the character is drawn (there will usually be nothing in the line).

For the background problem, which does cause strange artifacts to appear, rounding the cells there is probably the best bet. So say that the character width is 9.5, the character at col 4 will be drawn at `9.5 * 4` (float) and the *background* at cell 4 will be drawn at `Math.round(9.5*4)`. In other words, text is drawn using floats, backgrounds are drawn using integers. This also means that the size of background may vary by 1 pixel.
