### ISSUE TITLE
Please provide an xterm.less file

### ISSUE THREAD

**Issue by amejia1** [sourcelair/xterm.js#979]
Atom packages can include CSS of external files more easily through the use of a less file (as explained at http://lesscss.org). In this way, including the xterm styles is a simple one-liner using the '@import' directive. Currently for the atom-xterm package, I'm using several steps to not only search for the xterm.css file but also to add it in Atom's styles manager.

**Comment by Tyriar** [comment]
Surely you can rename xterm.css or copy it somewhere and mess with it that way. Also it's going to be quite small in the next version, bringing in a dependency on less would be a huge devDependency for little gain.
