### ISSUE TITLE
Greek characters not displayed as monospaced in canvas

### ISSUE THREAD

**Issue by parisk** [sourcelair/xterm.js#984]
Typing Greek characters in the new canvas renderer displays them with a not monospaced font.

---

## Details
- Browser and browser version:  Chrome 60
- OS version: macOS Sierra
- xterm.js version: https://github.com/sourcelair/xterm.js/commit/cd21a24ee4fd38f3e7023215ab92e4ec1be13333 (`v3` branch)

## Steps to reproduce

1. Type some Greek characters in (e.g. `καλησπέρα`)

## Screenshot

![image](https://user-images.githubusercontent.com/1188592/30391909-ccf9da0a-98c3-11e7-95c7-7ad850d88bd2.png)

**Comment by Tyriar** [comment]
Not sure I understand the problem, it seems fine to me. Did we change the default font and now the fallback is wrong?

**Comment by mofux** [comment]
The font chain in the v3 branch is `'courier-new, courier, monospace'`, I believe it was the same before?

**Comment by parisk** [comment]
Please disregard me 😅. This happens on master too -- I just assumed that it was a v3 problem, because of the big change in the renderer.

In SourceLair we always used another font, so this was never a problem.

False alarm.
