### ISSUE TITLE
Incorrect line height with canvas

### ISSUE THREAD

**Issue by mofux** [sourcelair/xterm.js#992]
Look at the screenshot. Notice the cyan border. In xterm.js (top picture), there is a visible gap between the `|` strokes. With `lineHeight` set to `1`, I would expect the output to look exactly as in Terminal.app (bottom picture). I think this is caused because we Math.ceil the measured character height.

<img width="776" alt="line-height" src="https://user-images.githubusercontent.com/2785983/30422508-6fd97f9c-9940-11e7-9b91-45b875ce86c0.png">

**Comment by Tyriar** [comment]
I think this is related to the default font. Both these work great:

```
term.setOption('fontFamily', 'Fira Code')
term.setOption('fontFamily', 'Hack')
```

<img width="880" alt="screen shot 2017-09-14 at 9 10 05 am" src="https://user-images.githubusercontent.com/2193314/30440838-8830ae12-992c-11e7-9211-74cab165ce85.png">
